       IDENTIFICATION DIVISION.
      *
       ENVIRONMENT DIVISION.
      *
       DATA DIVISION.
         WORKING-STORAGE SECTION.
       77  I.
       01  DECKNAME.
       77  J.
       COPY in70.
      *
       PROCEDURE DIVISION.
         MOVE I TO J.
         STOP RUN.
       c1.
         compute x = length of y
         compute x = function current-date
         compute x = function length (y)
         compute x = function factorial (y)
         compute x = function current-date (1:)
         compute x = function length (y) (0:7)
         compute x = function factorial (y) (2:)
         .
       c2.
         COPY in72 REPLACING
           alpha by beta
           1-2 by 3-4
           1-2 of 5-6 by 3-4 in 7-8
           002 in 3 by 6 of 007
           5 by 6
           -5 by -6
           +007 by +0066
           3.14 by 2.71
           a (all) by b (all)
           a in b by c of d
           a in b of c by c of d in e
           a in b of c (23) by c of d in e (x - 7)
           a (length of y:) by a (length of y:)
           a (function current-date:) by a (function current-date:)
           a (function length (y):) by a (function length (y):)
           a (function factorial (y):) by a (function factorial (y):)
           a (function current-date (1:):)
              by a (function current-date (1:):)
           a (function length (y) (0:7):)
              by a (function length (y) (0:7):)
           a (function factorial (y) (2:):)
              by a (function factorial (y) (2:):)
           'abc' by 'xyz'
           "abc" by "xyz"
           x'ff' by X'EE'
           ==#VAL== by ==VALUE==
      *
           = BY =
           < BY <
           > BY >
           ( BY (
           ) BY )
           + BY +
           <> BY <>
           >= BY >=
           <= BY <=
           66 BY 66
           77 BY 77
           78 BY 78
           88 BY 88
           - BY -
           : BY :
           & BY &
           ** BY **
           * BY *
           / BY /
      *
           == = == BY == = ==
           == < == BY == < ==
           == > == BY == > ==
           == ( == BY == ( ==
           == ) == BY == ) ==
           == + == BY == + ==
           == <> == BY == <> ==
           == >= == BY == >= ==
           == <= == BY == <= ==
           == 66 == BY == 66 ==
           == 77 == BY == 77 ==
           == 78 == BY == 78 ==
           == 88 == BY == 88 ==
           == - == BY == - ==
           == : == BY == : ==
           == & == BY == & ==
           == ** == BY == ** ==
           == * == BY == * ==
           == / == BY == / ==
      *
           ACCEPT BY ACCEPT
           ACCESS BY ACCESS
           ACTUAL BY ACTUAL
           ADD BY ADD
           ADDRESS BY ADDRESS
           ADVANCING BY ADVANCING
           AFTER BY AFTER
           ALL BY ALL
           ALPHABET BY ALPHABET
           ALPHABETIC BY ALPHABETIC
           ALPHABETIC-LOWER BY ALPHABETIC-LOWER
           ALPHABETIC-UPPER BY ALPHABETIC-UPPER
           ALPHANUMERIC BY ALPHANUMERIC
           ALPHANUMERIC-EDITED BY ALPHANUMERIC-EDITED
           ALSO BY ALSO
           ALTER BY ALTER
           ALTERNATE BY ALTERNATE
           AND BY AND
           ANY BY ANY
           APPLY BY APPLY
           ARE BY ARE
           AREA BY AREA
           AREAS BY AREAS
           AS BY AS
           ASCENDING BY ASCENDING
           ASSIGN BY ASSIGN
           AT BY AT
           AUTHOR BY AUTHOR
           AUTO BY AUTO
           AUTO-SKIP BY AUTO-SKIP
           AUTOMATIC BY AUTOMATIC
           BACKGROUND-COLOR BY BACKGROUND-COLOR
           BACKGROUND-COLOUR BY BACKGROUND-COLOUR
           BACKWARD BY BACKWARD
           BASIS BY BASIS
           BEEP BY BEEP
           BEFORE BY BEFORE
           BEGINNING BY BEGINNING
           BELL BY BELL
           BINARY BY BINARY
           BLANK BY BLANK
           BLINK BY BLINK
           BLOCK BY BLOCK
           BOTTOM BY BOTTOM
           BY BY BY
           C01 BY C01
           C02 BY C02
           C03 BY C03
           C04 BY C04
           C05 BY C05
           C06 BY C06
           C07 BY C07
           C08 BY C08
           C09 BY C09
           C10 BY C10
           C11 BY C11
           C12 BY C12
           CALL BY CALL
           CALL-CONVENTION BY CALL-CONVENTION
           CANCEL BY CANCEL
           CBL BY CBL
           CD BY CD
           CF BY CF
           CH BY CH
           CHAIN BY CHAIN
           CHAINING BY CHAINING
           CHANGED BY CHANGED
           CHARACTER BY CHARACTER
           CHARACTERS BY CHARACTERS
           CLASS BY CLASS
           CLOCK-UNITS BY CLOCK-UNITS
           CLOSE BY CLOSE
           COBOL BY COBOL
           CODE BY CODE
           CODE-SET BY CODE-SET
           COL BY COL
           COLLATING BY COLLATING
           COLUMN BY COLUMN
           COM-REG BY COM-REG
           COMMA BY COMMA
           COMMIT BY COMMIT
           COMMON BY COMMON
           COMMUNICATION BY COMMUNICATION
           COMP BY COMP
           COMP-0 BY COMP-0
           COMP-1 BY COMP-1
           COMP-2 BY COMP-2
           COMP-3 BY COMP-3
           COMP-4 BY COMP-4
           COMP-5 BY COMP-5
           COMP-6 BY COMP-6
           COMP-X BY COMP-X
           COMPUTATIONAL BY COMPUTATIONAL
           COMPUTATIONAL-0 BY COMPUTATIONAL-0
           COMPUTATIONAL-1 BY COMPUTATIONAL-1
           COMPUTATIONAL-2 BY COMPUTATIONAL-2
           COMPUTATIONAL-3 BY COMPUTATIONAL-3
           COMPUTATIONAL-4 BY COMPUTATIONAL-4
           COMPUTATIONAL-5 BY COMPUTATIONAL-5
           COMPUTATIONAL-6 BY COMPUTATIONAL-6
           COMPUTATIONAL-X BY COMPUTATIONAL-X
           COMPUTE BY COMPUTE
           CONFIGURATION BY CONFIGURATION
           CONSOLE BY CONSOLE
           CONTAINS BY CONTAINS
           CONTENT BY CONTENT
           CONTINUE BY CONTINUE
           CONTROL BY CONTROL
           CONTROLS BY CONTROLS
           CONVERT BY CONVERT
           CONVERTING BY CONVERTING
           COPY BY COPY
           CORE-INDEX BY CORE-INDEX
           CORR BY CORR
           CORRESPONDING BY CORRESPONDING
           COUNT BY COUNT
           CRT BY CRT
           CRT-UNDER BY CRT-UNDER
           CSP BY CSP
           CURRENCY BY CURRENCY
           CURRENT-DATE BY CURRENT-DATE
           CURSOR BY CURSOR
           CYCLE BY CYCLE
           CYL-INDEX BY CYL-INDEX
           CYL-OVERFLOW BY CYL-OVERFLOW
           DATA BY DATA
           DATE BY DATE
           DATE-COMPILED BY DATE-COMPILED
           DATE-WRITTEN BY DATE-WRITTEN
           DAY BY DAY
           DAY-OF-WEEK BY DAY-OF-WEEK
           DBCS BY DBCS
           DE BY DE
           DEBUG BY DEBUG
           DEBUG-CONTENTS BY DEBUG-CONTENTS
           DEBUG-ITEM BY DEBUG-ITEM
           DEBUG-LINE BY DEBUG-LINE
           DEBUG-NAME BY DEBUG-NAME
           DEBUG-SUB-1 BY DEBUG-SUB-1
           DEBUG-SUB-2 BY DEBUG-SUB-2
           DEBUG-SUB-3 BY DEBUG-SUB-3
           DEBUGGING BY DEBUGGING
           DECIMAL-POINT BY DECIMAL-POINT
           DECLARATIVES BY DECLARATIVES
           DELETE BY DELETE
           DELIMITED BY DELIMITED
           DELIMITER BY DELIMITER
           DEPENDING BY DEPENDING
           DESCENDING BY DESCENDING
           DESTINATION BY DESTINATION
           DETAIL BY DETAIL
           DISABLE BY DISABLE
           DISK BY DISK
           DISP BY DISP
           DISPLAY BY DISPLAY
           DISPLAY-1 BY DISPLAY-1
           DISPLAY-ST BY DISPLAY-ST
           DIVIDE BY DIVIDE
           DIVISION BY DIVISION
           DOWN BY DOWN
           DUPLICATES BY DUPLICATES
           DYNAMIC BY DYNAMIC
           ECHO BY ECHO
           EGCS BY EGCS
           EGI BY EGI
      *    EJECT BY EJECT
           ELSE BY ELSE
           EMI BY EMI
           EMPTY-CHECK BY EMPTY-CHECK
           ENABLE BY ENABLE
           END BY END
           END-ACCEPT BY END-ACCEPT
           END-ADD BY END-ADD
           END-CALL BY END-CALL
           END-CHAIN BY END-CHAIN
           END-COMPUTE BY END-COMPUTE
           END-DELETE BY END-DELETE
           END-DISPLAY BY END-DISPLAY
           END-DIVIDE BY END-DIVIDE
           END-EVALUATE BY END-EVALUATE
           END-IF BY END-IF
           END-INVOKE BY END-INVOKE
           END-MULTIPLY BY END-MULTIPLY
           END-OF-PAGE BY END-OF-PAGE
           END-PERFORM BY END-PERFORM
           END-READ BY END-READ
           END-RECEIVE BY END-RECEIVE
           END-RETURN BY END-RETURN
           END-REWRITE BY END-REWRITE
           END-SEARCH BY END-SEARCH
           END-START BY END-START
           END-STRING BY END-STRING
           END-SUBTRACT BY END-SUBTRACT
           END-UNSTRING BY END-UNSTRING
           END-WRITE BY END-WRITE
           ENDING BY ENDING
           ENTER BY ENTER
           ENTRY BY ENTRY
           ENVIRONMENT BY ENVIRONMENT
           EOL BY EOL
           EOP BY EOP
           EOS BY EOS
           EQUAL BY EQUAL
           EQUALS BY EQUALS
           ERASE BY ERASE
           ERROR BY ERROR
           ESCAPE BY ESCAPE
           ESI BY ESI
           EVALUATE BY EVALUATE
           EVERY BY EVERY
           EXAMINE BY EXAMINE
           EXCEEDS BY EXCEEDS
           EXCEPTION BY EXCEPTION
           EXCESS-3 BY EXCESS-3
           EXCLUSIVE BY EXCLUSIVE
           EXEC BY EXEC
           EXECUTE BY EXECUTE
           EXHIBIT BY EXHIBIT
           EXIT BY EXIT
           EXTEND BY EXTEND
           EXTENDED-SEARCH BY EXTENDED-SEARCH
           EXTERNAL BY EXTERNAL
           FACTORY BY FACTORY
           FALSE BY FALSE
           FD BY FD
           FH-FCD BY FH-FCD
           FH-KEYDEF BY FH-KEYDEF
           FILE BY FILE
           FILE-CONTROL BY FILE-CONTROL
           FILE-ID BY FILE-ID
           FILE-LIMIT BY FILE-LIMIT
           FILE-LIMITS BY FILE-LIMITS
           FILLER BY FILLER
           FINAL BY FINAL
           FIRST BY FIRST
           FIXED BY FIXED
           FOOTING BY FOOTING
           FOR BY FOR
           FOREGROUND-COLOR BY FOREGROUND-COLOR
           FOREGROUND-COLOUR BY FOREGROUND-COLOUR
           FORMFEED BY FORMFEED
           FROM BY FROM
           FULL BY FULL
           FUNCTION BY FUNCTION
           GENERATE BY GENERATE
           GIVING BY GIVING
           GLOBAL BY GLOBAL
           GO BY GO
           GOBACK BY GOBACK
           GREATER BY GREATER
           GRID BY GRID
           GROUP BY GROUP
           HEADING BY HEADING
           HIGH BY HIGH
           HIGH-VALUE BY HIGH-VALUE
           HIGH-VALUES BY HIGH-VALUES
           HIGHLIGHT BY HIGHLIGHT
           I-O BY I-O
           I-O-CONTROL BY I-O-CONTROL
           ID BY ID
           IDENTIFICATION BY IDENTIFICATION
           IF BY IF
           IGNORE BY IGNORE
           IN BY IN
           INDEX BY INDEX
           INDEXED BY INDEXED
           INDICATE BY INDICATE
           INHERITING BY INHERITING
           INITIAL BY INITIAL
           INITIALIZE BY INITIALIZE
           INITIATE BY INITIATE
           INPUT BY INPUT
           INPUT-OUTPUT BY INPUT-OUTPUT
           INSERT BY INSERT
           INSPECT BY INSPECT
           INSTALLATION BY INSTALLATION
           INTO BY INTO
           INVALID BY INVALID
           INVOKE BY INVOKE
           IS BY IS
           JAPANESE BY JAPANESE
           JUST BY JUST
           JUSTIFIED BY JUSTIFIED
           KANJI BY KANJI
           KEPT BY KEPT
           KEY BY KEY
           KEYBOARD BY KEYBOARD
           LABEL BY LABEL
           LAST BY LAST
           LEADING BY LEADING
           LEAVE BY LEAVE
           LEFT BY LEFT
           LEFT-JUSTIFY BY LEFT-JUSTIFY
           LEFTLINE BY LEFTLINE
           LENGTH BY LENGTH
           LENGTH-CHECK BY LENGTH-CHECK
           LESS BY LESS
           LIMIT BY LIMIT
           LIMITS BY LIMITS
           LIN BY LIN
           LINAGE BY LINAGE
           LINAGE-COUNTER BY LINAGE-COUNTER
           LINE BY LINE
           LINE-COUNTER BY LINE-COUNTER
           LINES BY LINES
           LINKAGE BY LINKAGE
           LOCAL-STORAGE BY LOCAL-STORAGE
           LOCK BY LOCK
           LOCKING BY LOCKING
           LOW BY LOW
           LOW-VALUE BY LOW-VALUE
           LOW-VALUES BY LOW-VALUES
           LOWER BY LOWER
           LOWLIGHT BY LOWLIGHT
           MANUAL BY MANUAL
           MASTER-INDEX BY MASTER-INDEX
           MEMORY BY MEMORY
           MERGE BY MERGE
           MESSAGE BY MESSAGE
           METHOD BY METHOD
           MODE BY MODE
           MODULES BY MODULES
           MORE-LABELS BY MORE-LABELS
           MOVE BY MOVE
           MULTIPLE BY MULTIPLE
           MULTIPLY BY MULTIPLY
           NAME BY NAME
           NAMED BY NAMED
           NATIONAL BY NATIONAL
           NATIONAL-EDITED BY NATIONAL-EDITED
           NATIVE BY NATIVE
           NCHAR BY NCHAR
           NEGATIVE BY NEGATIVE
           NEXT BY NEXT
           NO BY NO
           NO-ECHO BY NO-ECHO
           NOMINAL BY NOMINAL
           NOT BY NOT
      *    NOTE BY NOTE
           NSTD-REELS BY NSTD-REELS
           NULL BY NULL
           NULLS BY NULLS
           NUMBER BY NUMBER
           NUMERIC BY NUMERIC
           NUMERIC-EDITED BY NUMERIC-EDITED
           OBJECT BY OBJECT
           OBJECT-COMPUTER BY OBJECT-COMPUTER
           OBJECT-STORAGE BY OBJECT-STORAGE
           OCCURS BY OCCURS
           OF BY OF
           OFF BY OFF
           OMITTED BY OMITTED
           ON BY ON
           OOSTACKPTR BY OOSTACKPTR
           OPEN BY OPEN
           OPTIONAL BY OPTIONAL
           OR BY OR
           ORDER BY ORDER
           ORGANIZATION BY ORGANIZATION
           OTHER BY OTHER
           OTHERWISE BY OTHERWISE
           OUTPUT BY OUTPUT
           OVERFLOW BY OVERFLOW
           OVERLINE BY OVERLINE
           PACKED-DECIMAL BY PACKED-DECIMAL
           PADDING BY PADDING
           PAGE BY PAGE
           PAGE-COUNTER BY PAGE-COUNTER
           PARAGRAPH BY PARAGRAPH
           PASSWORD BY PASSWORD
           PERFORM BY PERFORM
           PF BY PF
           PH BY PH
           PIC BY PIC
           PICTURE BY PICTURE
           PLUS BY PLUS
           POINTER BY POINTER
           POS BY POS
           POSITION BY POSITION
           POSITIONING BY POSITIONING
           POSITIVE BY POSITIVE
           PREVIOUS BY PREVIOUS
           PRINT BY PRINT
           PRINT-SWITCH BY PRINT-SWITCH
           PRINTER BY PRINTER
           PRINTER-1 BY PRINTER-1
           PRINTING BY PRINTING
           PRIVATE BY PRIVATE
           PROCEDURE BY PROCEDURE
           PROCEDURE-POINTER BY PROCEDURE-POINTER
           PROCEDURES BY PROCEDURES
           PROCEED BY PROCEED
           PROCESSING BY PROCESSING
           PROGRAM BY PROGRAM
           PROGRAM-ID BY PROGRAM-ID
           PROMPT BY PROMPT
           PROTECTED BY PROTECTED
           PUBLIC BY PUBLIC
           PURGE BY PURGE
           QUEUE BY QUEUE
           QUOTE BY QUOTE
           QUOTES BY QUOTES
           RANDOM BY RANDOM
           RANGE BY RANGE
           RD BY RD
           READ BY READ
           READY BY READY
           RECEIVE BY RECEIVE
           RECORD BY RECORD
           RECORD-OVERFLOW BY RECORD-OVERFLOW
           RECORDING BY RECORDING
           RECORDS BY RECORDS
           REDEFINES BY REDEFINES
           REEL BY REEL
           REFERENCE BY REFERENCE
           REFERENCES BY REFERENCES
           RELATIVE BY RELATIVE
           RELEASE BY RELEASE
           RELOAD BY RELOAD
           REMAINDER BY REMAINDER
           REMARKS BY REMARKS
           REMOVAL BY REMOVAL
           RENAMES BY RENAMES
           REORG-CRITERIA BY REORG-CRITERIA
      *    REPLACE BY REPLACE
           REPLACING BY REPLACING
           REPORT BY REPORT
           REPORTING BY REPORTING
           REPORTS BY REPORTS
           REQUIRED BY REQUIRED
           REREAD BY REREAD
           RERUN BY RERUN
           RESERVE BY RESERVE
           RESET BY RESET
           RETURN BY RETURN
           RETURN-CODE BY RETURN-CODE
           RETURNING BY RETURNING
           REVERSE BY REVERSE
           REVERSE-VIDEO BY REVERSE-VIDEO
           REVERSED BY REVERSED
           REWIND BY REWIND
           REWRITE BY REWRITE
           RF BY RF
           RH BY RH
           RIGHT BY RIGHT
           RIGHT-JUSTIFY BY RIGHT-JUSTIFY
           ROLLBACK BY ROLLBACK
           ROUNDED BY ROUNDED
           RUN BY RUN
           S01 BY S01
           S02 BY S02
           S03 BY S03
           S04 BY S04
           S05 BY S05
           SAME BY SAME
           SCREEN BY SCREEN
           SD BY SD
           SEARCH BY SEARCH
           SECTION BY SECTION
           SECURE BY SECURE
           SECURITY BY SECURITY
           SEEK BY SEEK
           SEGMENT BY SEGMENT
           SEGMENT-LIMIT BY SEGMENT-LIMIT
           SELECT BY SELECT
           SELECTIVE BY SELECTIVE
           SELF BY SELF
           SEND BY SEND
           SENTENCE BY SENTENCE
           SEPARATE BY SEPARATE
           SEQUENCE BY SEQUENCE
           SEQUENTIAL BY SEQUENTIAL
           SERVICE BY SERVICE
           SET BY SET
           SHIFT-IN BY SHIFT-IN
           SHIFT-OUT BY SHIFT-OUT
           SIGN BY SIGN
           SIZE BY SIZE
           SKIP1 BY SKIP1
           SKIP2 BY SKIP2
           SKIP3 BY SKIP3
           SORT BY SORT
           SORT-CONTROL BY SORT-CONTROL
           SORT-CORE-SIZE BY SORT-CORE-SIZE
           SORT-FILE-SIZE BY SORT-FILE-SIZE
           SORT-MERGE BY SORT-MERGE
           SORT-MESSAGE BY SORT-MESSAGE
           SORT-MODE-SIZE BY SORT-MODE-SIZE
           SORT-OPTION BY SORT-OPTION
           SORT-RETURN BY SORT-RETURN
           SOURCE BY SOURCE
           SOURCE-COMPUTER BY SOURCE-COMPUTER
           SPACE BY SPACE
           SPACE-FILL BY SPACE-FILL
           SPACES BY SPACES
           SPECIAL-NAMES BY SPECIAL-NAMES
           STANDARD BY STANDARD
           STANDARD-1 BY STANDARD-1
           STANDARD-2 BY STANDARD-2
           START BY START
           STATUS BY STATUS
           STOP BY STOP
           STORE BY STORE
           STRING BY STRING
           SUB-QUEUE-1 BY SUB-QUEUE-1
           SUB-QUEUE-2 BY SUB-QUEUE-2
           SUB-QUEUE-3 BY SUB-QUEUE-3
           SUBTRACT BY SUBTRACT
           SUM BY SUM
           SUPER BY SUPER
           SUPPRESS BY SUPPRESS
           SYMBOLIC BY SYMBOLIC
           SYNC BY SYNC
           SYNCHRONIZED BY SYNCHRONIZED
           SYSIN BY SYSIN
           SYSIPT BY SYSIPT
           SYSLST BY SYSLST
           SYSOUT BY SYSOUT
           SYSPCH BY SYSPCH
           SYSPUNCH BY SYSPUNCH
           TAB BY TAB
           TABLE BY TABLE
           TALLY BY TALLY
           TALLYING BY TALLYING
           TAPE BY TAPE
           TERMINAL BY TERMINAL
           TERMINATE BY TERMINATE
           TEST BY TEST
           TEXT BY TEXT
           THAN BY THAN
           THEN BY THEN
           THROUGH BY THROUGH
           THRU BY THRU
           TIME BY TIME
           TIME-OF-DAY BY TIME-OF-DAY
           TIME-OUT BY TIME-OUT
           TIMEOUT BY TIMEOUT
           TIMES BY TIMES
           TITLE BY TITLE
           TO BY TO
           TOP BY TOP
           TOTALED BY TOTALED
           TOTALING BY TOTALING
           TRACE BY TRACE
           TRACK-AREA BY TRACK-AREA
           TRACK-LIMIT BY TRACK-LIMIT
           TRACKS BY TRACKS
           TRAILING BY TRAILING
           TRAILING-SIGN BY TRAILING-SIGN
           TRANSFORM BY TRANSFORM
           TRUE BY TRUE
           TYPE BY TYPE
           TYPEDEF BY TYPEDEF
           UNDERLINE BY UNDERLINE
           UNEQUAL BY UNEQUAL
           UNIT BY UNIT
           UNLOCK BY UNLOCK
           UNSTRING BY UNSTRING
           UNTIL BY UNTIL
           UP BY UP
           UPDATE BY UPDATE
           UPON BY UPON
           UPPER BY UPPER
           UPSI-0 BY UPSI-0
           UPSI-1 BY UPSI-1
           UPSI-2 BY UPSI-2
           UPSI-3 BY UPSI-3
           UPSI-4 BY UPSI-4
           UPSI-5 BY UPSI-5
           UPSI-6 BY UPSI-6
           UPSI-7 BY UPSI-7
           USAGE BY USAGE
           USE BY USE
           USER BY USER
           USING BY USING
           VALUE BY VALUE
           VALUES BY VALUES
           VARIABLE BY VARIABLE
           VARYING BY VARYING
           WAIT BY WAIT
           WHEN BY WHEN
           WHEN-COMPILED BY WHEN-COMPILED
           WITH BY WITH
           WORDS BY WORDS
           WORKING-STORAGE BY WORKING-STORAGE
           WRITE BY WRITE
           WRITE-ONLY BY WRITE-ONLY
           WRITE-VERIFY BY WRITE-VERIFY
           ZERO BY ZERO
           ZERO-FILL BY ZERO-FILL
           ZEROES BY ZEROES
           ZEROS BY ZEROS
           BACKGROUND-COLOUR BY BACKGROUND-COLOUR
           COMP BY COMP
           COMP-0 BY COMP-0
           COMP-1 BY COMP-1
           COMP-2 BY COMP-2
           COMP-3 BY COMP-3
           COMP-4 BY COMP-4
           COMP-5 BY COMP-5
           COMP-6 BY COMP-6
           COMP-X BY COMP-X
           CORR BY CORR
           DE BY DE
           EOP BY EOP
           EXEC BY EXEC
           FOREGROUND-COLOUR BY FOREGROUND-COLOUR
           HIGH-VALUES BY HIGH-VALUES
           ID BY ID
           JUST BY JUST
           LOW-VALUES BY LOW-VALUES
           OTHERWISE BY OTHERWISE
           PIC BY PIC
           QUOTES BY QUOTES
           SPACES BY SPACES
           SYNC BY SYNC
           THRU BY THRU
           TIMEOUT BY TIMEOUT
           UNIT BY UNIT
           ZEROES BY ZEROES

           accept by accept
           access by access
           actual by actual
           add by add
           address by address
           advancing by advancing
           after by after
           all by all
           alphabet by alphabet
           alphabetic by alphabetic
           alphabetic-lower by alphabetic-lower
           alphabetic-upper by alphabetic-upper
           alphanumeric by alphanumeric
           alphanumeric-edited by alphanumeric-edited
           also by also
           alter by alter
           alternate by alternate
           and by and
           any by any
           apply by apply
           are by are
           area by area
           areas by areas
           as by as
           ascending by ascending
           assign by assign
           at by at
           author by author
           auto by auto
           auto-skip by auto-skip
           automatic by automatic
           background-color by background-color
           background-colour by background-colour
           backward by backward
           basis by basis
           beep by beep
           before by before
           beginning by beginning
           bell by bell
           binary by binary
           blank by blank
           blink by blink
           block by block
           bottom by bottom
           by by by
           c01 by c01
           c02 by c02
           c03 by c03
           c04 by c04
           c05 by c05
           c06 by c06
           c07 by c07
           c08 by c08
           c09 by c09
           c10 by c10
           c11 by c11
           c12 by c12
           call by call
           call-convention by call-convention
           cancel by cancel
           cbl by cbl
           cd by cd
           cf by cf
           ch by ch
           chain by chain
           chaining by chaining
           changed by changed
           character by character
           characters by characters
           class by class
           clock-units by clock-units
           close by close
           cobol by cobol
           code by code
           code-set by code-set
           col by col
           collating by collating
           column by column
           com-reg by com-reg
           comma by comma
           commit by commit
           common by common
           communication by communication
           comp by comp
           comp-0 by comp-0
           comp-1 by comp-1
           comp-2 by comp-2
           comp-3 by comp-3
           comp-4 by comp-4
           comp-5 by comp-5
           comp-6 by comp-6
           comp-x by comp-x
           computational by computational
           computational-0 by computational-0
           computational-1 by computational-1
           computational-2 by computational-2
           computational-3 by computational-3
           computational-4 by computational-4
           computational-5 by computational-5
           computational-6 by computational-6
           computational-x by computational-x
           compute by compute
           configuration by configuration
           console by console
           contains by contains
           content by content
           continue by continue
           control by control
           controls by controls
           convert by convert
           converting by converting
           copy by copy
           core-index by core-index
           corr by corr
           corresponding by corresponding
           count by count
           crt by crt
           crt-under by crt-under
           csp by csp
           currency by currency
           current-date by current-date
           cursor by cursor
           cycle by cycle
           cyl-index by cyl-index
           cyl-overflow by cyl-overflow
           data by data
           date by date
           date-compiled by date-compiled
           date-written by date-written
           day by day
           day-of-week by day-of-week
           dbcs by dbcs
           de by de
           debug by debug
           debug-contents by debug-contents
           debug-item by debug-item
           debug-line by debug-line
           debug-name by debug-name
           debug-sub-1 by debug-sub-1
           debug-sub-2 by debug-sub-2
           debug-sub-3 by debug-sub-3
           debugging by debugging
           decimal-point by decimal-point
           declaratives by declaratives
           delete by delete
           delimited by delimited
           delimiter by delimiter
           depending by depending
           descending by descending
           destination by destination
           detail by detail
           disable by disable
           disk by disk
           disp by disp
           display by display
           display-1 by display-1
           display-st by display-st
           divide by divide
           division by division
           down by down
           duplicates by duplicates
           dynamic by dynamic
           echo by echo
           egcs by egcs
           egi by egi
      *    eject by eject
           else by else
           emi by emi
           empty-check by empty-check
           enable by enable
           end by end
           end-accept by end-accept
           end-add by end-add
           end-call by end-call
           end-chain by end-chain
           end-compute by end-compute
           end-delete by end-delete
           end-display by end-display
           end-divide by end-divide
           end-evaluate by end-evaluate
           end-if by end-if
           end-invoke by end-invoke
           end-multiply by end-multiply
           end-of-page by end-of-page
           end-perform by end-perform
           end-read by end-read
           end-receive by end-receive
           end-return by end-return
           end-rewrite by end-rewrite
           end-search by end-search
           end-start by end-start
           end-string by end-string
           end-subtract by end-subtract
           end-unstring by end-unstring
           end-write by end-write
           ending by ending
           enter by enter
           entry by entry
           environment by environment
           eol by eol
           eop by eop
           eos by eos
           equal by equal
           equals by equals
           erase by erase
           error by error
           escape by escape
           esi by esi
           evaluate by evaluate
           every by every
           examine by examine
           exceeds by exceeds
           exception by exception
           excess-3 by excess-3
           exclusive by exclusive
           exec by exec
           execute by execute
           exhibit by exhibit
           exit by exit
           extend by extend
           extended-search by extended-search
           external by external
           factory by factory
           false by false
           fd by fd
           fh-fcd by fh-fcd
           fh-keydef by fh-keydef
           file by file
           file-control by file-control
           file-id by file-id
           file-limit by file-limit
           file-limits by file-limits
           filler by filler
           final by final
           first by first
           fixed by fixed
           footing by footing
           for by for
           foreground-color by foreground-color
           foreground-colour by foreground-colour
           formfeed by formfeed
           from by from
           full by full
           function by function
           generate by generate
           giving by giving
           global by global
           go by go
           goback by goback
           greater by greater
           grid by grid
           group by group
           heading by heading
           high by high
           high-value by high-value
           high-values by high-values
           highlight by highlight
           i-o by i-o
           i-o-control by i-o-control
           id by id
           identification by identification
           if by if
           ignore by ignore
           in by in
           index by index
           indexed by indexed
           indicate by indicate
           inheriting by inheriting
           initial by initial
           initialize by initialize
           initiate by initiate
           input by input
           input-output by input-output
           insert by insert
           inspect by inspect
           installation by installation
           into by into
           invalid by invalid
           invoke by invoke
           is by is
           japanese by japanese
           just by just
           justified by justified
           kanji by kanji
           kept by kept
           key by key
           keyboard by keyboard
           label by label
           last by last
           leading by leading
           leave by leave
           left by left
           left-justify by left-justify
           leftline by leftline
           length by length
           length-check by length-check
           less by less
           limit by limit
           limits by limits
           lin by lin
           linage by linage
           linage-counter by linage-counter
           line by line
           line-counter by line-counter
           lines by lines
           linkage by linkage
           local-storage by local-storage
           lock by lock
           locking by locking
           low by low
           low-value by low-value
           low-values by low-values
           lower by lower
           lowlight by lowlight
           manual by manual
           master-index by master-index
           memory by memory
           merge by merge
           message by message
           method by method
           mode by mode
           modules by modules
           more-labels by more-labels
           move by move
           multiple by multiple
           multiply by multiply
           name by name
           named by named
           national by national
           national-edited by national-edited
           native by native
           nchar by nchar
           negative by negative
           next by next
           no by no
           no-echo by no-echo
           nominal by nominal
           not by not
      *    note by note
           nstd-reels by nstd-reels
           null by null
           nulls by nulls
           number by number
           numeric by numeric
           numeric-edited by numeric-edited
           object by object
           object-computer by object-computer
           object-storage by object-storage
           occurs by occurs
           of by of
           off by off
           omitted by omitted
           on by on
           oostackptr by oostackptr
           open by open
           optional by optional
           or by or
           order by order
           organization by organization
           other by other
           otherwise by otherwise
           output by output
           overflow by overflow
           overline by overline
           packed-decimal by packed-decimal
           padding by padding
           page by page
           page-counter by page-counter
           paragraph by paragraph
           password by password
           perform by perform
           pf by pf
           ph by ph
           pic by pic
           picture by picture
           plus by plus
           pointer by pointer
           pos by pos
           position by position
           positioning by positioning
           positive by positive
           previous by previous
           print by print
           print-switch by print-switch
           printer by printer
           printer-1 by printer-1
           printing by printing
           private by private
           procedure by procedure
           procedure-pointer by procedure-pointer
           procedures by procedures
           proceed by proceed
           processing by processing
           program by program
           program-id by program-id
           prompt by prompt
           protected by protected
           public by public
           purge by purge
           queue by queue
           quote by quote
           quotes by quotes
           random by random
           range by range
           rd by rd
           read by read
           ready by ready
           receive by receive
           record by record
           record-overflow by record-overflow
           recording by recording
           records by records
           redefines by redefines
           reel by reel
           reference by reference
           references by references
           relative by relative
           release by release
           reload by reload
           remainder by remainder
           remarks by remarks
           removal by removal
           renames by renames
           reorg-criteria by reorg-criteria
      *    replace by replace
           replacing by replacing
           report by report
           reporting by reporting
           reports by reports
           required by required
           reread by reread
           rerun by rerun
           reserve by reserve
           reset by reset
           return by return
           return-code by return-code
           returning by returning
           reverse by reverse
           reverse-video by reverse-video
           reversed by reversed
           rewind by rewind
           rewrite by rewrite
           rf by rf
           rh by rh
           right by right
           right-justify by right-justify
           rollback by rollback
           rounded by rounded
           run by run
           s01 by s01
           s02 by s02
           s03 by s03
           s04 by s04
           s05 by s05
           same by same
           screen by screen
           sd by sd
           search by search
           section by section
           secure by secure
           security by security
           seek by seek
           segment by segment
           segment-limit by segment-limit
           select by select
           selective by selective
           self by self
           send by send
           sentence by sentence
           separate by separate
           sequence by sequence
           sequential by sequential
           service by service
           set by set
           shift-in by shift-in
           shift-out by shift-out
           sign by sign
           size by size
           skip1 by skip1
           skip2 by skip2
           skip3 by skip3
           sort by sort
           sort-control by sort-control
           sort-core-size by sort-core-size
           sort-file-size by sort-file-size
           sort-merge by sort-merge
           sort-message by sort-message
           sort-mode-size by sort-mode-size
           sort-option by sort-option
           sort-return by sort-return
           source by source
           source-computer by source-computer
           space by space
           space-fill by space-fill
           spaces by spaces
           special-names by special-names
           standard by standard
           standard-1 by standard-1
           standard-2 by standard-2
           start by start
           status by status
           stop by stop
           store by store
           string by string
           sub-queue-1 by sub-queue-1
           sub-queue-2 by sub-queue-2
           sub-queue-3 by sub-queue-3
           subtract by subtract
           sum by sum
           super by super
           suppress by suppress
           symbolic by symbolic
           sync by sync
           synchronized by synchronized
           sysin by sysin
           sysipt by sysipt
           syslst by syslst
           sysout by sysout
           syspch by syspch
           syspunch by syspunch
           tab by tab
           table by table
           tally by tally
           tallying by tallying
           tape by tape
           terminal by terminal
           terminate by terminate
           test by test
           text by text
           than by than
           then by then
           through by through
           thru by thru
           time by time
           time-of-day by time-of-day
           time-out by time-out
           timeout by timeout
           times by times
           title by title
           to by to
           top by top
           totaled by totaled
           totaling by totaling
           trace by trace
           track-area by track-area
           track-limit by track-limit
           tracks by tracks
           trailing by trailing
           trailing-sign by trailing-sign
           transform by transform
           true by true
           type by type
           typedef by typedef
           underline by underline
           unequal by unequal
           unit by unit
           unlock by unlock
           unstring by unstring
           until by until
           up by up
           update by update
           upon by upon
           upper by upper
           upsi-0 by upsi-0
           upsi-1 by upsi-1
           upsi-2 by upsi-2
           upsi-3 by upsi-3
           upsi-4 by upsi-4
           upsi-5 by upsi-5
           upsi-6 by upsi-6
           upsi-7 by upsi-7
           usage by usage
           use by use
           user by user
           using by using
           value by value
           values by values
           variable by variable
           varying by varying
           wait by wait
           when by when
           when-compiled by when-compiled
           with by with
           words by words
           working-storage by working-storage
           write by write
           write-only by write-only
           write-verify by write-verify
           zero by zero
           zero-fill by zero-fill
           zeroes by zeroes
           zeros by zeros
           background-colour by background-colour
           comp by comp
           comp-0 by comp-0
           comp-1 by comp-1
           comp-2 by comp-2
           comp-3 by comp-3
           comp-4 by comp-4
           comp-5 by comp-5
           comp-6 by comp-6
           comp-x by comp-x
           corr by corr
           de by de
           eop by eop
           exec by exec
           foreground-colour by foreground-colour
           high-values by high-values
           id by id
           just by just
           low-values by low-values
           otherwise by otherwise
           pic by pic
           quotes by quotes
           spaces by spaces
           sync by sync
           thru by thru
           timeout by timeout
           unit by unit
           zeroes by zeroes
           .
         REPLACE OFF.
         REPLACE
           == alpha == by == beta ==
           == 1-2 == by == 3-4 ==
           ==#VAL== by ==VALUE==
           == "abc
      -         "def" == BY == "abc
      -         "def" ==
           == "abc
      -         "def
      -         "ghi" == BY == "abc
      -         "def
      -         "ghi" ==
           == 123
      -          456 == BY == 123
      -          456 ==
           == VOR
      -          NAME == BY == VOR
      -          NAME ==
           == MO
      -      VE == BY == MO
      -      VE ==
      *
           == = == BY == = ==
           == < == BY == < ==
           == > == BY == > ==
           == ( == BY == ( ==
           == ) == BY == ) ==
           == + == BY == + ==
           == <> == BY == <> ==
           == >= == BY == >= ==
           == <= == BY == <= ==
           == 66 == BY == 66 ==
           == 77 == BY == 77 ==
           == 78 == BY == 78 ==
           == 88 == BY == 88 ==
           == - == BY == - ==
           == : == BY == : ==
           == & == BY == & ==
           == ** == BY == ** ==
           == * == BY == * ==
           == / == BY == / ==
           .
         REPLACE OFF.
         COPY in72 REPLACING ==01  KUNBES.
                                                       ==
                        BY ==03  KUNBES.==.
         COPY in72 REPLACING ==01  KUNSTO.==
                        BY ==03  KUNSTO.==.
         COPY in72 REPLACING == 'SYSD0230' == BY
                                  == 'EFFW0257' ==
                                  == VALUE 'D'  == BY
                                  == VALUE 'B'  ==.
         COPY in72 REPLACING =='AA'== BY ==WSS==.

