#define yy_create_buffer ch_highlight__create_buffer
#define yy_delete_buffer ch_highlight__delete_buffer
#define yy_scan_buffer ch_highlight__scan_buffer
#define yy_scan_string ch_highlight__scan_string
#define yy_scan_bytes ch_highlight__scan_bytes
#define yy_flex_debug ch_highlight__flex_debug
#define yy_init_buffer ch_highlight__init_buffer
#define yy_flush_buffer ch_highlight__flush_buffer
#define yy_load_buffer_state ch_highlight__load_buffer_state
#define yy_switch_to_buffer ch_highlight__switch_to_buffer
#define yyin ch_highlight_in
#define yyleng ch_highlight_leng
#define yylex ch_highlight_lex
#define yyout ch_highlight_out
#define yyrestart ch_highlight_restart
#define yytext ch_highlight_text
#define yywrap ch_highlight_wrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 123
#define YY_END_OF_BUFFER 124
static yyconst short int yy_accept[669] =
    {   0,
        0,    0,    0,    0,  124,  122,  121,  120,  122,  122,
      122,  122,  122,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  122,  122,    4,    5,    4,  121,
        0,    1,    0,    1,    0,    2,    8,  119,  119,  119,
      119,  119,  119,  119,   17,  119,  119,  119,  119,  119,
       25,  119,  119,  119,  119,  119,  119,   35,  119,  119,
      119,  119,  119,  119,  119,   47,  119,  119,  119,  119,

      119,   54,   55,  119,  119,  119,  119,   69,   70,   71,
       72,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  112,  119,  114,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,   35,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,   55,  119,  119,  119,  119,   72,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,    0,    0,    0,    7,    3,    0,    6,  119,  119,

       11,   12,  119,  119,  119,  119,   20,  119,  119,  119,
      119,  119,  119,  119,  119,   33,  119,  119,  119,  119,
      119,   41,  119,  119,  119,  119,  119,   49,  119,  119,
      119,  119,  119,  119,  119,   59,   61,  119,   63,  119,
      119,  119,   68,  119,   74,  119,  119,  119,  119,  119,
       81,  119,  119,  119,   86,  119,   88,  119,  119,   93,
      119,  119,   96,  119,  119,  119,  119,  119,  119,  119,
      105,  119,  119,  119,  119,  119,  119,  119,  119,  118,
      119,  119,   12,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,

      119,  119,  119,  119,  119,   49,  119,  119,  119,  119,
      119,  119,  119,  119,   63,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,   88,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      105,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,   22,   23,  119,
       26,  119,   28,  119,  119,  119,   36,  119,  119,   39,
       42,  119,   44,  119,   46,  119,  119,  119,   52,  119,
       56,  119,  119,  119,   62,  119,  119,  119,  119,   73,
       75,  119,  119,  119,   79,  119,   83,  119,  119,  119,

      119,  119,  119,  119,   95,  119,  119,   99,  119,  119,
      102,  103,  119,  119,  107,  108,  109,  110,  119,  119,
      119,  117,  119,  119,  119,  119,  119,  119,  119,  119,
       23,  119,  119,   28,  119,  119,  119,  119,  119,   39,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,   79,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  110,  119,  119,  119,  119,   10,   13,   14,
      119,  119,   18,   19,   24,  119,   27,   29,  119,  119,
       32,   34,  119,  119,  119,   43,  119,   48,  119,  119,

       53,  119,   60,  119,  119,  119,  119,  119,  119,  119,
      119,  119,   82,  119,  119,  119,  119,  119,  119,   94,
      119,  119,  100,  119,  119,  119,  119,  113,  119,  116,
      119,  119,  119,  119,  119,  119,  119,  119,   40,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,    9,   15,  119,   21,  119,
      119,  119,  119,  119,   50,  119,   57,  119,   64,  119,
       66,   67,  119,  119,  119,  119,  119,  119,   87,   89,
       90,   91,   97,   98,  101,  104,  119,  119,  119,  119,

      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,   91,  119,  119,  119,  119,   30,
      119,  119,   38,  119,   51,  119,   65,  119,  119,  119,
       80,   84,  119,   92,  106,  111,  115,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,   31,   37,  119,
       58,   76,   77,   78,  119,  119,  119,  119,  119,  119,
       85,  119,  119,  119,   45,  119,   16,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    7,    1,
        1,    8,    1,    1,    9,    1,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,    1,   12,
        1,   13,    1,    1,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       23,   30,   31,   32,   33,   34,   35,   36,   37,   38,
        1,    1,    1,    1,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   49,   56,   57,   58,   59,   60,   61,   62,
       63,   64,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4
    } ;

static yyconst short int yy_base[675] =
    {   0,
        0,   63,   63,   64,  801,  802,  797,  802,  794,  791,
      788,  788,  782,   54,   60,   62,   59,   64,   79,   84,
        0,   84,  766,  765,   87,   89,   95,  103,  106,  108,
      108,  778,  118,  763,   99,  105,  107,  104,  109,  124,
      129,   65,  736,  735,   88,  131,  137,  142,  144,  150,
      150,  748,  132,  733,  204,  784,  802,  802,  775,  781,
      778,  777,  774,  773,  776,  802,  802,    0,  762,  745,
      751,  758,  744,  742,    0,  741,  751,  743,  172,  750,
        0,  178,  754,  740,  750,  740,  739,  728,  732,  734,
      729,  742,  744,  739,  192,    0,  728,  725,  727,  721,

      738,    0,  190,  197,  734,  715,  196,    0,    0,    0,
      727,  716,  731,  711,  198,  715,  717,  213,  708,  208,
      211,  724,  220,  714,  704,  224,  713,    0,  710,    0,
      707,  714,  703,  704,  691,  674,  680,  687,  673,  671,
      670,  680,  672,  193,  679,  160,  683,  669,  679,  669,
      668,  657,  661,  663,  658,  671,  673,  668,  201,  657,
      654,  656,  650,  667,  203,  199,  663,  644,  200,  656,
      645,  660,  640,  215,  644,  646,  222,  637,  217,  220,
      653,  233,  643,  633,  234,  642,  639,  636,  643,  632,
      633,  279,  686,  685,  684,  802,  682,  802,  666,  665,

        0,  660,  667,  258,  662,  657,    0,  641,  652,  657,
      657,  643,  643,  640,  646,    0,  656,  642,  654,  653,
      648,    0,  649,  261,  646,  631,  648,  646,  642,  631,
      631,  625,  634,  622,  622,    0,    0,  633,  619,  625,
      620,  635,    0,  629,    0,  623,  628,  626,  616,  627,
        0,  622,  624,  238,    0,  618,  611,  605,  604,    0,
      598,  618,    0,  607,  604,  616,  260,  602,  601,  596,
      602,  595,  599,  594,  606,  596,  585,  596,  599,    0,
      575,  574,  569,  576,  239,  571,  566,  550,  561,  566,
      566,  552,  552,  549,  555,  565,  551,  563,  562,  250,

      559,  243,  556,  541,  558,  556,  552,  541,  541,  535,
      544,  532,  532,  543,  529,  535,  530,  545,  539,  533,
      538,  536,  526,  537,  532,  534,  251,  528,  521,  515,
      514,  508,  528,  517,  514,  526,  244,  512,  511,  506,
      512,  505,  509,  504,  516,  506,  495,  506,  509,  524,
      524,  534,  515,  521,  534,  532,  521,    0,  516,  528,
        0,  527,  513,  279,  525,  505,    0,  509,  514,  517,
        0,  506,    0,  508,    0,  504,  513,  504,    0,  501,
        0,  505,  499,  516,    0,  504,  500,  509,  510,    0,
        0,  495,  502,  493,  504,  503,    0,  498,  489,  490,

      485,  491,  485,  496,    0,  499,  487,    0,  479,  488,
        0,    0,  493,  480,    0,    0,    0,  479,  486,  483,
      486,    0,  446,  446,  456,  437,  443,  456,  454,  443,
      438,  450,  449,  435,  259,  447,  427,  431,  436,    0,
      442,  428,  430,  426,  435,  426,  423,  427,  421,  438,
      426,  422,  431,  432,  417,  424,  415,  426,  425,  420,
      411,  412,  407,  413,  407,  418,  421,  409,  401,  410,
      415,  402,  401,  408,  405,  408,  420,    0,    0,    0,
      418,  427,    0,    0,    0,  418,    0,    0,  411,  419,
        0,    0,  423,  422,  424,    0,  410,    0,  424,  426,

        0,  421,    0,  411,  419,  419,  416,  410,  402,  396,
      409,  399,    0,  395,  397,  400,  408,  393,  397,    0,
      398,  404,    0,  405,  388,  402,  385,    0,  390,    0,
      359,  357,  366,  357,  350,  358,  362,  361,    0,  350,
      364,  366,  361,  351,  359,  359,  356,  350,  342,  336,
      349,  339,  335,  337,  340,  348,  333,  337,  338,  344,
      345,  328,  342,  325,  330,    0,    0,  368,    0,  349,
      347,  351,  362,  355,    0,  351,    0,  359,    0,  356,
        0,    0,  355,  354,  339,  339,  351,  346,    0,    0,
        0,  336,    0,    0,    0,    0,  348,  333,  344,  323,

      304,  302,  306,  317,  310,  306,  314,  311,  310,  309,
      294,  294,  306,  301,  291,  303,  288,  299,  312,    0,
      325,  315,    0,  313,    0,  322,    0,  307,  321,  300,
        0,    0,  302,    0,    0,    0,    0,  277,  290,  280,
      278,  282,  251,  265,  243,  245,  282,    0,    0,  257,
        0,    0,    0,    0,  185,  133,  112,  107,  106,   89,
        0,   59,   37,   53,    0,   15,    0,  802,  310,  314,
      318,  320,  323,  327
    } ;

static yyconst short int yy_def[675] =
    {   0,
      668,    1,  669,  669,  668,  668,  668,  668,  670,  671,
      668,  668,  668,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  668,  673,  668,  668,  668,  668,
      670,  668,  671,  668,  674,  668,  668,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,

      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  668,  673,  673,  673,  668,  674,  668,  672,  672,

      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,

      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,

      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,

      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,

      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,  672,  672,  672,
      672,  672,  672,  672,  672,  672,  672,    0,  668,  668,
      668,  668,  668,  668
    } ;

static yyconst short int yy_nxt[867] =
    {   0,
        6,    6,    7,    8,    9,    6,   10,    6,   11,   12,
        6,   13,    6,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   21,   21,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   21,   21,    6,   35,
       36,   37,   38,   39,   40,   41,   21,   42,   21,   21,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   21,   21,   55,   58,   58,  667,   56,   69,
       59,   59,   70,   76,   86,   82,   87,   77,   71,  667,
       72,   78,   83,   73,   74,   75,   88,   79,   91,   84,
       92,   89,   80,  665,   93,   90,   81,   94,   85,   95,

       96,   99,  102,   97,  106,  108,   98,  109,  113,  102,
      103,  100,  666,  101,  107,  110,  117,  165,  111,  665,
      118,  112,  114,  120,  115,  125,  116,  121,  126,  127,
      119,  168,  129,  664,  122,  128,  130,  123,  132,  133,
      135,  169,  124,  136,  141,  150,  146,  151,  142,  137,
      661,  138,  143,  147,  139,  140,   75,  152,  144,  155,
      148,  156,  153,  145,  663,  157,  154,   81,  158,  149,
      159,   96,  162,  108,  160,  109,  172,  161,  189,  190,
      662,  176,  163,  110,  164,  177,  170,  179,  208,  171,
      173,  180,  174,  184,  175,  178,  185,  186,  181,  209,

      187,  182,  661,  128,  130,  192,  183,  225,  211,  193,
      212,  232,  237,  226,  233,  248,  291,  234,  292,  249,
      235,  236,  241,  238,  242,  250,  253,  243,  254,  261,
      264,  255,  256,  267,  262,  288,  265,  268,  257,  263,
      237,  273,  303,  258,  259,  274,  289,  269,  304,  270,
      310,  314,  317,  311,  318,  398,  312,  243,  322,  313,
      236,  326,  323,  327,  332,  334,  255,  328,  324,  333,
      399,  335,  337,  329,  263,  354,  338,  343,  330,  331,
      192,  344,  427,  660,  193,  355,  339,  372,  340,  409,
      373,  410,  428,  440,  460,  442,  489,  441,  373,  469,

      490,  470,  535,  659,  658,  654,  536,  653,  652,  461,
       57,   57,   57,   57,   61,   61,   61,   61,   63,   63,
       63,   63,   68,   68,  195,  651,  195,  197,  197,  197,
      197,  657,  649,  648,  656,  655,  654,  653,  652,  651,
      650,  649,  648,  647,  637,  636,  635,  634,  646,  632,
      631,  645,  644,  643,  627,  642,  625,  641,  623,  640,
      639,  620,  638,  637,  636,  635,  634,  633,  632,  631,
      630,  629,  628,  627,  626,  625,  624,  623,  622,  621,
      620,  619,  618,  617,  616,  596,  595,  594,  593,  615,
      591,  590,  589,  614,  613,  612,  611,  610,  609,  582,

      581,  608,  579,  607,  577,  606,  575,  605,  604,  603,
      602,  601,  569,  600,  567,  566,  599,  598,  597,  596,
      595,  594,  593,  592,  591,  590,  589,  588,  587,  586,
      585,  584,  583,  582,  581,  580,  579,  578,  577,  576,
      575,  574,  539,  573,  572,  571,  570,  569,  568,  567,
      566,  530,  565,  528,  564,  563,  562,  561,  523,  560,
      559,  520,  558,  557,  556,  555,  554,  553,  513,  552,
      551,  550,  549,  548,  547,  546,  545,  544,  503,  543,
      501,  542,  541,  498,  540,  496,  539,  538,  537,  492,
      491,  488,  487,  534,  485,  484,  483,  533,  532,  480,

      479,  478,  531,  530,  529,  528,  527,  526,  525,  524,
      523,  522,  521,  520,  519,  518,  517,  516,  515,  514,
      513,  512,  511,  510,  509,  508,  507,  506,  505,  504,
      503,  502,  501,  500,  499,  498,  497,  496,  495,  494,
      493,  492,  491,  488,  487,  486,  485,  484,  483,  482,
      481,  480,  479,  478,  477,  422,  476,  475,  474,  473,
      417,  416,  415,  472,  471,  412,  411,  408,  468,  467,
      405,  466,  465,  464,  463,  462,  397,  459,  458,  457,
      456,  455,  391,  390,  454,  453,  452,  451,  385,  450,
      449,  448,  381,  447,  379,  446,  445,  444,  375,  443,

      371,  439,  438,  367,  437,  436,  435,  434,  433,  361,
      432,  431,  358,  430,  429,  426,  425,  424,  423,  422,
      421,  420,  419,  418,  417,  416,  415,  414,  413,  412,
      411,  408,  407,  406,  405,  404,  403,  402,  401,  400,
      397,  396,  395,  394,  393,  392,  391,  390,  389,  388,
      387,  386,  385,  384,  383,  382,  381,  380,  379,  378,
      377,  376,  375,  374,  371,  370,  369,  368,  367,  366,
      365,  364,  363,  362,  361,  360,  359,  358,  357,  356,
      353,  352,  351,  350,  198,  668,  194,  194,  280,  349,
      348,  347,  346,  345,  342,  341,  336,  260,  325,  251,

      321,  320,  245,  319,  316,  315,  309,  308,  307,  306,
      305,  302,  301,  222,  300,  299,  298,  297,  296,  216,
      295,  294,  293,  290,  207,  287,  286,  285,  284,  283,
      201,  282,  281,  280,  279,  278,  277,  276,  275,  272,
      271,  266,  260,  252,  251,  247,  246,  245,  244,  240,
      239,  231,  230,  229,  228,  227,  224,  223,  222,  221,
      220,  219,  218,  217,  216,  215,  214,  213,  210,  207,
      206,  205,  204,  203,  202,  201,  200,  199,  198,   63,
       64,   61,   62,   60,  196,  194,  191,  188,  167,  166,
      134,  131,  105,  104,   67,   66,   65,   64,   62,   60,

      668,    5,  668,  668,  668,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  668,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  668,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  668,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  668,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  668,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  668,  668
    } ;

static yyconst short int yy_chk[867] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    3,    4,  666,    2,   14,
        3,    4,   14,   15,   17,   16,   17,   15,   14,  664,
       14,   15,   16,   14,   14,   14,   17,   15,   18,   16,
       18,   17,   15,  663,   18,   17,   15,   18,   16,   18,

       19,   20,   22,   19,   25,   26,   19,   26,   27,   42,
       22,   20,  662,   20,   25,   26,   28,   42,   26,  660,
       28,   26,   27,   29,   27,   30,   27,   29,   30,   30,
       28,   45,   31,  659,   29,   30,   31,   29,   33,   33,
       35,   45,   29,   35,   36,   38,   37,   38,   36,   35,
      658,   35,   36,   37,   35,   35,   35,   38,   36,   39,
       37,   39,   38,   36,  657,   39,   38,   36,   39,   37,
       39,   40,   41,   46,   40,   46,   47,   40,   53,   53,
      656,   48,   41,   46,   41,   48,   46,   49,   79,   46,
       47,   49,   47,   50,   47,   48,   50,   50,   49,   79,

       51,   49,  655,   50,   51,   55,   49,   95,   82,   55,
       82,  103,  104,   95,  103,  115,  146,  103,  146,  115,
      103,  103,  107,  104,  107,  115,  118,  107,  118,  120,
      121,  118,  118,  123,  120,  144,  121,  123,  118,  120,
      166,  126,  159,  118,  118,  126,  144,  123,  159,  123,
      165,  166,  169,  165,  169,  254,  165,  169,  174,  165,
      165,  177,  174,  177,  179,  180,  177,  177,  174,  179,
      254,  180,  182,  177,  179,  204,  182,  185,  177,  177,
      192,  185,  285,  650,  192,  204,  182,  224,  182,  267,
      224,  267,  285,  300,  327,  302,  364,  300,  302,  337,

      364,  337,  435,  647,  646,  645,  435,  644,  643,  327,
      669,  669,  669,  669,  670,  670,  670,  670,  671,  671,
      671,  671,  672,  672,  673,  642,  673,  674,  674,  674,
      674,  641,  640,  639,  638,  633,  630,  629,  628,  626,
      624,  622,  621,  619,  618,  617,  616,  615,  614,  613,
      612,  611,  610,  609,  608,  607,  606,  605,  604,  603,
      602,  601,  600,  599,  598,  597,  592,  588,  587,  586,
      585,  584,  583,  580,  578,  576,  574,  573,  572,  571,
      570,  568,  565,  564,  563,  562,  561,  560,  559,  558,
      557,  556,  555,  554,  553,  552,  551,  550,  549,  548,

      547,  546,  545,  544,  543,  542,  541,  540,  538,  537,
      536,  535,  534,  533,  532,  531,  529,  527,  526,  525,
      524,  522,  521,  519,  518,  517,  516,  515,  514,  512,
      511,  510,  509,  508,  507,  506,  505,  504,  502,  500,
      499,  497,  495,  494,  493,  490,  489,  486,  482,  481,
      477,  476,  475,  474,  473,  472,  471,  470,  469,  468,
      467,  466,  465,  464,  463,  462,  461,  460,  459,  458,
      457,  456,  455,  454,  453,  452,  451,  450,  449,  448,
      447,  446,  445,  444,  443,  442,  441,  439,  438,  437,
      436,  434,  433,  432,  431,  430,  429,  428,  427,  426,

      425,  424,  423,  421,  420,  419,  418,  414,  413,  410,
      409,  407,  406,  404,  403,  402,  401,  400,  399,  398,
      396,  395,  394,  393,  392,  389,  388,  387,  386,  384,
      383,  382,  380,  378,  377,  376,  374,  372,  370,  369,
      368,  366,  365,  363,  362,  360,  359,  357,  356,  355,
      354,  353,  352,  351,  350,  349,  348,  347,  346,  345,
      344,  343,  342,  341,  340,  339,  338,  336,  335,  334,
      333,  332,  331,  330,  329,  328,  326,  325,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,

      301,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  284,  283,  282,  281,  279,
      278,  277,  276,  275,  274,  273,  272,  271,  270,  269,
      268,  266,  265,  264,  262,  261,  259,  258,  257,  256,
      253,  252,  250,  249,  248,  247,  246,  244,  242,  241,
      240,  239,  238,  235,  234,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  223,  221,  220,  219,  218,  217,
      215,  214,  213,  212,  211,  210,  209,  208,  206,  205,
      203,  202,  200,  199,  197,  195,  194,  193,  191,  190,
      189,  188,  187,  186,  184,  183,  181,  178,  176,  175,

      173,  172,  171,  170,  168,  167,  164,  163,  162,  161,
      160,  158,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  148,  147,  145,  143,  142,  141,  140,  139,  138,
      137,  136,  135,  134,  133,  132,  131,  129,  127,  125,
      124,  122,  119,  117,  116,  114,  113,  112,  111,  106,
      105,  101,  100,   99,   98,   97,   94,   93,   92,   91,
       90,   89,   88,   87,   86,   85,   84,   83,   80,   78,
       77,   76,   74,   73,   72,   71,   70,   69,   65,   64,
       63,   62,   61,   60,   59,   56,   54,   52,   44,   43,
       34,   32,   24,   23,   13,   12,   11,   10,    9,    7,

        5,  668,  668,  668,  668,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  668,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  668,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  668,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  668,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  668,  668,  668,  668,  668,  668,
      668,  668,  668,  668,  668,  668
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ch_high.l"
#define INITIAL 0
/*

Copyright (c) 2000, Red Hat, Inc.

This file is part of Source-Navigator.

Source-Navigator is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License as published
by the Free Software Foundation; either version 2, or (at your option)
any later version.

Source-Navigator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License along
with Source-Navigator; see the file COPYING.  If not, write to
the Free Software Foundation, 59 Temple Place - Suite 330, Boston,
MA 02111-1307, USA.



*/
#line 27 "ch_high.l"

  /*
   * ch_high.l
   *
   * Copyright (C) 1998 Cygnus Solutions
   *
   * Description:
   * A GNU flex specification for detecting comments, string literals and
   * keywords in the CCITT High Level Language (CHILL).  Appropriate values
   * are then returned to the `hyper' interpreter for syntax higlighting.
   *
   * Some extensions made by GNU CHILL are observed.  No doubt more will
   * be requested by customers in the future.
   */

#include <ctype.h>
#include "highlight.h"

static long linenumber = 1;
static int  charnumber = 0;
static int lex_buf_size = YY_BUF_SIZE;
static void *user_data1;
static void *user_data2;

extern int tk_text_buffer(char *buf, int maxs, int lexs, void *u_d1, void *u_d2);

#undef yywrap
#define    YY_SKIP_YYWRAP    1
static    int    yywrap();
#define COMMENT 1


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 64 "ch_high.l"



	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 669 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 802 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 66 "ch_high.l"
{
  paf_high_pos.beg_lineno = paf_high_pos.end_lineno = linenumber;
  paf_high_pos.beg_charno = charnumber;
  charnumber += strlen(yytext);
  paf_high_pos.end_charno = charnumber;

  return PAF_HIGH_STRING;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 75 "ch_high.l"
{
  paf_high_pos.beg_lineno = linenumber;
  paf_high_pos.beg_charno = charnumber;
  charnumber += 2;

  BEGIN(COMMENT);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 83 "ch_high.l"
{
  paf_high_pos.end_lineno = linenumber;
  charnumber += 2;
  paf_high_pos.end_charno = charnumber;

  BEGIN(INITIAL);

  return PAF_HIGH_COMMENT;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 93 "ch_high.l"
{ charnumber++; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 95 "ch_high.l"
{ linenumber++; charnumber = 0; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 97 "ch_high.l"
{
  paf_high_pos.beg_lineno = paf_high_pos.end_lineno = linenumber;
  paf_high_pos.beg_charno = charnumber;
	    
  charnumber += yyleng;
  paf_high_pos.end_charno = charnumber - 1;
  
  linenumber++;
  charnumber = 0;

  return PAF_HIGH_COMMENT;
}
	YY_BREAK
case 7:
#line 111 "ch_high.l"
case 8:
#line 112 "ch_high.l"
case 9:
#line 113 "ch_high.l"
case 10:
#line 114 "ch_high.l"
case 11:
#line 115 "ch_high.l"
case 12:
#line 116 "ch_high.l"
case 13:
#line 117 "ch_high.l"
case 14:
#line 118 "ch_high.l"
case 15:
#line 119 "ch_high.l"
case 16:
#line 120 "ch_high.l"
case 17:
#line 121 "ch_high.l"
case 18:
#line 122 "ch_high.l"
case 19:
#line 123 "ch_high.l"
case 20:
#line 124 "ch_high.l"
case 21:
#line 125 "ch_high.l"
case 22:
#line 126 "ch_high.l"
case 23:
#line 127 "ch_high.l"
case 24:
#line 128 "ch_high.l"
case 25:
#line 129 "ch_high.l"
case 26:
#line 130 "ch_high.l"
case 27:
#line 131 "ch_high.l"
case 28:
#line 132 "ch_high.l"
case 29:
#line 133 "ch_high.l"
case 30:
#line 134 "ch_high.l"
case 31:
#line 135 "ch_high.l"
case 32:
#line 136 "ch_high.l"
case 33:
#line 137 "ch_high.l"
case 34:
#line 138 "ch_high.l"
case 35:
#line 139 "ch_high.l"
case 36:
#line 140 "ch_high.l"
case 37:
#line 141 "ch_high.l"
case 38:
#line 142 "ch_high.l"
case 39:
#line 143 "ch_high.l"
case 40:
#line 144 "ch_high.l"
case 41:
#line 145 "ch_high.l"
case 42:
#line 146 "ch_high.l"
case 43:
#line 147 "ch_high.l"
case 44:
#line 148 "ch_high.l"
case 45:
#line 149 "ch_high.l"
case 46:
#line 150 "ch_high.l"
case 47:
#line 151 "ch_high.l"
case 48:
#line 152 "ch_high.l"
case 49:
#line 153 "ch_high.l"
case 50:
#line 154 "ch_high.l"
case 51:
#line 155 "ch_high.l"
case 52:
#line 156 "ch_high.l"
case 53:
#line 157 "ch_high.l"
case 54:
#line 158 "ch_high.l"
case 55:
#line 159 "ch_high.l"
case 56:
#line 160 "ch_high.l"
case 57:
#line 161 "ch_high.l"
case 58:
#line 162 "ch_high.l"
case 59:
#line 163 "ch_high.l"
case 60:
#line 164 "ch_high.l"
case 61:
#line 165 "ch_high.l"
case 62:
#line 166 "ch_high.l"
case 63:
#line 167 "ch_high.l"
case 64:
#line 168 "ch_high.l"
case 65:
#line 169 "ch_high.l"
case 66:
#line 170 "ch_high.l"
case 67:
#line 171 "ch_high.l"
case 68:
#line 172 "ch_high.l"
case 69:
#line 173 "ch_high.l"
case 70:
#line 174 "ch_high.l"
case 71:
#line 175 "ch_high.l"
case 72:
#line 176 "ch_high.l"
case 73:
#line 177 "ch_high.l"
case 74:
#line 178 "ch_high.l"
case 75:
#line 179 "ch_high.l"
case 76:
#line 180 "ch_high.l"
case 77:
#line 181 "ch_high.l"
case 78:
#line 182 "ch_high.l"
case 79:
#line 183 "ch_high.l"
case 80:
#line 184 "ch_high.l"
case 81:
#line 185 "ch_high.l"
case 82:
#line 186 "ch_high.l"
case 83:
#line 187 "ch_high.l"
case 84:
#line 188 "ch_high.l"
case 85:
#line 189 "ch_high.l"
case 86:
#line 190 "ch_high.l"
case 87:
#line 191 "ch_high.l"
case 88:
#line 192 "ch_high.l"
case 89:
#line 193 "ch_high.l"
case 90:
#line 194 "ch_high.l"
case 91:
#line 195 "ch_high.l"
case 92:
#line 196 "ch_high.l"
case 93:
#line 197 "ch_high.l"
case 94:
#line 198 "ch_high.l"
case 95:
#line 199 "ch_high.l"
case 96:
#line 200 "ch_high.l"
case 97:
#line 201 "ch_high.l"
case 98:
#line 202 "ch_high.l"
case 99:
#line 203 "ch_high.l"
case 100:
#line 204 "ch_high.l"
case 101:
#line 205 "ch_high.l"
case 102:
#line 206 "ch_high.l"
case 103:
#line 207 "ch_high.l"
case 104:
#line 208 "ch_high.l"
case 105:
#line 209 "ch_high.l"
case 106:
#line 210 "ch_high.l"
case 107:
#line 211 "ch_high.l"
case 108:
#line 212 "ch_high.l"
case 109:
#line 213 "ch_high.l"
case 110:
#line 214 "ch_high.l"
case 111:
#line 215 "ch_high.l"
case 112:
#line 216 "ch_high.l"
case 113:
#line 217 "ch_high.l"
case 114:
#line 218 "ch_high.l"
case 115:
#line 219 "ch_high.l"
case 116:
#line 220 "ch_high.l"
case 117:
#line 221 "ch_high.l"
case 118:
YY_RULE_SETUP
#line 221 "ch_high.l"
{

  paf_high_pos.beg_lineno = paf_high_pos.end_lineno = linenumber;
  paf_high_pos.beg_charno = charnumber;
  charnumber += yyleng;
  paf_high_pos.end_charno = charnumber;

  return PAF_HIGH_KEYWORD;
}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 231 "ch_high.l"
{
  charnumber += yyleng;
}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 235 "ch_high.l"
{ }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 237 "ch_high.l"
{
  linenumber += yyleng;
  charnumber = 0;
}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 242 "ch_high.l"
{
  /* Eat up everything else. */
  charnumber++;
}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 247 "ch_high.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 669 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 669 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 668);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 247 "ch_high.l"


static    int
yywrap()
{
  linenumber = 1;
  charnumber = 0;
  return 1;
}

static void
flush_lex_scanner()
{
    YY_FLUSH_BUFFER;
}

void
ch_highlight_init_func(int maxs, int lineno, int charno, void *(*func), void *u_d1, void *u_d2)
{
    lex_buf_size = maxs;
    linenumber = lineno;
    charnumber = charno;
    *func = flush_lex_scanner;
    user_data1 = u_d1;
    user_data2 = u_d2;
}

