#define yy_create_buffer tcl_highlight__create_buffer
#define yy_delete_buffer tcl_highlight__delete_buffer
#define yy_scan_buffer tcl_highlight__scan_buffer
#define yy_scan_string tcl_highlight__scan_string
#define yy_scan_bytes tcl_highlight__scan_bytes
#define yy_flex_debug tcl_highlight__flex_debug
#define yy_init_buffer tcl_highlight__init_buffer
#define yy_flush_buffer tcl_highlight__flush_buffer
#define yy_load_buffer_state tcl_highlight__load_buffer_state
#define yy_switch_to_buffer tcl_highlight__switch_to_buffer
#define yyin tcl_highlight_in
#define yyleng tcl_highlight_leng
#define yylex tcl_highlight_lex
#define yyout tcl_highlight_out
#define yyrestart tcl_highlight_restart
#define yytext tcl_highlight_text
#define yywrap tcl_highlight_wrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 99
#define YY_END_OF_BUFFER 100
static yyconst short int yy_accept[728] =
    {   0,
        0,    0,    5,    5,  100,   98,   97,   89,   96,    6,
       95,   95,   95,   94,   91,   98,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   92,   93,   97,    1,    5,
        4,    5,   97,   89,   96,   95,   95,    7,    0,    2,
       94,   90,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   27,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,

       95,   95,   95,   88,   97,    1,    5,    5,    5,    3,
       95,    7,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   32,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,

       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,    8,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   51,   14,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   29,
       95,   95,   37,   95,   59,   31,   95,   95,   95,   95,
       95,   95,   64,   65,   38,   95,   95,   95,   67,   68,
       95,   95,   95,   71,   95,   73,   95,   95,   95,    9,

       95,   95,   95,   95,   95,   95,   95,   95,   95,   78,
       95,   95,   95,   82,   28,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   46,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,    8,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   50,   23,   95,   24,

       95,   25,   95,   11,   55,   95,   95,   95,   95,   95,
       95,   57,   58,   42,   95,   95,   62,   95,   63,   95,
       95,   95,   66,   95,   95,   95,   95,   95,   95,   74,
       95,   95,   95,   95,   95,   76,   95,   95,   77,   95,
       95,   95,   95,   81,   95,   95,   85,   95,   95,   49,
       95,   95,   87,   34,    0,   95,   95,   95,    8,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
        8,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,    8,   95,   95,   95,   95,    8,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,

       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   53,   95,   20,   95,   95,
       95,   95,   30,   95,   95,   95,   40,   95,   95,   95,
       95,   21,   95,   72,   95,   95,   95,   95,   17,   95,
       43,   39,   95,   95,   45,   35,   83,   95,   86,   95,
       95,   95,    0,    8,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   36,   56,   95,   95,

       33,   16,   95,   95,   70,   95,   44,   95,   18,   95,
       95,   95,   95,   95,   48,   95,   12,    0,    0,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   52,   95,   95,   26,   95,   95,
       95,   95,   95,   13,   95,   95,   95,   95,   84,   22,
        0,    0,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   61,   95,   95,   41,   19,   95,   79,   80,    0,
        0,   95,   95,   95,   95,   95,   95,   95,   95,   95,

       95,   95,   95,   15,   60,   10,   69,   95,    0,    0,
       95,   95,   95,   95,   95,   95,   54,   75,    0,    0,
       95,   95,   47,    0,    0,    8,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    8,    1,    9,    1,    9,
        9,    1,    9,    1,    9,    9,    1,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,   10,   11,    1,
        1,    1,    1,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
       12,   13,    1,    1,   14,    1,   15,   16,   17,   18,

       19,   20,   21,   22,   23,    9,   24,   25,   26,   27,
       28,   29,    9,   30,   31,   32,   33,   34,   35,   36,
       37,    9,   38,    1,   39,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[40] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    3,    3,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1
    } ;

static yyconst short int yy_base[732] =
    {   0,
        0,   38,   38,   39,  851,  852,   42,  847,  845,  852,
      816,    0,  837,   48,  852,    0,   26,   34,   43,  827,
       36,   52,   24,   54,   45,  826,  829,  814,   62,   64,
       71,   92,  813,   61,   63,  852,  852,   95,  852,  828,
      852,  110,   89,  837,  835,    0,  816,  119,   96,  852,
      826,  852,  804,  805,  807,  815,  813,  799,  798,  810,
       89,   82,   90,  797,  795,  796,  111,  138,  797,  799,
       88,  808,  794,  143,    0,  140,  804,  804,  804,  132,
      792,  100,  800,  801,  146,  799,  149,  141,   63,  150,
      781,  790,  796,  775,  791,  774,  779,  792,  153,  776,

      775,  789,  780,    0,  174,  852,  789,  180,  186,  852,
      778,  795,  767,  150,  167,  179,  779,  178,  192,  181,
      196,  198,  778,  781,  766,  202,  177,  202,  223,  765,
      221,  176,  774,  777,  773,  753,  774,  756,  770,  769,
      754,  753,  757,  209,  767,  749,  761,  749,  750,  752,
      749,  758,  742,  746,  753,  738,  751,  743,  752,  751,
      748,  737,  745,  738,  743,  743,  727,  728,  736,  738,
      729,  732,  730,  736,  718,  717,  193,  725,  726,  717,
      732,  713,  720,  716,  724,  724,  711,  708,  714,  706,
      710,  721,  710,  717,  718,  713,  716,  707,  697,  705,

      702,  695,  703,  692,  693,  695,  703,  701,  687,  686,
      698,  203,  207,  219,  685,  683,  684,  233,  235,  685,
      687,  229,  696,  682,  234,    0,  164,  692,  692,  692,
      233,  680,  236,  688,  689,  243,  687,  249,  242,  246,
      248,  669,  678,  684,  663,  679,  662,  667,  680,  245,
      664,  663,  677,  668,  660,  652,  656,    0,  663,  658,
      663,  660,  652,  663,  653,  657,  656,  645,  647,  653,
      638,  644,    0,  641,    0,    0,  652,  652,  639,  654,
      649,  652,    0,    0,    0,  636,  651,  639,    0,  647,
      647,  633,  629,    0,  631,  643,  638,  633,  640,    0,

      635,  630,  624,  632,  624,  619,  629,  622,  629,    0,
      628,  627,  624,    0,    0,  619,  622,  621,  607,  604,
      607,  621,  602,  602,  614,  238,  609,  612,  615,  611,
      591,  612,  594,  608,  607,  592,  591,  595,  257,  605,
      587,  599,  587,  588,  590,  587,  596,  580,  584,  591,
      576,  589,  581,  590,  589,  586,  575,  583,  576,  581,
      581,  565,  566,  574,  576,  567,  570,  568,  574,  556,
      555,  261,  563,  564,  555,  570,  551,  558,  554,  562,
      562,  549,  546,  552,  544,  548,  559,  548,  555,  556,
      551,  554,  545,  535,  543,  540,    0,    0,  549,    0,

      536,    0,  546,    0,    0,  534,  539,  532,  533,  529,
      536,    0,    0,    0,  532,  520,    0,  536,    0,  527,
      528,  533,    0,  516,  527,  529,  517,  518,  523,    0,
      515,  510,  524,  523,  523,    0,  519,  510,    0,  511,
      503,  515,  511,    0,  500,  497,    0,  511,  510,    0,
      512,  512,    0,    0,  278,  495,  495,  487,  491,  498,
      493,  498,  495,  487,  498,  488,  492,  491,  480,  482,
      488,  473,  479,  476,  487,  487,  474,  489,  484,  487,
      471,  486,  474,  482,  482,  468,  464,  466,  478,  473,
      468,  475,  470,  465,  459,  467,  459,  454,  464,  457,

      464,  463,  462,  459,  454,  457,  456,  442,  439,  442,
      456,  437,  437,  449,  446,    0,  433,    0,  449,  431,
      431,  425,    0,  440,  441,  437,    0,  426,  432,  424,
      436,    0,  439,    0,  434,  419,  432,  418,    0,  416,
        0,    0,  432,  424,    0,    0,    0,  427,    0,  420,
      419,  418,  423,  279,  426,  413,  423,  411,  416,  409,
      410,  406,  413,  409,  397,  413,  404,  405,  410,  393,
      404,  406,  394,  395,  400,  392,  387,  401,  400,  400,
      396,  387,  388,  380,  392,  388,  377,  374,  388,  387,
      389,  389,  372,  370,  373,  381,    0,    0,  366,  371,

        0,    0,  382,  364,    0,  378,    0,  363,    0,  374,
      360,  376,  362,  364,    0,  369,    0,  362,  280,  365,
      352,  368,  350,  350,  344,  359,  360,  356,  345,  351,
      343,  355,  358,  353,  338,  351,  337,  335,  351,  343,
      346,  339,  338,  337,    0,  329,  342,    0,  329,  326,
      325,  325,  328,    0,  328,  312,   18,   98,    0,    0,
      112,  205,  255,  255,  260,  271,  258,  265,  279,  263,
      280,  268,  281,  269,  287,  275,  279,  286,  278,  270,
      289,    0,  278,  283,    0,    0,  283,    0,    0,  280,
      288,  282,  297,  286,  285,  287,  291,  301,  303,  290,

      293,  297,  298,    0,    0,    0,    0,  299,  308,  309,
      301,  293,  312,  301,  306,  306,    0,    0,  333,  304,
      310,  312,  852,  321,  340,  852,  852,  348,  340,  351,
      354
    } ;

static yyconst short int yy_def[732] =
    {   0,
      727,    1,  728,  728,  727,  727,  727,  727,  727,  727,
      729,  729,  729,  727,  727,  730,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  727,  727,  727,  727,  731,
      727,  731,  727,  727,  727,  729,  729,  727,  727,  727,
      727,  727,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,

      729,  729,  729,  729,  727,  727,  731,  731,  731,  727,
      729,  727,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,

      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,

      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,

      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  727,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,

      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  727,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,

      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  727,  727,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      727,  727,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  729,
      729,  729,  729,  729,  729,  729,  729,  729,  729,  727,
      727,  729,  729,  729,  729,  729,  729,  729,  729,  729,

      729,  729,  729,  729,  729,  729,  729,  729,  727,  727,
      729,  729,  729,  729,  729,  729,  729,  729,  727,  727,
      729,  729,  727,  727,  727,  727,    0,  727,  727,  727,
      727
    } ;

static yyconst short int yy_nxt[892] =
    {   0,
        6,    7,    8,    9,    7,   10,    6,   11,   12,   13,
       14,   15,   16,   12,   17,   18,   19,   20,   21,   22,
       23,   12,   24,   12,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   12,   12,   36,   37,   38,
       41,   41,   38,   43,   39,   53,   43,  688,   73,   49,
       42,   42,   49,   74,   50,   54,   55,   59,   51,   78,
       64,   56,   65,   57,   60,   66,   58,   61,   69,   67,
       62,   68,   79,   75,   70,  100,   83,  183,   87,   71,
       76,   72,   88,  101,  103,   77,   84,   89,  104,   90,
       43,   85,  184,   43,   86,  102,  105,   49,   91,  105,

       49,  106,   50,  141,  156,   92,   93,  143,  144,  145,
       94,  109,  110,   95,  109,   96,  142,  157,  171,   97,
      146,   98,  108,  112,  689,  150,  113,   46,   46,  151,
      690,  172,   46,  114,  115,  116,  117,  118,  119,  120,
       46,  121,   46,  122,  123,  124,  125,  126,  127,  128,
      129,  130,  131,  132,   46,   46,  152,  160,  167,  162,
      153,  163,  168,  169,  175,  161,  179,  181,  176,  204,
      195,  180,  182,  177,  185,  105,  186,  196,  105,  205,
      106,  109,  110,  357,  109,  358,  197,  109,  110,  206,
      109,  238,  108,  210,  207,  239,  208,  254,  108,  209,

      211,  226,  215,  212,  216,  224,  213,  217,  220,  300,
      225,  218,  229,  219,  221,  226,  234,  336,  240,  222,
      241,  223,  227,  691,  301,  230,  235,  228,  266,  242,
      337,  236,  338,  339,  237,  251,  243,  244,  340,  455,
      267,  245,  455,  252,  246,  351,  247,  345,  355,  341,
      248,  346,  249,  347,  366,  253,  356,  348,  352,  362,
      378,  370,  390,  363,  364,  371,  374,  367,  376,  391,
      372,  375,  380,  377,  381,  379,  467,  226,  392,  455,
      619,  619,  455,  619,  619,  226,  692,  693,  468,  226,
      694,  695,  493,  696,  697,  553,  698,  662,  226,  699,

      700,  701,  702,  226,  226,  703,  704,  705,  706,  707,
      708,  709,  710,  711,  712,  713,  226,  714,  715,  226,
      226,  716,  226,  226,  717,  718,  719,  720,  721,  226,
      226,  226,  226,  722,  723,  724,  226,  723,  226,  725,
      723,  726,   46,  687,  726,  686,  685,  726,   40,   40,
       40,   52,  684,   52,  107,  683,  107,  682,  681,  680,
      679,  226,  678,  226,  677,  676,  675,  674,  673,  226,
      672,  226,  671,  226,  670,  669,  226,  226,  668,  667,
      226,  226,  666,  665,  664,  663,  661,  660,  659,  658,
      657,  656,  655,  654,  653,  652,  651,  650,  649,  648,

      647,  646,  645,  644,  643,  642,  226,  641,  226,  226,
      226,  640,  639,  226,  226,  638,  226,  637,  636,  635,
      634,  226,  633,  226,  632,  631,  630,  629,  226,  628,
      627,  626,  226,  625,  624,  623,  622,  226,  621,  226,
      620,  618,  617,  616,  615,  614,  613,  612,  611,  610,
      609,  608,  607,  606,  605,  604,  603,  602,  601,  600,
      599,  598,  597,  596,  595,  594,  593,  226,  226,  592,
      591,  226,  590,  589,  226,  588,  587,  226,  586,  585,
      584,  583,  226,  582,  581,  226,  580,  579,  578,  577,
      576,  226,  575,  574,  573,  572,  571,  570,  226,  569,

      568,  567,  226,  566,  226,  565,  564,  226,  226,  226,
      563,  562,  561,  560,  559,  558,  226,  226,  557,  226,
      556,  226,  555,  226,  226,  554,  552,  551,  550,  549,
      548,  547,  546,  545,  544,  543,  542,  541,  540,  539,
      538,  537,  536,  535,  534,  533,  532,  531,  530,  529,
      528,  527,  526,  525,  524,  523,  522,  521,  520,  519,
      518,  517,  516,  515,  514,  513,  512,  511,  510,  509,
      508,  507,  506,  505,  226,  226,  504,  503,  502,  226,
      501,  500,  499,  498,  497,  496,  495,  494,  492,  491,
      490,  489,  488,  226,  487,  486,  485,  484,  226,  483,

      482,  481,  226,  226,  226,  480,  479,  478,  477,  476,
      475,  226,  226,  474,  226,  473,  472,  471,  470,  469,
      466,  465,  464,  463,  462,  461,  460,  226,  459,  458,
      457,  456,  454,  453,  452,  451,  450,  449,  448,  447,
      446,  445,  444,  443,  442,  441,  440,  439,  438,  437,
      436,  435,  434,  433,  432,  431,  430,  429,  428,  427,
      426,  425,  424,  423,  422,  421,  420,  419,  418,  417,
      416,  415,  414,  413,  412,  411,  410,  409,  408,  407,
      406,  405,  404,  403,  402,  401,  400,  399,  398,  397,
      396,  395,  394,  393,  389,  388,  387,  386,  385,  384,

      383,  382,  373,  369,  368,  365,  361,  360,  359,  354,
      353,  350,  349,  344,  343,  342,  335,  334,  333,  332,
      331,  330,  329,  328,  327,  326,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  316,  315,  314,  313,  312,
      311,  310,  309,  308,  307,  306,  305,  304,  303,  302,
      299,  298,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  277,  276,  275,  274,  273,  272,  271,  270,
      269,  268,  265,  264,  263,  262,  261,  260,  259,  258,
      257,  256,  255,  250,  233,  232,  231,  214,  203,  112,

      202,  108,  201,  200,  199,  198,  194,  193,  192,  191,
      190,  189,  188,  187,  178,  174,  173,  170,  166,  165,
      164,  159,  158,  155,  154,  149,  148,  147,  140,  139,
      138,  137,  136,  135,  134,  133,   51,  111,   45,   44,
      108,   99,   82,   81,   80,   63,   48,   47,   45,   44,
      727,    5,  727,  727,  727,  727,  727,  727,  727,  727,
      727,  727,  727,  727,  727,  727,  727,  727,  727,  727,
      727,  727,  727,  727,  727,  727,  727,  727,  727,  727,
      727,  727,  727,  727,  727,  727,  727,  727,  727,  727,
      727

    } ;

static yyconst short int yy_chk[892] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        3,    4,    2,    7,    2,   17,    7,  657,   23,   14,
        3,    4,   14,   23,   14,   17,   18,   19,   14,   25,
       21,   18,   21,   18,   19,   21,   18,   19,   22,   21,
       19,   21,   25,   24,   22,   34,   29,   89,   30,   22,
       24,   22,   30,   34,   35,   24,   29,   31,   35,   31,
       43,   29,   89,   43,   29,   34,   38,   49,   31,   38,

       49,   38,   49,   61,   71,   31,   32,   62,   62,   63,
       32,   42,   42,   32,   42,   32,   61,   71,   82,   32,
       63,   32,   42,   48,  658,   67,   48,   48,   48,   67,
      661,   82,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   68,   74,   80,   76,
       68,   76,   80,   80,   85,   74,   87,   88,   85,  114,
       99,   87,   88,   85,   90,  105,   90,   99,  105,  114,
      105,  108,  108,  227,  108,  227,   99,  109,  109,  115,
      109,  127,  108,  116,  115,  127,  115,  132,  109,  115,

      116,  132,  118,  116,  118,  120,  116,  118,  119,  177,
      120,  118,  122,  118,  119,  121,  126,  212,  128,  119,
      128,  119,  121,  662,  177,  122,  126,  121,  144,  128,
      212,  126,  213,  213,  126,  131,  128,  129,  214,  326,
      144,  129,  326,  131,  129,  222,  129,  218,  225,  214,
      129,  218,  129,  219,  233,  131,  225,  219,  222,  231,
      240,  236,  250,  231,  231,  236,  238,  233,  239,  250,
      236,  238,  241,  239,  241,  240,  339,  372,  250,  455,
      554,  619,  455,  554,  619,  663,  664,  665,  339,  666,
      667,  668,  372,  669,  670,  455,  671,  619,  672,  673,

      674,  675,  676,  677,  678,  679,  680,  681,  683,  684,
      687,  690,  691,  692,  693,  694,  695,  696,  697,  698,
      699,  700,  701,  702,  703,  708,  709,  710,  711,  712,
      713,  714,  715,  716,  719,  720,  721,  719,  722,  724,
      719,  725,  729,  656,  725,  655,  653,  725,  728,  728,
      728,  730,  652,  730,  731,  651,  731,  650,  649,  647,
      646,  644,  643,  642,  641,  640,  639,  638,  637,  636,
      635,  634,  633,  632,  631,  630,  629,  628,  627,  626,
      625,  624,  623,  622,  621,  620,  618,  616,  614,  613,
      612,  611,  610,  608,  606,  604,  603,  600,  599,  596,

      595,  594,  593,  592,  591,  590,  589,  588,  587,  586,
      585,  584,  583,  582,  581,  580,  579,  578,  577,  576,
      575,  574,  573,  572,  571,  570,  569,  568,  567,  566,
      565,  564,  563,  562,  561,  560,  559,  558,  557,  556,
      555,  553,  552,  551,  550,  548,  544,  543,  540,  538,
      537,  536,  535,  533,  531,  530,  529,  528,  526,  525,
      524,  522,  521,  520,  519,  517,  515,  514,  513,  512,
      511,  510,  509,  508,  507,  506,  505,  504,  503,  502,
      501,  500,  499,  498,  497,  496,  495,  494,  493,  492,
      491,  490,  489,  488,  487,  486,  485,  484,  483,  482,

      481,  480,  479,  478,  477,  476,  475,  474,  473,  472,
      471,  470,  469,  468,  467,  466,  465,  464,  463,  462,
      461,  460,  459,  458,  457,  456,  452,  451,  449,  448,
      446,  445,  443,  442,  441,  440,  438,  437,  435,  434,
      433,  432,  431,  429,  428,  427,  426,  425,  424,  422,
      421,  420,  418,  416,  415,  411,  410,  409,  408,  407,
      406,  403,  401,  399,  396,  395,  394,  393,  392,  391,
      390,  389,  388,  387,  386,  385,  384,  383,  382,  381,
      380,  379,  378,  377,  376,  375,  374,  373,  371,  370,
      369,  368,  367,  366,  365,  364,  363,  362,  361,  360,

      359,  358,  357,  356,  355,  354,  353,  352,  351,  350,
      349,  348,  347,  346,  345,  344,  343,  342,  341,  340,
      338,  337,  336,  335,  334,  333,  332,  331,  330,  329,
      328,  327,  325,  324,  323,  322,  321,  320,  319,  318,
      317,  316,  313,  312,  311,  309,  308,  307,  306,  305,
      304,  303,  302,  301,  299,  298,  297,  296,  295,  293,
      292,  291,  290,  288,  287,  286,  282,  281,  280,  279,
      278,  277,  274,  272,  271,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  257,  256,  255,
      254,  253,  252,  251,  249,  248,  247,  246,  245,  244,

      243,  242,  237,  235,  234,  232,  230,  229,  228,  224,
      223,  221,  220,  217,  216,  215,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  189,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  179,  178,
      176,  175,  174,  173,  172,  171,  170,  169,  168,  167,
      166,  165,  164,  163,  162,  161,  160,  159,  158,  157,
      156,  155,  154,  153,  152,  151,  150,  149,  148,  147,
      146,  145,  143,  142,  141,  140,  139,  138,  137,  136,
      135,  134,  133,  130,  125,  124,  123,  117,  113,  112,

      111,  107,  103,  102,  101,  100,   98,   97,   96,   95,
       94,   93,   92,   91,   86,   84,   83,   81,   79,   78,
       77,   73,   72,   70,   69,   66,   65,   64,   60,   59,
       58,   57,   56,   55,   54,   53,   51,   47,   45,   44,
       40,   33,   28,   27,   26,   20,   13,   11,    9,    8,
        5,  727,  727,  727,  727,  727,  727,  727,  727,  727,
      727,  727,  727,  727,  727,  727,  727,  727,  727,  727,
      727,  727,  727,  727,  727,  727,  727,  727,  727,  727,
      727,  727,  727,  727,  727,  727,  727,  727,  727,  727,
      727

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tcl_high.l"
#define INITIAL 0
/*

Copyright (c) 2000, Red Hat, Inc.

This file is part of Source-Navigator.

Source-Navigator is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License as published
by the Free Software Foundation; either version 2, or (at your option)
any later version.

Source-Navigator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License along
with Source-Navigator; see the file COPYING.  If not, write to
the Free Software Foundation, 59 Temple Place - Suite 330, Boston,
MA 02111-1307, USA.



*/
#line 27 "tcl_high.l"
#include <ctype.h>

#include "highlight.h"

static long braceNest       = 0;
static long lineNumber      = 1;
static int lex_buf_size = 0;
static void *user_data1;
static void *user_data2;

static int    charNumber = 0;
static long comment_caller  = 0;

static    void    drop_until();

#undef yywrap
#define    YY_SKIP_YYWRAP    1
static    int    yywrap();
#define COMMENT 1


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 49 "tcl_high.l"



	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 728 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 852 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
#line 52 "tcl_high.l"
case 2:
YY_RULE_SETUP
#line 52 "tcl_high.l"
{
    char    *p;

    for (p = &yytext[yyleng - 1]; isspace(*p); p++);
    paf_high_pos.beg_lineno = lineNumber;
    paf_high_pos.beg_charno = charNumber + p - yytext;

    charNumber += yyleng;
    BEGIN(COMMENT);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 63 "tcl_high.l"
{
    lineNumber++;
    charNumber = 0;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 68 "tcl_high.l"
{	    /* end of comment */
    lineNumber++;
    charNumber = 0;
    paf_high_pos.end_lineno = lineNumber;
    paf_high_pos.end_charno = charNumber;

    BEGIN(comment_caller);

    return PAF_HIGH_COMMENT;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 79 "tcl_high.l"
{	    /* eat up everything */
    charNumber += yyleng;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 83 "tcl_high.l"
{
    paf_high_pos.beg_lineno = lineNumber;
    paf_high_pos.beg_charno = charNumber;

    charNumber += yyleng;

    drop_until((int)'"',(int)'\\');

    paf_high_pos.end_lineno = lineNumber;
    paf_high_pos.end_charno = charNumber;

    return PAF_HIGH_STRING;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 97 "tcl_high.l"
{
    charNumber += yyleng;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 101 "tcl_high.l"
{
    paf_high_pos.beg_lineno = lineNumber;
    paf_high_pos.beg_charno = charNumber + 2;
    paf_high_pos.end_lineno = lineNumber;
    paf_high_pos.end_charno = charNumber + yyleng;

    charNumber += yyleng;

    return PAF_HIGH_KEYWORD;
}
	YY_BREAK
case 9:
#line 113 "tcl_high.l"
case 10:
#line 114 "tcl_high.l"
case 11:
#line 115 "tcl_high.l"
case 12:
#line 116 "tcl_high.l"
case 13:
#line 117 "tcl_high.l"
case 14:
#line 118 "tcl_high.l"
case 15:
#line 119 "tcl_high.l"
case 16:
#line 120 "tcl_high.l"
case 17:
#line 121 "tcl_high.l"
case 18:
#line 122 "tcl_high.l"
case 19:
#line 123 "tcl_high.l"
case 20:
#line 124 "tcl_high.l"
case 21:
#line 125 "tcl_high.l"
case 22:
#line 126 "tcl_high.l"
case 23:
#line 127 "tcl_high.l"
case 24:
#line 128 "tcl_high.l"
case 25:
#line 129 "tcl_high.l"
case 26:
#line 130 "tcl_high.l"
case 27:
#line 131 "tcl_high.l"
case 28:
#line 132 "tcl_high.l"
case 29:
#line 133 "tcl_high.l"
case 30:
#line 134 "tcl_high.l"
case 31:
#line 135 "tcl_high.l"
case 32:
#line 136 "tcl_high.l"
case 33:
#line 137 "tcl_high.l"
case 34:
#line 138 "tcl_high.l"
case 35:
#line 139 "tcl_high.l"
case 36:
#line 140 "tcl_high.l"
case 37:
#line 141 "tcl_high.l"
case 38:
#line 142 "tcl_high.l"
case 39:
#line 143 "tcl_high.l"
case 40:
#line 144 "tcl_high.l"
case 41:
#line 145 "tcl_high.l"
case 42:
#line 146 "tcl_high.l"
case 43:
#line 147 "tcl_high.l"
case 44:
#line 148 "tcl_high.l"
case 45:
#line 149 "tcl_high.l"
case 46:
#line 150 "tcl_high.l"
case 47:
#line 151 "tcl_high.l"
case 48:
#line 152 "tcl_high.l"
case 49:
#line 153 "tcl_high.l"
case 50:
#line 154 "tcl_high.l"
case 51:
#line 155 "tcl_high.l"
case 52:
#line 156 "tcl_high.l"
case 53:
#line 157 "tcl_high.l"
case 54:
#line 158 "tcl_high.l"
case 55:
#line 159 "tcl_high.l"
case 56:
#line 160 "tcl_high.l"
case 57:
#line 161 "tcl_high.l"
case 58:
#line 162 "tcl_high.l"
case 59:
#line 163 "tcl_high.l"
case 60:
#line 164 "tcl_high.l"
case 61:
#line 165 "tcl_high.l"
case 62:
#line 166 "tcl_high.l"
case 63:
#line 167 "tcl_high.l"
case 64:
#line 168 "tcl_high.l"
case 65:
#line 169 "tcl_high.l"
case 66:
#line 170 "tcl_high.l"
case 67:
#line 171 "tcl_high.l"
case 68:
#line 172 "tcl_high.l"
case 69:
#line 173 "tcl_high.l"
case 70:
#line 174 "tcl_high.l"
case 71:
#line 175 "tcl_high.l"
case 72:
#line 176 "tcl_high.l"
case 73:
#line 177 "tcl_high.l"
case 74:
#line 178 "tcl_high.l"
case 75:
#line 179 "tcl_high.l"
case 76:
#line 180 "tcl_high.l"
case 77:
#line 181 "tcl_high.l"
case 78:
#line 182 "tcl_high.l"
case 79:
#line 183 "tcl_high.l"
case 80:
#line 184 "tcl_high.l"
case 81:
#line 185 "tcl_high.l"
case 82:
#line 186 "tcl_high.l"
case 83:
#line 187 "tcl_high.l"
case 84:
#line 188 "tcl_high.l"
case 85:
#line 189 "tcl_high.l"
case 86:
#line 190 "tcl_high.l"
case 87:
#line 191 "tcl_high.l"
case 88:
YY_RULE_SETUP
#line 191 "tcl_high.l"
{
    paf_high_pos.beg_lineno = lineNumber;
    paf_high_pos.beg_charno = charNumber;
    paf_high_pos.end_lineno = lineNumber;
    paf_high_pos.end_charno = charNumber + yyleng;

    charNumber += yyleng;

    return PAF_HIGH_KEYWORD;
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 202 "tcl_high.l"
{
    lineNumber += yyleng;
    charNumber = 0;
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 207 "tcl_high.l"
{    /* eat up \. characters like \\ \" \{*/
    charNumber += yyleng;
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 211 "tcl_high.l"
{
    charNumber += yyleng;
    /* drop_braces(); */
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 216 "tcl_high.l"
{
    braceNest++;
    charNumber += yyleng;
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 221 "tcl_high.l"
{
    charNumber += yyleng;
    if (--braceNest <= 0)
	braceNest = 0;
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 227 "tcl_high.l"
{
    charNumber += yyleng;
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 231 "tcl_high.l"
{
    charNumber += yyleng;
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 235 "tcl_high.l"
{
	    }
	YY_BREAK
case 97:
#line 239 "tcl_high.l"
case 98:
YY_RULE_SETUP
#line 239 "tcl_high.l"
{
    charNumber += yyleng;
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 242 "tcl_high.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 728 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 728 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 727);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 242 "tcl_high.l"


static    void
drop_until(int term, int esc)
{
    int    c;
    int    l = 0;

    for (l = -1; ((c = (int)input()) != term || l == esc); l = c, charNumber++)
    {
	switch (c)
	{
	case '\\':
	    c = input();
	    if (c <= 0)
	    {
		return;
		break;
	    }
	    if (c != '\n')
	    {
	        charNumber++;
	        c = -1;
	        break;
	    }
	case '\n':
	    lineNumber++;
	    charNumber = -1;
	    break;

	case '\r':
	    charNumber--;
	    break;

	case EOF:
	    return;
	    break;
	}
    }
    if (c == term)
	charNumber++;
}

static    int
yywrap()
{
    braceNest = 0;
    comment_caller = 0;
    return 1;
}

static void
flush_lex_scanner()
{
    YY_FLUSH_BUFFER;
}

void
tcl_highlight_init_func(int maxs, int lineno, int charno, void *(*func), void *u_d1, void *u_d2)
{
    lex_buf_size = maxs;
    lineNumber = lineno;
    charNumber = charno;
    *func = flush_lex_scanner;
    user_data1 = u_d1;
    user_data2 = u_d2;
}

