#define yy_create_buffer verilog_highlight__create_buffer
#define yy_delete_buffer verilog_highlight__delete_buffer
#define yy_scan_buffer verilog_highlight__scan_buffer
#define yy_scan_string verilog_highlight__scan_string
#define yy_scan_bytes verilog_highlight__scan_bytes
#define yy_flex_debug verilog_highlight__flex_debug
#define yy_init_buffer verilog_highlight__init_buffer
#define yy_flush_buffer verilog_highlight__flush_buffer
#define yy_load_buffer_state verilog_highlight__load_buffer_state
#define yy_switch_to_buffer verilog_highlight__switch_to_buffer
#define yyin verilog_highlight_in
#define yyleng verilog_highlight_leng
#define yylex verilog_highlight_lex
#define yyout verilog_highlight_out
#define yyrestart verilog_highlight_restart
#define yytext verilog_highlight_text
#define yywrap verilog_highlight_wrap


/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 122
#define YY_END_OF_BUFFER 123
static yyconst short int yy_accept[481] =
    {   0,
        0,    0,    0,    0,    0,    0,  123,  121,  120,  119,
      121,  121,  121,  121,  118,  118,  121,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,    4,    5,    4,
        7,    8,  120,    0,    1,    0,    0,    0,    0,    0,
        2,    6,  118,  118,    0,    0,    0,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  114,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,   11,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,

      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,    3,    0,    0,    0,    0,    0,    9,  117,
        0,    0,    0,    0,    0,  118,   21,  118,  118,  109,
      118,  118,  118,  118,  118,  118,  118,   10,  118,   71,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,   17,   18,  118,  118,  118,
      118,  118,  118,  118,   50,  118,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,   59,
      118,  118,  118,  118,  118,  118,   69,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  118,  118,  118,  118,

       53,   96,  118,  118,  118,  118,   29,   48,  118,  118,
      118,  118,  118,  118,  118,  118,   82,  118,  118,  118,
      118,  118,  118,   38,  118,  118,  118,  118,  118,   22,
      118,   72,  118,  118,  118,  107,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,  118,   40,   26,   68,   62,  118,  118,  118,  118,
       99,   77,  118,  118,   81,    0,    0,    0,   84,   44,
        0,    0,    0,    0,  118,  118,   30,  118,   76,   54,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
       23,  118,  118,  118,  118,   39,   79,  118,   63,  118,

      118,  118,  118,  118,  118,  118,  118,  118,  118,  113,
      110,  118,  118,   91,  118,  118,   65,  102,   14,  118,
      118,  108,  118,  118,  118,  118,   27,  118,  118,   33,
      118,  118,  101,  100,   98,    0,    0,    0,    0,    0,
       45,   43,    0,    0,  106,   24,   95,   90,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,  118,  118,
      118,   97,   92,  118,  118,  118,  118,  111,   73,  118,
       51,   41,   20,  118,  118,  118,  118,  116,  118,   60,
      118,  118,   55,  118,  118,  118,  118,  118,   34,   58,
      118,    0,    0,   88,   89,    0,    0,    0,  118,   70,

      118,   32,   12,  118,  118,  118,  118,  118,   28,   74,
      118,   93,   35,  118,  118,   31,  118,   64,  118,  118,
       49,  118,  118,   66,  118,   42,   36,   83,   80,   61,
       56,  118,    0,    0,    0,   46,    0,   25,  112,  118,
      118,  118,  118,   13,   67,  118,  118,  118,  118,   94,
       37,   57,  118,   52,   86,   87,    0,    0,  118,  104,
      118,  118,  118,  118,   75,   78,  105,    0,   47,  118,
      118,   19,  115,  118,   85,   15,  118,  103,   16,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    4,    1,    5,    1,    1,    1,    1,
        1,    6,    1,    1,    7,    1,    8,    9,   10,   11,
       11,   11,   11,   11,   11,   11,   11,    1,    1,    1,
        1,    1,    1,    1,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   13,   12,
       12,   14,   12,   12,   12,   12,   12,   15,   12,   12,
        1,    1,    1,    1,   16,   17,   18,   19,   20,   21,

       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   12,   34,   35,   36,   37,   38,   39,   40,
       41,   42,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[43] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    1,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2
    } ;

static yyconst short int yy_base[486] =
    {   0,
        0,    0,   41,   42,  495,  494,  495,  498,  492,  498,
      489,   28,  485,   44,    0,  478,   31,   25,   24,   40,
       33,   44,   34,  464,   45,  457,   51,   56,   59,   50,
       62,   73,   77,   67,  466,   90,  455,  498,  498,  478,
      498,  498,  483,  480,  479,  445,  455,  444,  453,  476,
      498,  498,    0,  463,   69,   88,  450,  436,  453,  438,
      448,  448,  435,  437,  100,  433,  443,  431,  444,  442,
      429,  431,  437,    0,   94,  434,  425,  438,  437,  435,
      434,  423,  429,  420,   95,    0,  415,  416,  417,  413,
      421,  417,  415,  104,  414,  413,  408,  423,  416,  421,

      416,  403,  403,   67,   99,  415,  108,  416,  407,  398,
      397,  396,  498,  399,  397,  393,  396,  423,  498,    0,
      389,  402,  401,  401,  390,  401,    0,  392,  391,  390,
      393,  379,  378,   72,  394,  389,  388,  112,  378,  116,
      388,  382,  370,  368,  367,  381,  371,  377,  382,  365,
      372,  360,  375,  373,  359,    0,  367,  359,  373,  355,
      367,  358,  358,  354,    0,  363,  362,  351,  350,  363,
      351,  348,  349,  357,  344,  342,  345,  345,  341,  131,
      335,  334,  348,  340,  338,  344,    0,  332,  338,  331,
      340,  339,  334,  337,  329,  335,  315,  331,  323,  330,

      110,    0,  317,  314,  332,  330,    0,    0,  330,  310,
      314,  311,  311,  325,  306,  303,    0,  304,  297,  312,
      301,  300,  311,    0,  312,  304,  300,  294,  301,    0,
      308,    0,  305,  290,  296,    0,  304,  298,  145,  288,
      304,  303,  285,  284,  287,  295,  294,  286,   46,  283,
      284,  290,    0,  285,    0,    0,  279,  275,  286,  275,
        0,    0,  147,  284,    0,   98,  270,  285,  280,  498,
      279,  278,  263,  264,  263,  266,    0,  149,    0,    0,
      270,  266,  260,  264,  257,  260,  269,  263,  266,  127,
        0,  265,  260,  151,  267,    0,    0,  262,    0,  250,

      252,  251,  258,  255,  158,  242,  255,  252,  239,    0,
        0,  242,  240,    0,  237,  235,    0,    0,  244,  235,
      247,    0,  244,  248,  241,  223,    0,  240,  241,    0,
      237,  226,    0,    0,    0,  233,  240,  232,  234,  223,
      498,  498,  233,  233,    0,    0,    0,    0,  228,  215,
      232,  227,  226,  227,  209,  215,  224,  214,  214,  207,
      208,    0,    0,  210,  204,  219,  204,    0,    0,  213,
        0,    0,    0,  198,  211,  206,  192,    0,  208,    0,
      206,  206,    0,  186,  192,  160,  162,  164,    0,    0,
      203,  195,  189,  498,  498,  188,  199,  202,  188,    0,

      188,    0,    0,  181,  187,  189,  188,  191,    0,    0,
      181,    0,    0,  177,  189,    0,  187,    0,  170,  176,
        0,  196,  184,    0,  186,    0,    0,    0,    0,    0,
        0,  182,  180,  166,  170,  498,  170,    0,    0,  172,
      175,  160,  172,    0,    0,  176,  156,  158,  169,    0,
        0,    0,  151,    0,  498,  498,  162,  157,  146,    0,
      151,  135,  145,  135,    0,    0,    0,  117,  498,  120,
      105,    0,    0,  102,  498,    0,   40,    0,    0,  498,
      182,  184,  186,   43,  188
    } ;

static yyconst short int yy_def[486] =
    {   0,
      480,    1,  481,  481,  482,  482,  480,  480,  480,  480,
      483,  480,  480,  480,  484,  484,  480,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  480,  480,  480,
      480,  480,  480,  483,  480,  480,  480,  480,  480,  485,
      480,  480,  484,  484,  480,  480,  480,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,

      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  480,  480,  480,  480,  480,  485,  480,  484,
      480,  480,  480,  480,  480,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  484,  484,  484,  484,

      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,

      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  480,  480,  480,  480,  480,  480,  480,  484,  484,

      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  480,  480,  480,  480,  480,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  480,  480,  480,  480,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  480,  480,  484,
      484,  484,  484,  484,  480,  484,  484,  484,  484,    0,
      480,  480,  480,  480,  480
    } ;

static yyconst short int yy_nxt[541] =
    {   0,
        8,    9,   10,   11,   12,    8,   13,   14,    8,    8,
        8,   15,   15,   15,   16,    8,   17,   18,   19,   20,
       21,   22,   23,   15,   24,   25,   26,   15,   27,   28,
       29,   30,   31,   32,   33,   34,   15,   35,   36,   37,
       15,   15,   39,   39,   53,   61,   40,   40,   46,   51,
       47,   52,   55,   58,   65,   59,   56,   63,   66,   60,
       62,  479,   48,   49,   67,   71,   57,   74,   77,   64,
       72,  323,   68,   79,   69,   75,   82,   80,  324,   88,
       83,   70,   78,   86,  104,  177,   87,   81,   84,  204,
       85,   89,   93,   90,   94,   91,   98,  121,   92,  122,

      105,  178,   99,   95,  205,   96,  100,  107,   97,  101,
      123,  108,  102,  103,  109,  110,  179,  133,  124,  143,
      336,  111,  134,  478,  180,  144,  145,  165,  156,  146,
      157,  209,  166,  182,  210,  337,  167,  216,  183,  255,
      256,  211,  477,  217,  212,  358,  213,  214,  257,  279,
      476,  280,  475,  310,  311,  333,  334,  347,  348,  362,
      363,  359,  258,  474,  259,  312,  371,  372,  426,  427,
      428,  429,  430,  431,  473,  472,  471,  470,  469,  468,
      467,  313,   38,   38,   41,   41,   44,   44,  118,  118,
      466,  465,  464,  463,  462,  461,  460,  459,  458,  457,

      456,  455,  454,  453,  452,  451,  450,  449,  448,  447,
      446,  445,  444,  443,  442,  441,  440,  439,  438,  437,
      436,  435,  434,  433,  432,  425,  424,  423,  422,  421,
      420,  419,  418,  417,  416,  415,  414,  413,  412,  411,
      410,  409,  408,  407,  406,  405,  404,  403,  402,  401,
      400,  399,  398,  397,  396,  395,  394,  393,  392,  391,
      390,  389,  388,  387,  386,  385,  384,  383,  382,  381,
      380,  379,  378,  377,  376,  375,  374,  373,  370,  369,
      368,  367,  366,  365,  364,  361,  360,  357,  356,  355,
      354,  353,  352,  351,  350,  349,  346,  345,  344,  343,

      342,  341,  340,  339,  338,  335,  332,  331,  330,  329,
      328,  327,  326,  325,  322,  321,  320,  319,  318,  317,
      316,  315,  314,  309,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  295,  294,  293,
      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  278,  277,  276,  275,  274,  273,  272,  271,
      270,  269,  268,  267,  266,  265,  264,  263,  262,  261,
      260,  254,  253,  252,  251,  250,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,

      225,  224,  223,  222,  221,  220,  219,  218,  215,  208,
      207,  206,  203,  202,  201,  200,  199,  198,  197,  196,
      195,  194,  193,  192,  119,  191,  190,  189,  188,  120,
      187,  186,  185,  184,  181,  176,  175,  174,  173,  172,
      171,  170,  169,  168,  164,  163,  162,  161,  160,  159,
      158,  155,  154,  153,  152,  151,  150,  149,  148,  147,
      142,  141,  140,  139,  138,  137,  136,  135,  132,  131,
      130,  129,  128,  127,  126,  125,  120,  119,  117,  116,
      115,  114,   44,   45,   43,  113,  112,  106,   76,   73,
       54,   50,   45,   43,  480,   42,   42,    7,  480,  480,

      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480
    } ;

static yyconst short int yy_chk[541] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,  484,   19,    3,    4,   12,   14,
       12,   14,   17,   18,   21,   18,   17,   20,   21,   18,
       19,  477,   12,   12,   22,   23,   17,   25,   27,   20,
       23,  249,   22,   28,   22,   25,   29,   28,  249,   31,
       29,   22,   27,   30,   34,  104,   30,   28,   29,  134,
       29,   31,   32,   31,   32,   31,   33,   55,   31,   55,

       34,  104,   33,   32,  134,   32,   33,   36,   32,   33,
       56,   36,   33,   33,   36,   36,  105,   65,   56,   75,
      266,   36,   65,  474,  105,   75,   75,   94,   85,   75,
       85,  138,   94,  107,  138,  266,   94,  140,  107,  180,
      180,  138,  471,  140,  138,  290,  138,  138,  180,  201,
      470,  201,  468,  239,  239,  263,  263,  278,  278,  294,
      294,  290,  180,  464,  180,  239,  305,  305,  386,  386,
      387,  387,  388,  388,  463,  462,  461,  459,  458,  457,
      453,  239,  481,  481,  482,  482,  483,  483,  485,  485,
      449,  448,  447,  446,  443,  442,  441,  440,  437,  435,

      434,  433,  432,  425,  423,  422,  420,  419,  417,  415,
      414,  411,  408,  407,  406,  405,  404,  401,  399,  398,
      397,  396,  393,  392,  391,  385,  384,  382,  381,  379,
      377,  376,  375,  374,  370,  367,  366,  365,  364,  361,
      360,  359,  358,  357,  356,  355,  354,  353,  352,  351,
      350,  349,  344,  343,  340,  339,  338,  337,  336,  332,
      331,  329,  328,  326,  325,  324,  323,  321,  320,  319,
      316,  315,  313,  312,  309,  308,  307,  306,  304,  303,
      302,  301,  300,  298,  295,  293,  292,  289,  288,  287,
      286,  285,  284,  283,  282,  281,  276,  275,  274,  273,

      272,  271,  269,  268,  267,  264,  260,  259,  258,  257,
      254,  252,  251,  250,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  238,  237,  235,  234,  233,  231,  229,
      228,  227,  226,  225,  223,  222,  221,  220,  219,  218,
      216,  215,  214,  213,  212,  211,  210,  209,  206,  205,
      204,  203,  200,  199,  198,  197,  196,  195,  194,  193,
      192,  191,  190,  189,  188,  186,  185,  184,  183,  182,
      181,  179,  178,  177,  176,  175,  174,  173,  172,  171,
      170,  169,  168,  167,  166,  164,  163,  162,  161,  160,
      159,  158,  157,  155,  154,  153,  152,  151,  150,  149,

      148,  147,  146,  145,  144,  143,  142,  141,  139,  137,
      136,  135,  133,  132,  131,  130,  129,  128,  126,  125,
      124,  123,  122,  121,  118,  117,  116,  115,  114,  112,
      111,  110,  109,  108,  106,  103,  102,  101,  100,   99,
       98,   97,   96,   95,   93,   92,   91,   90,   89,   88,
       87,   84,   83,   82,   81,   80,   79,   78,   77,   76,
       73,   72,   71,   70,   69,   68,   67,   66,   64,   63,
       62,   61,   60,   59,   58,   57,   54,   50,   49,   48,
       47,   46,   45,   44,   43,   40,   37,   35,   26,   24,
       16,   13,   11,    9,    7,    6,    5,  480,  480,  480,

      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "verilog_high.l"
#define INITIAL 0
/*

Copyright (c) 2000, Red Hat, Inc.

This file is part of Source-Navigator.

Source-Navigator is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License as published
by the Free Software Foundation; either version 2, or (at your option)
any later version.

Source-Navigator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License along
with Source-Navigator; see the file COPYING.  If not, write to
the Free Software Foundation, 59 Temple Place - Suite 330, Boston,
MA 02111-1307, USA.



*/
#line 27 "verilog_high.l"

  /*
   * verilog_high.l
   *
   * Copyright (C) 1998 Cygnus Solutions
   *
   * Description:
   * A GNU flex specification for detecting comments, string literals and
   * keywords in the CCITT High Level Language (CHILL).  Appropriate values
   * are then returned to the `hyper' interpreter for syntax higlighting.
   *
   * Some extensions made by GNU CHILL are observed.  No doubt more will
   * be requested by customers in the future.
   */

#include <ctype.h>
#include "highlight.h"

static long linenumber = 1;
static int  charnumber = 0;
static int lex_buf_size = YY_BUF_SIZE;
static void *user_data1;
static void *user_data2;

extern int tk_text_buffer(char *buf, int maxs, int lexs, void *u_d1, void *u_d2);

#undef yywrap
#define	YY_SKIP_YYWRAP	1
static	int	yywrap();
/*  string-literal  (\"(\"\"|[^\"])*\")|('(''|[^'])*') */
#define COMMENT 1

#define LCOMMENT 2

#line 697 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 66 "verilog_high.l"


#line 851 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 481 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 498 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 68 "verilog_high.l"
{
  paf_high_pos.beg_lineno = paf_high_pos.end_lineno = linenumber;
  paf_high_pos.beg_charno = charnumber;
  charnumber += strlen(yytext);
  paf_high_pos.end_charno = charnumber;

  return PAF_HIGH_STRING;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 77 "verilog_high.l"
{
  paf_high_pos.beg_lineno = linenumber;
  paf_high_pos.beg_charno = charnumber;
  charnumber += 2;

  BEGIN(COMMENT);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 85 "verilog_high.l"
{
  paf_high_pos.end_lineno = linenumber;
  charnumber += 2;
  paf_high_pos.end_charno = charnumber;

  BEGIN(INITIAL);

  return PAF_HIGH_COMMENT;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 95 "verilog_high.l"
{ charnumber++; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 97 "verilog_high.l"
{ linenumber++; charnumber = 0; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 99 "verilog_high.l"
{
  paf_high_pos.beg_lineno = linenumber;
  paf_high_pos.beg_charno = charnumber;
  charnumber += 2;

  BEGIN(LCOMMENT);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 107 "verilog_high.l"
{ charnumber++; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 109 "verilog_high.l"
{
  paf_high_pos.end_lineno = linenumber;
  paf_high_pos.end_charno = charnumber;
  linenumber++; charnumber = 0;

  BEGIN(INITIAL);

  return PAF_HIGH_COMMENT;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 119 "verilog_high.l"
{
  paf_high_pos.beg_lineno = paf_high_pos.end_lineno = linenumber;
  paf_high_pos.beg_charno = charnumber;
		    
  charnumber += yyleng;
  paf_high_pos.end_charno = charnumber - 1;
  
  linenumber++;
  charnumber = 0;

  return PAF_HIGH_COMMENT;
}
	YY_BREAK
/* ^[ \t]*#[ \t]*[a-z]+ |
     "<>" |  */
case 10:
#line 135 "verilog_high.l"
case 11:
#line 136 "verilog_high.l"
case 12:
#line 137 "verilog_high.l"
case 13:
#line 138 "verilog_high.l"
case 14:
#line 139 "verilog_high.l"
case 15:
#line 140 "verilog_high.l"
case 16:
#line 141 "verilog_high.l"
case 17:
#line 142 "verilog_high.l"
case 18:
#line 143 "verilog_high.l"
case 19:
#line 144 "verilog_high.l"
case 20:
#line 145 "verilog_high.l"
case 21:
#line 146 "verilog_high.l"
case 22:
#line 147 "verilog_high.l"
case 23:
#line 148 "verilog_high.l"
case 24:
#line 149 "verilog_high.l"
case 25:
#line 150 "verilog_high.l"
case 26:
#line 151 "verilog_high.l"
case 27:
#line 152 "verilog_high.l"
case 28:
#line 153 "verilog_high.l"
case 29:
#line 154 "verilog_high.l"
case 30:
#line 155 "verilog_high.l"
case 31:
#line 156 "verilog_high.l"
case 32:
#line 157 "verilog_high.l"
case 33:
#line 158 "verilog_high.l"
case 34:
#line 159 "verilog_high.l"
case 35:
#line 160 "verilog_high.l"
case 36:
#line 161 "verilog_high.l"
case 37:
#line 162 "verilog_high.l"
case 38:
#line 163 "verilog_high.l"
case 39:
#line 164 "verilog_high.l"
case 40:
#line 165 "verilog_high.l"
case 41:
#line 166 "verilog_high.l"
case 42:
#line 167 "verilog_high.l"
case 43:
#line 168 "verilog_high.l"
case 44:
#line 169 "verilog_high.l"
case 45:
#line 170 "verilog_high.l"
case 46:
#line 171 "verilog_high.l"
case 47:
#line 172 "verilog_high.l"
case 48:
#line 173 "verilog_high.l"
case 49:
#line 174 "verilog_high.l"
case 50:
#line 175 "verilog_high.l"
case 51:
#line 176 "verilog_high.l"
case 52:
#line 177 "verilog_high.l"
case 53:
#line 178 "verilog_high.l"
case 54:
#line 179 "verilog_high.l"
case 55:
#line 180 "verilog_high.l"
case 56:
#line 181 "verilog_high.l"
case 57:
#line 182 "verilog_high.l"
case 58:
#line 183 "verilog_high.l"
case 59:
#line 184 "verilog_high.l"
case 60:
#line 185 "verilog_high.l"
case 61:
#line 186 "verilog_high.l"
case 62:
#line 187 "verilog_high.l"
case 63:
#line 188 "verilog_high.l"
case 64:
#line 189 "verilog_high.l"
case 65:
#line 190 "verilog_high.l"
case 66:
#line 191 "verilog_high.l"
case 67:
#line 192 "verilog_high.l"
case 68:
#line 193 "verilog_high.l"
case 69:
#line 194 "verilog_high.l"
case 70:
#line 195 "verilog_high.l"
case 71:
#line 196 "verilog_high.l"
case 72:
#line 197 "verilog_high.l"
case 73:
#line 198 "verilog_high.l"
case 74:
#line 199 "verilog_high.l"
case 75:
#line 200 "verilog_high.l"
case 76:
#line 201 "verilog_high.l"
case 77:
#line 202 "verilog_high.l"
case 78:
#line 203 "verilog_high.l"
case 79:
#line 204 "verilog_high.l"
case 80:
#line 205 "verilog_high.l"
case 81:
#line 206 "verilog_high.l"
case 82:
#line 207 "verilog_high.l"
case 83:
#line 208 "verilog_high.l"
case 84:
#line 209 "verilog_high.l"
case 85:
#line 210 "verilog_high.l"
case 86:
#line 211 "verilog_high.l"
case 87:
#line 212 "verilog_high.l"
case 88:
#line 213 "verilog_high.l"
case 89:
#line 214 "verilog_high.l"
case 90:
#line 215 "verilog_high.l"
case 91:
#line 216 "verilog_high.l"
case 92:
#line 217 "verilog_high.l"
case 93:
#line 218 "verilog_high.l"
case 94:
#line 219 "verilog_high.l"
case 95:
#line 220 "verilog_high.l"
case 96:
#line 221 "verilog_high.l"
case 97:
#line 222 "verilog_high.l"
case 98:
#line 223 "verilog_high.l"
case 99:
#line 224 "verilog_high.l"
case 100:
#line 225 "verilog_high.l"
case 101:
#line 226 "verilog_high.l"
case 102:
#line 227 "verilog_high.l"
case 103:
#line 228 "verilog_high.l"
case 104:
#line 229 "verilog_high.l"
case 105:
#line 230 "verilog_high.l"
case 106:
#line 231 "verilog_high.l"
case 107:
#line 232 "verilog_high.l"
case 108:
#line 233 "verilog_high.l"
case 109:
#line 234 "verilog_high.l"
case 110:
#line 235 "verilog_high.l"
case 111:
#line 236 "verilog_high.l"
case 112:
#line 237 "verilog_high.l"
case 113:
#line 238 "verilog_high.l"
case 114:
#line 239 "verilog_high.l"
case 115:
#line 240 "verilog_high.l"
case 116:
#line 241 "verilog_high.l"
case 117:
YY_RULE_SETUP
#line 241 "verilog_high.l"
{     
  paf_high_pos.beg_lineno = paf_high_pos.end_lineno = linenumber;
  paf_high_pos.beg_charno = charnumber;
  charnumber += yyleng;
  paf_high_pos.end_charno = charnumber;

  return PAF_HIGH_KEYWORD;
}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 250 "verilog_high.l"
{
  charnumber += yyleng;
}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 254 "verilog_high.l"
{ }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 256 "verilog_high.l"
{
  linenumber += yyleng;
  charnumber = 0;
}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 261 "verilog_high.l"
{
  /* Eat up everything else. */
  charnumber++;
}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 266 "verilog_high.l"
ECHO;
	YY_BREAK
#line 1286 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(LCOMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 481 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 481 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 480);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 266 "verilog_high.l"


static	int
yywrap()
{
  linenumber = 1;
  charnumber = 0;
  return 1;
}

static void
flush_lex_scanner()
{
	YY_FLUSH_BUFFER;
}

void
verilog_highlight_init_func(int maxs, int lineno, int charno, void *(*func), void *u_d1, void *u_d2)
{

	lex_buf_size = maxs;
	linenumber = lineno;
	charnumber = charno;
	*func = flush_lex_scanner;
	user_data1 = u_d1;
	user_data2 = u_d2;
}

