      PARAMETER (MLEVL=100,LCTYP=1,LCOPD=512,LOPER=6)
      COMMON /STACK/ CTYP(MLEVL),COPD(MLEVL),COPT(MLEVL)
      COMMON /STACK1/NLEVL,IPOP(MLEVL),IPOS(MLEVL),LOPD(MLEVL)
      CHARACTER*(LCTYP) CTYP
      CHARACTER*(LCOPD) COPD
      CHARACTER*(LOPER) COPT
