/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 57
#define YY_END_OF_BUFFER 58
static yyconst short int yy_accept[587] =
    {   0,
        0,    0,    5,    5,   12,   12,   20,   20,    0,    0,
        0,    0,    0,    0,   58,   45,   44,   45,    5,    6,
        7,   12,   13,   17,   16,   20,   21,   25,   24,   57,
       27,   45,   11,   45,   19,   28,   29,   45,   45,   41,
       34,   45,   35,   45,   30,   45,   31,   41,   41,   41,
       41,   41,   41,   41,   32,   33,   56,   57,   55,   54,
       54,   54,   54,   54,   54,   54,   54,    1,    5,    6,
        7,    8,    7,    9,   12,   13,   14,   20,   21,   22,
        0,   27,    0,    0,   10,   43,   18,   36,    4,    0,
       41,    0,    2,   42,   41,   41,   41,   41,   40,   41,

       41,   54,   54,   54,   54,   54,   54,   54,   54,   14,
       15,    0,    0,   22,   23,    0,    0,    0,    3,    0,
       41,   41,   41,   41,   54,   54,   54,   54,   54,   54,
       54,    0,    0,   41,   41,   41,   41,   54,   54,   54,
       54,   54,   54,   54,   26,   41,   41,   41,   41,   54,
       54,   54,   54,   54,   54,   54,   41,   38,   41,   41,
       54,   54,   54,   54,   54,   54,   54,   41,   39,   39,
       54,   54,   54,   54,   54,   54,   54,   37,   41,   41,
       54,   54,   54,   54,   54,   54,   53,   41,   41,   54,
       54,   54,   54,   54,    0,    0,   41,   41,   54,   54,

       54,   54,   47,    0,    0,   41,   41,   48,   54,   54,
       54,    0,    0,   39,   54,   54,   54,    0,    0,   54,
       54,   54,    0,    0,   54,   54,   54,    0,    0,   54,
        0,   54,    0,    0,   54,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   51,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   52,    0,
        0,    0,    0,    0,    0,    0,   52,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   50,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   49,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       46,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    6,    1,    1,    7,    8,
        9,   10,   11,    1,   12,    1,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,   15,   16,
       17,   18,   19,    1,   20,   21,   22,   23,   24,   25,
       26,   14,   27,   14,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   14,   41,   14,
       42,   43,   44,    1,   45,    1,   46,   47,   48,   49,

       50,   51,   52,   14,   53,   14,   14,   54,   14,   55,
       56,   14,   57,   58,   14,   59,   60,   14,   14,   61,
       14,   14,   62,    1,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[64] =
    {   0,
        1,    2,    1,    2,    3,    1,    4,    1,    1,    5,
        1,    1,    1,    6,    1,    1,    1,    1,    1,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    1,    7,    1,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    1,    1
    } ;

static yyconst short int yy_base[608] =
    {   0,
        0,    1,    2,    3,    4,    5,    8,   11,  880,  879,
       54,    0,  117,    0,  881,  884,  884,  861,  876,  884,
       16,  875,  884,  884,  872,  873,  884,  884,  868,  871,
      884,   18,  868,    0,  865,  884,  884,  854,   11,    0,
      884,  854,  884,  851,  884,  862,  884,  812,  806,  811,
      809,  805,  812,  805,  884,  884,  884,  884,  884,    0,
      831,  821,  829,  826,  823,  823,  834,  884,  850,  884,
       20,  884,   22,  884,  849,  884,  178,  848,  884,  179,
      847,  884,   32,  836,  884,    0,  884,  884,  884,  845,
        0,  831,  884,  884,  797,  790,  788,  795,    0,  785,

      783,    0,  808,  808,  806,  815,  812,  805,  799,  180,
      884,  830,  827,  181,  884,  828,  823,  826,  884,   35,
      780,  780,  772,  765,  788,  801,  801,  792,  789,  795,
      791,   36,   39,  758,  770,  755,  761,  789,  775,  791,
      772,  764,  768,  787,  884,  753,  751,  755,  745,  757,
      774,  771,  776,  777,  765,  775,  739,    0,  744,  743,
      771,  759,  745,  765,  753,  752,  757,  730,  739,  738,
      747,  750,  752,  734,  758,  754,  752,    0,  719,  718,
      753,  727,  747,  742,  747,  764,  763,  711,  710,  742,
      735,  721,  737,  736,  727,  738,  709,  708,  731,  730,

      713,  711,    0,  718,  714,  699,  698,    0,  706,  714,
      705,  720,  707,    0,  702,  706,  708,  708,  711,  705,
      713,  700,  689,  707,  697,  727,  707,  696,  697,  704,
      687,  721,  704,  693,  718,  701,  163,  685,  695,  682,
      682,  684,  682,  687,  689,  681,  679,  683,  671,  684,
      676,  675,  668,  674,  683,  681,  670,  674,  884,  654,
      674,  676,  667,  650,  665,  661,  652,  662,  666,  656,
      664,  654,  654,  661,  639,  663,  637,  657,  645,  675,
      644,  642,  642,  640,  651,   10,  635,  648,  633,  650,
      665,  644,  647,  634,  634,  632,  626,  630,  631,  625,

      622,  654,  620,  624,  622,  627,  626,  628,  162,  627,
      615,  625,  626,  627,  623,  613,  617,  620,  606,  610,
      608,  618,  593,  599,  605,  590,  884,  589,  604,  603,
      595,  609,  603,  592,  594,  594,  601,  587,  594,  593,
      584,  600,  588,  614,  582,  592,  591,  579,  578,  884,
       14,  585,  566,  565,  582,  584,  576,  572,  571,  573,
      572,  576,  563,  562,  573,  594,  593,  564,  563,    5,
      558,  556,  555,  562,  570,  565,  564,  563,  554,  550,
      554,  560,  559,  545,  553,  552,  533,  532,  552,  555,
      552,  537,  536,  526,  549,  537,  531,  530,  533,  536,

      535,  528,  527,  541,  536,  527,  531,  530,  521,  551,
      523,  522,  521,  527,  167,  884,  524,  523,  517,  511,
      526,  541,  540,  507,  507,  519,  508,  512,  511,  508,
      503,  509,  514,  501,  508,  500,  509,  493,  497,  497,
      497,  501,  479,  499,  498,  476,  499,  488,  514,  484,
      481,  478,  168,  494,  493,  467,  475,  475,  487,  476,
      471,  482,  481,  471,  476,  471,  497,  476,  473,  494,
      884,  462,  465,  459,  474,  463,  468,  454,  466,  459,
      456,  456,  459,  450,  447,  460,  477,  435,  444,  173,
      437,  427,  444,  193,  199,  403,  397,  178,  197,  198,

      393,  340,  206,  204,  333,  207,  208,  347,  209,  210,
      327,  200,  201,  331,  214,  215,  325,  212,  216,  355,
      211,  224,  208,  228,  234,  354,  235,  236,  237,  238,
      225,  247,  248,  249,  251,  254,  255,  253,  256,  262,
      264,  266,  269,  265,  272,  273,  274,  276,  278,  279,
      280,  282,  283,  286,  291,  284,  288,  293,  296,  299,
      300,  302,  303,  304,  305,  353,  295,  316,  321,  326,
      290,  308,  329,  330,  332,  333,  339,  341,  334,  335,
      342,  344,  346,  351,  352,  884,  377,  384,  391,  398,
      405,  412,  419,  426,  432,  438,  348,  346,  345,  445,

      452,  459,  466,  472,  477,  341,   46
    } ;

static yyconst short int yy_def[608] =
    {   0,
      587,  587,  588,  588,  589,  589,  590,  590,  591,  591,
      586,   11,  586,   13,  586,  586,  586,  586,  592,  586,
      593,  594,  586,  586,  586,  595,  586,  586,  586,  596,
      586,  586,  586,  597,  586,  586,  586,  586,  586,  598,
      586,  586,  586,  586,  586,  586,  586,  598,  598,  598,
      598,  598,  598,  598,  586,  586,  586,  586,  586,  599,
      599,  599,  599,  599,  599,  599,  599,  586,  592,  586,
      593,  586,  593,  586,  594,  586,  600,  595,  586,  601,
      596,  586,  586,  586,  586,  597,  586,  586,  586,  602,
      598,  586,  586,  586,  598,  598,  598,  598,  598,  598,

      598,  599,  599,  599,  599,  599,  599,  599,  599,  600,
      586,  603,  586,  601,  586,  604,  586,  602,  586,  605,
      598,  598,  598,  598,  599,  599,  599,  599,  599,  599,
      599,  605,  605,  598,  598,  598,  598,  599,  599,  599,
      599,  599,  599,  599,  586,  598,  598,  598,  598,  599,
      599,  599,  599,  599,  599,  599,  598,  598,  598,  598,
      599,  599,  599,  599,  599,  599,  599,  598,  598,  598,
      599,  599,  599,  599,  599,  599,  599,  598,  598,  598,
      599,  599,  599,  599,  599,  599,  599,  598,  598,  599,
      599,  599,  599,  599,  586,  586,  598,  598,  599,  599,

      599,  599,  599,  586,  586,  598,  598,  599,  599,  599,
      599,  586,  586,  598,  599,  599,  599,  586,  586,  599,
      599,  599,  586,  586,  599,  599,  599,  586,  586,  599,
      586,  599,  586,  586,  599,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,

      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,

      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  606,
      586,  586,  606,  606,  606,  586,  586,  586,  606,  606,

      586,  586,  606,  606,  586,  606,  606,  586,  606,  606,
      586,  606,  606,  586,  606,  606,  586,  606,  606,  586,
      606,  606,  607,  606,  606,  607,  607,  607,  606,  606,
      586,  607,  607,  606,  606,  607,  607,  606,  606,  607,
      607,  606,  606,  607,  607,  606,  606,  607,  607,  606,
      606,  607,  607,  606,  606,  607,  607,  606,  606,  607,
      607,  606,  606,  607,  607,  606,  607,  607,  607,  607,
      607,  607,  607,  607,  607,  607,  607,  607,  607,  607,
      607,  607,  607,  607,  607,    0,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,

      586,  586,  586,  586,  586,  586,  586
    } ;

static yyconst short int yy_nxt[948] =
    {   0,
      586,  586,   17,   17,   20,   20,   23,   23,   24,   24,
       27,   21,   21,   27,   28,   18,   18,   28,   72,   83,
       89,   83,   72,   90,   72,   73,  374,   88,   74,  586,
       84,   73,  586,   83,   74,   83,  132,  132,  132,  132,
      586,  145,  586,  375,   84,  292,   25,   25,  293,  292,
       29,  526,  293,   29,   16,   32,   17,   32,   33,   34,
       35,   36,   37,   38,   38,   38,   39,   40,   41,   42,
       43,   16,   44,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   45,   46,   47,   40,   48,

       40,   40,   40,   40,   49,   50,   51,   40,   40,   52,
       40,   53,   40,   40,   54,   55,   56,   57,   57,   58,
       59,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       60,   57,   57,   57,   57,   57,   60,   60,   61,   60,
       60,   62,   63,   64,   60,   60,   60,   60,   65,   60,
       60,   60,   66,   60,   60,   67,   60,   60,   57,   57,
       57,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   57,   57,
      111,  115,  111,  115,  316,  242,  420,  457,  374,  374,
      112,  116,  112,  116,  243,  494,  498,  317,  244,  374,

      498,  498,  498,  498,  498,  421,  421,  498,  495,  498,
      498,  498,  498,  498,  498,  498,  421,  498,  498,  498,
      113,  117,  586,  586,  499,  500,  506,  498,  504,  507,
      527,  498,  512,  513,  503,  509,  510,  498,  531,  531,
      498,  498,  524,  528,  515,  516,  374,  518,  519,  521,
      531,  531,  498,  522,  498,  525,  498,  531,  531,  498,
      534,  535,  533,  421,  529,  531,  532,  531,  531,  498,
      530,  538,  498,  539,  540,  531,  498,  498,  537,  531,
      541,  531,  498,  498,  536,  531,  531,  531,  548,  498,
      544,  531,  545,  531,  498,  549,  498,  542,  531,  498,

      543,  546,  531,  531,  547,  498,  498,  531,  531,  550,
      551,  531,  558,  554,  555,  556,  557,  559,  569,  531,
      552,  560,  553,  562,  531,  561,  563,  566,  566,  531,
      564,  565,  531,  531,  573,  531,  531,  531,  531,  570,
      567,  568,  531,  571,  531,  531,  493,  531,  572,  531,
      102,   91,  574,   86,  531,  531,  498,  531,  523,  520,
      581,  582,  517,  514,  575,  576,  511,  508,  577,  578,
      416,  585,  583,  579,  584,  580,  585,   16,   16,   16,
       16,   16,   16,   16,   19,   19,   19,   19,   19,   19,
       19,   22,   22,   22,   22,   22,   22,   22,   26,   26,

       26,   26,   26,   26,   26,   30,   30,   30,   30,   30,
       30,   30,   69,   69,   69,   69,  505,   69,   69,   71,
       71,   71,   71,   71,   71,   71,   75,   75,  502,   75,
       75,   75,   78,   78,   78,  501,   78,   78,   81,   81,
       81,   81,   81,   81,   81,  110,  110,  498,  110,  110,
      110,  110,  114,  114,  114,  497,  114,  114,  114,  118,
      118,  118,  118,  118,  118,  118,  112,  112,  496,  112,
      112,  112,  116,  116,  116,  492,  116,  116,  133,  491,
      490,  489,  133,  488,  487,  486,  485,  484,  483,  482,
      481,  480,  479,  478,  477,  476,  475,  474,  473,  472,

      471,  470,  469,  468,  467,  466,  465,  464,  463,  462,
      461,  460,  459,  458,  456,  455,  454,  453,  452,  451,
      450,  449,  448,  447,  446,  445,  444,  443,  442,  441,
      440,  439,  438,  437,  436,  435,  434,  433,  432,  431,
      430,  429,  428,  427,  426,  425,  424,  423,  422,  422,
      419,  418,  417,  416,  415,  414,  413,  412,  411,  410,
      409,  408,  407,  406,  405,  404,  403,  402,  401,  400,
      399,  398,  397,  396,  395,  394,  393,  392,  391,  390,
      389,  388,  387,  386,  385,  384,  383,  382,  381,  380,
      379,  378,  377,  376,  373,  372,  371,  370,  367,  369,

      368,  367,  366,  365,  364,  363,  362,  361,  360,  359,
      358,  357,  356,  355,  354,  353,  352,  351,  350,  349,
      348,  347,  346,  345,  344,  343,  342,  341,  340,  339,
      338,  337,  336,  335,  334,  333,  332,  331,  330,  329,
      328,  327,  326,  325,  324,  323,  322,  321,  320,  319,
      318,  315,  314,  313,  312,  311,  310,  309,  308,  307,
      306,  305,  304,  303,  302,  301,  300,  299,  298,  297,
      296,  295,  294,  291,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  279,  278,  277,  276,  275,
      274,  273,  272,  271,  270,  269,  268,  267,  266,  265,

      264,  263,  262,  261,  260,  259,  258,  257,  256,  255,
      254,  253,  252,  251,  250,  249,  248,  247,  246,  245,
      241,  240,  239,  238,  237,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  226,  225,  224,  223,  222,
      221,  220,  219,  218,  217,  216,  215,  214,  214,  213,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  201,  200,  199,  198,  197,  196,  195,  194,  193,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  183,
      182,  181,  180,  179,  178,  177,  176,  175,  174,  173,
      172,  171,  170,  169,  168,  167,  166,  165,  164,  163,

      162,  161,  160,  159,  158,  157,  156,  155,  154,  153,
      152,  151,  150,  149,  148,  147,  146,  144,  143,  142,
      141,  140,  139,  138,  137,  136,  135,  134,  119,   80,
      115,   77,  111,  131,  130,  129,  128,  127,  126,  125,
       99,  124,  123,  122,  121,   99,  120,  119,   90,   82,
       79,   76,   70,  109,  108,  107,  106,  105,  104,  103,
      101,  100,   99,   98,   97,   96,   95,   94,   93,   92,
       88,   87,   85,   82,   80,   79,   77,   76,   70,   68,
      586,   31,   31,   15,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,

      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586
    } ;

static yyconst short int yy_chk[948] =
    {   0,
        0,    0,    1,    2,    3,    4,    5,    6,    5,    6,
        7,    3,    4,    8,    7,    1,    2,    8,   21,   32,
       39,   32,   71,   39,   73,   21,  370,   39,   21,   71,
       32,   73,   71,   83,   73,   83,  120,  132,  120,  132,
      133,  133,  133,  370,   83,  286,    5,    6,  286,  351,
        7,  607,  351,    8,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,

       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       77,   80,  110,  114,  309,  237,  415,  453,  415,  453,
       77,   80,  110,  114,  237,  490,  494,  309,  237,  498,

      499,  500,  495,  512,  513,  415,  453,  504,  490,  503,
      506,  507,  509,  510,  521,  518,  498,  515,  516,  519,
       77,   80,  110,  114,  494,  495,  503,  522,  500,  504,
      523,  524,  509,  510,  499,  506,  507,  525,  527,  528,
      529,  530,  521,  523,  512,  513,  531,  515,  516,  518,
      532,  533,  534,  519,  535,  522,  538,  536,  537,  539,
      529,  530,  528,  531,  524,  540,  527,  541,  544,  542,
      525,  534,  543,  535,  536,  545,  546,  547,  533,  548,
      537,  549,  550,  551,  532,  552,  553,  556,  544,  554,
      540,  557,  541,  571,  555,  545,  558,  538,  567,  559,

      539,  542,  560,  561,  543,  562,  563,  564,  565,  546,
      547,  572,  554,  550,  551,  552,  553,  555,  567,  568,
      548,  556,  549,  558,  569,  557,  559,  562,  563,  570,
      560,  561,  573,  574,  571,  575,  576,  579,  580,  568,
      564,  565,  577,  569,  578,  581,  606,  582,  570,  583,
      599,  598,  572,  597,  584,  585,  566,  526,  520,  517,
      579,  580,  514,  511,  573,  574,  508,  505,  575,  576,
      502,  583,  581,  577,  582,  578,  584,  587,  587,  587,
      587,  587,  587,  587,  588,  588,  588,  588,  588,  588,
      588,  589,  589,  589,  589,  589,  589,  589,  590,  590,

      590,  590,  590,  590,  590,  591,  591,  591,  591,  591,
      591,  591,  592,  592,  592,  592,  501,  592,  592,  593,
      593,  593,  593,  593,  593,  593,  594,  594,  497,  594,
      594,  594,  595,  595,  595,  496,  595,  595,  596,  596,
      596,  596,  596,  596,  596,  600,  600,  493,  600,  600,
      600,  600,  601,  601,  601,  492,  601,  601,  601,  602,
      602,  602,  602,  602,  602,  602,  603,  603,  491,  603,
      603,  603,  604,  604,  604,  489,  604,  604,  605,  488,
      487,  486,  605,  485,  484,  483,  482,  481,  480,  479,
      478,  477,  476,  475,  474,  473,  472,  470,  469,  468,

      467,  466,  465,  464,  463,  462,  461,  460,  459,  458,
      457,  456,  455,  454,  452,  451,  450,  449,  448,  447,
      446,  445,  444,  443,  442,  441,  440,  439,  438,  437,
      436,  435,  434,  433,  432,  431,  430,  429,  428,  427,
      426,  425,  424,  423,  422,  421,  420,  419,  418,  417,
      414,  413,  412,  411,  410,  409,  408,  407,  406,  405,
      404,  403,  402,  401,  400,  399,  398,  397,  396,  395,
      394,  393,  392,  391,  390,  389,  388,  387,  386,  385,
      384,  383,  382,  381,  380,  379,  378,  377,  376,  375,
      374,  373,  372,  371,  369,  368,  367,  366,  365,  364,

      363,  362,  361,  360,  359,  358,  357,  356,  355,  354,
      353,  352,  349,  348,  347,  346,  345,  344,  343,  342,
      341,  340,  339,  338,  337,  336,  335,  334,  333,  332,
      331,  330,  329,  328,  326,  325,  324,  323,  322,  321,
      320,  319,  318,  317,  316,  315,  314,  313,  312,  311,
      310,  308,  307,  306,  305,  304,  303,  302,  301,  300,
      299,  298,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  285,  284,  283,  282,  281,  280,  279,
      278,  277,  276,  275,  274,  273,  272,  271,  270,  269,
      268,  267,  266,  265,  264,  263,  262,  261,  260,  258,

      257,  256,  255,  254,  253,  252,  251,  250,  249,  248,
      247,  246,  245,  244,  243,  242,  241,  240,  239,  238,
      236,  235,  234,  233,  232,  231,  230,  229,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  213,  212,  211,  210,  209,  207,  206,  205,
      204,  202,  201,  200,  199,  198,  197,  196,  195,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  177,  176,  175,  174,  173,
      172,  171,  170,  169,  168,  167,  166,  165,  164,  163,
      162,  161,  160,  159,  157,  156,  155,  154,  153,  152,

      151,  150,  149,  148,  147,  146,  144,  143,  142,  141,
      140,  139,  138,  137,  136,  135,  134,  131,  130,  129,
      128,  127,  126,  125,  124,  123,  122,  121,  118,  117,
      116,  113,  112,  109,  108,  107,  106,  105,  104,  103,
      101,  100,   98,   97,   96,   95,   92,   90,   84,   81,
       78,   75,   69,   67,   66,   65,   64,   63,   62,   61,
       54,   53,   52,   51,   50,   49,   48,   46,   44,   42,
       38,   35,   33,   30,   29,   26,   25,   22,   19,   18,
       15,   10,    9,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,

      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  586,  586,  586,  586,  586
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "phpbrowser.l"
#define INITIAL 0
/*

Copyright (c) 2003, Mo DeJong

This file is part of Source-Navigator.

Source-Navigator is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License as published
by the Free Software Foundation; either version 2, or (at your option)
any later version.

Source-Navigator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License along
with Source-Navigator; see the file COPYING.  If not, write to
the Free Software Foundation, 59 Temple Place - Suite 330, Boston,
MA 02111-1307, USA.



*/
/*
 * phpbrowser.l
 *
 * Copyright (C) 2003 Mo DeJong
 *
 * Description:
 * Lex input file for an php language processor.
 */
#line 36 "phpbrowser.l"

#include <ctype.h>
#include <stdlib.h>
#include <stdio.h>
#include "snptools.h"
#include "lexinput.h"
#include "longstr.h"
#include "srchtbl.h"
#include "tcl.h"

#undef YY_INPUT
#define YY_INPUT(buf,r,ms) (r = sn_encoded_input(buf, ms))

#undef yywrap
#define YY_SKIP_YYWRAP

typedef enum {
    OPEN_PAREN,    /* '(' */
    CLOSE_PAREN,   /* ')' */
    OPEN_BRACE,    /* '{' */
    CLOSE_BRACE,   /* '}' */
    OPEN_BRACKET,  /* '[' */
    CLOSE_BRACKET, /* ']' */
    SEMICOLON,     /* ';' */
    COMMA,         /* ',' */

    VARIABLE,      /* $var */
    ARRAY_VARIABLE, /* $var['one'] */
    ASSIGNMENT_OPERATOR, /* '=' */
    ASSIGNMENT_OPERATORS, /* = -= += and so on */

    SOMEWORD,          /* a sequence of text */
    KEYWORD,       /* a key sequence in this language */
    FUNCTION_KEYWORD, /* The keyword "function" */
    GLOBAL_KEYWORD, /* The keyword "global" */
    INCLUDE_KEYWORD, /* The keyword "include" */

    DOUBLE_QUOTED_STRING, /* "I am a double quoted string" */
    SINGLE_QUOTED_STRING,  /* 'I am a double quoted string' */

    UNKNOWN        /* Some unknown or unimportant text */
} TokenType;

typedef struct Token {
    TokenType type;
    char * strval; /* String value of token, NULL if single character */
    long start_line;
    int start_column;
    long end_line;
    int end_column;
    struct Token* next;
} Token;

/* Uncomment this to see debug output in token parsing stage */
/* #define TOKEN_DEBUG */

#ifdef TOKEN_DEBUG
FILE* tokenout = NULL;
#endif

Token* tokens_head = NULL;
Token* tokens_tail = NULL;
int token_index = 0; /* current offset from original token_head */

static char group[] = "php";

#define MAX_SIZE 512

/* FIXME: Can't pass NULL or "" as current function (core dump) */
static char* current_function = (char *) NULL;
static char* current_function_args = (char *) NULL;

/* line number where highlight starts and ends */
static int  current_function_highlight_line;

/* in "function fog() {}" column of 'f' in "fog" */
static int  current_function_highlight_column_start;

/* in "function fog() {}" column of 'g' in "fog" */
static int  current_function_highlight_column_end;

/* line where "function" appears */
static int  current_function_line_start;

/* line where closing brace of function appears */
static int  current_function_line_end;

/* in "function fog() {}" column of 'f' in "function" */
static int  current_function_column_start;

/* in "function fog() {}" column of '}' in "{}" */
static int  current_function_column_end;

static int  current_function_brace_count;

static int result;

static SearchTable * global_var_table = (SearchTable *) NULL;

/* Stores the contents of a special processing mode over
 * multiple lines/rules.
 */
LongString mode_buff;
long mode_start_line;
int mode_start_column;

#define COMMENT_DUMP 0
#define DQSTRING_DUMP 0
#define SQSTRING_DUMP 0
#define HDSTRING_DUMP 0

static YY_BUFFER_STATE original_buffer;

static char* heredoc_id = (char *) NULL; /* End marker for a heredoc string */

static void matched_pattern(char * pattern, char * text);

static char* modestring();

static void FreeGlobalEntry(SearchEntry *entry);

void FreeToken(Token* tok);
void free_head_token();
void append_token(TokenType type,
                  char* strval,
                  long start_line,
                  int start_column,
                  long end_line,
                  int end_column);

char * TokenTypeToString(Token *tok);

void emit_function_declaration();
void emit_comment();
void emit_dqstring();
void emit_sqstring();
void emit_hdstring();

int yywrap() { return 1; }

#define COMMENT 1

#define DQSTRING 2

#define SQSTRING 3

#define HDSTRING 4

#define PHP 5

#define TOKEN 6


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 213 "phpbrowser.l"



	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 587 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 884 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 215 "phpbrowser.l"
{ /* HTML -> PHP mode */
    matched_pattern("<?", yytext);
    BEGIN(PHP);
    sn_advance_column(2);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 221 "phpbrowser.l"
{ /* PHP -> HTML mode */
    matched_pattern("?>", yytext);
    BEGIN(INITIAL);
    sn_advance_column(2);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 227 "phpbrowser.l"
{ /* A C++ style line comment -> // This function is quite nice. <- */
  char * x = (char *) yytext;
  char * y = x + yyleng - 1;

  matched_pattern("//.*\\n", yytext);

  while (*x != '/') { x++; }
  x++;
  assert(*x == '/');
  x++;
  sn_advance_column(x - yytext);

  assert(*y == '\n');
  *y = '\0';

  sn_insert_comment(
    /* classname */ NULL,
    /* funcname */ NULL,
    sn_current_file(),
    x,
    sn_line(),
    sn_column());

  sn_advance_line();
  sn_reset_column();
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 254 "phpbrowser.l"
{ /* A C style multi-line comment, just like this! */
    matched_pattern("/*", yytext);
    BEGIN(COMMENT);
    sn_advance_column(2);
    LongStringInit(&mode_buff,0);
    mode_start_line = sn_line();
    mode_start_column = sn_column();
}
	YY_BREAK

case 5:
YY_RULE_SETUP
#line 264 "phpbrowser.l"
{
    matched_pattern("[^\\*\\n]*", yytext);

    #if COMMENT_DUMP
    fprintf(stderr, "comment(1) \"%s\", %d\n", yytext, yyleng);
    #endif
    mode_buff.append( &mode_buff,
        yytext, yyleng );
    sn_advance_column(yyleng);
  }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 274 "phpbrowser.l"
{
    matched_pattern("[^\\*\\n]*\\n", yytext);

    #if COMMENT_DUMP
    fprintf(stderr, "comment(2) \"%s\", %d\n", yytext, yyleng);
    #endif

    mode_buff.append( &mode_buff,
        yytext, yyleng );
    sn_advance_line();
    sn_reset_column();
  }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 286 "phpbrowser.l"
{
    matched_pattern("\\*+[^\\*/\\n]*", yytext);

    #if COMMENT_DUMP
    fprintf(stderr, "comment(3) \"%s\", %d\n", yytext, yyleng);
    #endif

    mode_buff.append( &mode_buff,
        yytext, yyleng );
    sn_advance_column(yyleng);
  }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 297 "phpbrowser.l"
{
    matched_pattern("\\*+[^\\*/\\n]*\\n", yytext);

    #if COMMENT_DUMP
    fprintf(stderr, "comment(4) \"%s\", %d\n", yytext, yyleng);
    #endif

    mode_buff.append( &mode_buff,
        yytext, yyleng );
    sn_advance_line();
    sn_reset_column();
  }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 309 "phpbrowser.l"
{
    matched_pattern("\\*+/", yytext);

    /* Include multiple '*' characters in the comment */
    if (yyleng > 2) {
        int to_append = yyleng;
        char *comment = (char *) yytext + yyleng - 1;
        assert(*comment == '/');
        comment--;
        assert(*comment == '*');
        *comment = '0';
        to_append -= 2;
        mode_buff.append( &mode_buff,
            yytext, to_append );
    }

    emit_comment();
    sn_advance_column(yyleng);
    BEGIN(PHP);
  }
	YY_BREAK

case 10:
YY_RULE_SETUP
#line 331 "phpbrowser.l"
{
  matched_pattern("\\\"\\\"", yytext);
  /* FIXME: Can we pass NULL instead of "" after length issues worked out ? */
  append_token(DOUBLE_QUOTED_STRING, "",
          sn_line(),
          sn_column(),
          sn_line(),
          sn_column() + yyleng);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 342 "phpbrowser.l"
{
  matched_pattern("\\\"", yytext);
#if DQSTRING_DUMP
  fprintf(stderr, "dqstring started at (%d.%d)\n", sn_line(), sn_column());
#endif
  LongStringInit(&mode_buff,0);
  mode_start_line = sn_line();
  mode_start_column = sn_column();
  sn_advance_column(yyleng);
  BEGIN(DQSTRING);
}
	YY_BREAK

case 12:
YY_RULE_SETUP
#line 355 "phpbrowser.l"
{
    matched_pattern("[^\\\"\\n\\\\]*", yytext);

    #if DQSTRING_DUMP
    fprintf(stderr, "dqstring(1) \"%s\", %d\n", yytext, yyleng);
    #endif
    mode_buff.append( &mode_buff,
        yytext, yyleng );
    sn_advance_column(yyleng);
  }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 365 "phpbrowser.l"
{
    matched_pattern("[^\\\"\\n\\\\]*\\n", yytext);

    #if DQSTRING_DUMP
    fprintf(stderr, "dqstring(2) \"%s\", %d\n", yytext, yyleng);
    #endif
    mode_buff.append( &mode_buff,
        yytext, yyleng );
    sn_advance_line();
    sn_reset_column();
  }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 376 "phpbrowser.l"
{
    matched_pattern("\\\"+[^\\\"/\\n\\\\]*", yytext);

    #if DQSTRING_DUMP
    fprintf(stderr, "dqstring(3) \"%s\", %d\n", yytext, yyleng);
    #endif

    mode_buff.append( &mode_buff,
        yytext, yyleng );
    sn_advance_column(yyleng);
  }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 387 "phpbrowser.l"
{
    matched_pattern("\\\"+[^\\\"\\n\\\\]*\\n", yytext);

    #if DQSTRING_DUMP
    fprintf(stderr, "dqstring(4) \"%s\", %d\n", yytext, yyleng);
    #endif

    mode_buff.append( &mode_buff,
        yytext, yyleng );
    sn_advance_line();
    sn_reset_column();
  }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 399 "phpbrowser.l"
{
    matched_pattern("\\\\", yytext);

    #if DQSTRING_DUMP
    fprintf(stderr, "dqstring(5) \"%s\", %d\n", yytext, yyleng);
    #endif

    mode_buff.append( &mode_buff,
        yytext, yyleng );
    sn_advance_column(yyleng);
  }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 410 "phpbrowser.l"
{
    matched_pattern("\\\"", yytext);
    sn_advance_column(yyleng);
    emit_dqstring();
    BEGIN(PHP);
  }
	YY_BREAK

case 18:
YY_RULE_SETUP
#line 418 "phpbrowser.l"
{
  matched_pattern("\\\'\\\'", yytext);
  /* FIXME: Can we pass NULL instead of "" after length issues worked out ? */
  append_token(SINGLE_QUOTED_STRING, "",
          sn_line(),
          sn_column(),
          sn_line(),
          sn_column() + yyleng);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 429 "phpbrowser.l"
{
  matched_pattern("\\\'", yytext);
#if SQSTRING_DUMP
  fprintf(stderr, "sqstring started at (%d.%d)\n", sn_line(), sn_column());
#endif
  LongStringInit(&mode_buff,0);
  mode_start_line = sn_line();
  mode_start_column = sn_column();
  sn_advance_column(yyleng);
  BEGIN(SQSTRING);
}
	YY_BREAK

case 20:
YY_RULE_SETUP
#line 442 "phpbrowser.l"
{
    matched_pattern("[^\\\'\\n\\\\]*", yytext);

    #if SQSTRING_DUMP
    fprintf(stderr, "sqstring(1) \"%s\", %d\n", yytext, yyleng);
    #endif
    mode_buff.append( &mode_buff,
        yytext, yyleng );
    sn_advance_column(yyleng);
  }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 452 "phpbrowser.l"
{
    matched_pattern("[^\\\'\\n\\\\]*\\n", yytext);

    #if SQSTRING_DUMP
    fprintf(stderr, "sqstring(2) \"%s\", %d\n", yytext, yyleng);
    #endif

    mode_buff.append( &mode_buff,
        yytext, yyleng );
    sn_advance_line();
    sn_reset_column();
  }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 464 "phpbrowser.l"
{
    matched_pattern("\\\'+[^\\\'/\\n\\\\]*", yytext);

    #if SQSTRING_DUMP
    fprintf(stderr, "sqstring(3) \"%s\", %d\n", yytext, yyleng);
    #endif

    mode_buff.append( &mode_buff,
        yytext, yyleng );
    sn_advance_column(yyleng);
  }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 475 "phpbrowser.l"
{
    matched_pattern("\\\'+[^\\\'\\n\\\\]*\\n", yytext);

    #if SQSTRING_DUMP
    fprintf(stderr, "sqstring(4) \"%s\", %d\n", yytext, yyleng);
    #endif

    mode_buff.append( &mode_buff,
        yytext, yyleng );
    sn_advance_line();
    sn_reset_column();
  }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 487 "phpbrowser.l"
{
    matched_pattern("\\\\", yytext);

    #if SQSTRING_DUMP
    fprintf(stderr, "sqstring(5) \"%s\", %d\n", yytext, yyleng);
    #endif

    mode_buff.append( &mode_buff,
        yytext, yyleng );
    sn_advance_column(yyleng);
  }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 498 "phpbrowser.l"
{
    matched_pattern("\\\'", yytext);
    sn_advance_column(yyleng);
    emit_sqstring();
    BEGIN(PHP);
  }
	YY_BREAK

case 26:
YY_RULE_SETUP
#line 506 "phpbrowser.l"
{
  char *x = yytext;
  char *y;

  matched_pattern("<<<{ws}*{heredoc-id}\\n", yytext);

  mode_start_line = sn_line();
  mode_start_column = sn_column();

  x += 3;
  while(*x == ' ' || *x == '\t') { x++; }
  y = x;
  while(*y != '\n') { y++; }
  *y = 0;

  LongStringInit(&mode_buff,0);
  mode_buff.append( &mode_buff,
          x, -1 );
  mode_buff.append( &mode_buff,
          ";\n", -1 );
  heredoc_id = SN_StrDup(mode_buff.buf);
  mode_buff.free(&mode_buff);

#if HDSTRING_DUMP
  fprintf(stderr, "hdstring started at (%d.%d)\n", sn_line(), sn_column());
  fprintf(stderr, "hdstring id is \"%s\"\n", heredoc_id);
#endif

  LongStringInit(&mode_buff,0);

  sn_advance_line();
  sn_reset_column();

  BEGIN(HDSTRING);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 542 "phpbrowser.l"
{
  matched_pattern(".*\n", yytext);
  #if HDSTRING_DUMP
  fprintf(stderr, "hdstring(1) \"%s\", %d\n", yytext, yyleng);
  #endif

  if (strcmp(yytext, heredoc_id) == 0) {
  #if HDSTRING_DUMP
      fprintf(stderr, "hdstring end matched\n");
  #endif

      sn_advance_column(yyleng-2); /* advance to ; */
      emit_hdstring();
      sn_advance_line();
      sn_reset_column();
      BEGIN(PHP);
  } else {
      if (mode_buff.len != 0) {
          /* Only append newline if more than one line in heredoc */
          mode_buff.append( &mode_buff, "\n", 1 );
      }
      mode_buff.append( &mode_buff, yytext, yyleng-1 );
      sn_advance_line();
      sn_reset_column();
  }
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 569 "phpbrowser.l"
{
  matched_pattern("(", yytext);
  append_token(OPEN_PAREN, NULL,
          sn_line(),
          sn_column(),
          sn_line(),
          sn_column() + yyleng);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 579 "phpbrowser.l"
{
  matched_pattern(")", yytext);
  append_token(CLOSE_PAREN, NULL,
          sn_line(),
          sn_column(),
          sn_line(),
          sn_column() + yyleng);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 589 "phpbrowser.l"
{
  matched_pattern("[", yytext);
  append_token(OPEN_BRACKET, NULL,
          sn_line(),
          sn_column(),
          sn_line(),
          sn_column() + yyleng);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 599 "phpbrowser.l"
{
  matched_pattern("]", yytext);
  append_token(CLOSE_BRACKET, NULL,
          sn_line(),
          sn_column(),
          sn_line(),
          sn_column() + yyleng);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 609 "phpbrowser.l"
{
  matched_pattern("{", yytext);
  append_token(OPEN_BRACE, NULL,
          sn_line(),
          sn_column(),
          sn_line(),
          sn_column() + yyleng);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 619 "phpbrowser.l"
{
  matched_pattern("}", yytext);
  append_token(CLOSE_BRACE, NULL,
          sn_line(),
          sn_column(),
          sn_line(),
          sn_column() + yyleng);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 629 "phpbrowser.l"
{
  matched_pattern("}", yytext);
  append_token(SEMICOLON, NULL,
          sn_line(),
          sn_column(),
          sn_line(),
          sn_column() + yyleng);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 639 "phpbrowser.l"
{
  matched_pattern("=", yytext);
  append_token(ASSIGNMENT_OPERATOR, NULL,
          sn_line(),
          sn_column(),
          sn_line(),
          sn_column() + yyleng);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 649 "phpbrowser.l"
{
  matched_pattern("{assignment-operators}", yytext);
  append_token(ASSIGNMENT_OPERATORS, yytext,
          sn_line(),
          sn_column(),
          sn_line(),
          sn_column() + yyleng);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 659 "phpbrowser.l"
{
  matched_pattern("function", yytext);
  append_token(FUNCTION_KEYWORD, yytext,
          sn_line(),
          sn_column(),
          sn_line(),
          sn_column() + yyleng);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 669 "phpbrowser.l"
{
  matched_pattern("global", yytext);
  append_token(GLOBAL_KEYWORD, yytext,
          sn_line(),
          sn_column(),
          sn_line(),
          sn_column() + yyleng);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 679 "phpbrowser.l"
{
  matched_pattern("{include-keywords}", yytext);
  append_token(INCLUDE_KEYWORD, yytext,
          sn_line(),
          sn_column(),
          sn_line(),
          sn_column() + yyleng);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 689 "phpbrowser.l"
{
  matched_pattern("{keywords}", yytext);
  append_token(KEYWORD, yytext,
          sn_line(),
          sn_column(),
          sn_line(),
          sn_column() + yyleng);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 699 "phpbrowser.l"
{
  matched_pattern("{someword}", yytext);
  append_token(SOMEWORD, yytext,
          sn_line(),
          sn_column(),
          sn_line(),
          sn_column() + yyleng);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 709 "phpbrowser.l"
{
  matched_pattern("\\$", yytext);
  sn_advance_column(yyleng); /* ignore \$ */
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 714 "phpbrowser.l"
{
  matched_pattern("${varname}", yytext);
  sn_advance_column(1);
  append_token(VARIABLE, yytext+1,
          sn_line(),
          sn_column(),
          sn_line(),
          sn_column() + yyleng - 1);
  sn_advance_column(yyleng-1);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 725 "phpbrowser.l"
{
  matched_pattern("\\n", yytext);
  sn_advance_line();
  sn_reset_column();
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 731 "phpbrowser.l"
{
  matched_pattern(".", yytext);
  sn_advance_column(yyleng); /* eat text */
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 738 "phpbrowser.l"
{
  int parens, noargs;
  LongString abuff;

#ifdef TOKEN_DEBUG
  fprintf(tokenout, "function declaration at token %d\n", token_index);
  fprintf(tokenout, "match text was \"%s\"\n", yytext);
#endif
  assert(tokens_head->type == FUNCTION_KEYWORD);

  current_function_line_start = tokens_head->start_line;
  current_function_column_start = tokens_head->start_column;

  free_head_token(); /* FUNCTION_KEYWORD */

  /* FIXME: It would be better to create a state stack and push
     the current state onto that (class, function, namespace) */
  assert(current_function == NULL);
  current_function = SN_StrDup(tokens_head->strval);

  current_function_highlight_line = tokens_head->start_line;
  current_function_highlight_column_start = tokens_head->start_column;
  current_function_highlight_column_end = tokens_head->end_column;

  free_head_token(); /* SOMEWORD */
  free_head_token(); /* OPEN_PAREN */

  /* Save function arguments in current_function_args */  
  parens = 1;
  noargs = 1;
  LongStringInit(&abuff,0);
  while (parens > 0) {
    if (tokens_head->type == OPEN_PAREN) {
      parens++;
    } else if (tokens_head->type == CLOSE_PAREN) {
      parens--;
    } else if (tokens_head->type == VARIABLE) {
        /* We just ignore default values for arguments */
        if (!noargs) {
            abuff.append( &abuff, ",", -1);
        }
        abuff.append( &abuff, tokens_head->strval, -1);
        noargs = 0;
    }

    free_head_token(); /* ... */
  }

  assert(current_function_args == NULL);
  if (!noargs) {
      current_function_args = SN_StrDup(abuff.buf);
  }
  abuff.free(&abuff);

  free_head_token(); /* OPEN_BRACE */

  current_function_brace_count = 1;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 797 "phpbrowser.l"
{
  if (current_function) {
    current_function_brace_count++;
  }
  free_head_token(); /* OPEN_BRACE */
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 804 "phpbrowser.l"
{
  if (current_function && (--current_function_brace_count == 0)) {
#ifdef TOKEN_DEBUG
    fprintf(tokenout, "end of function %s at token %d\n",
        current_function, token_index);
#endif

    current_function_line_end = tokens_head->end_line;
    current_function_column_end = tokens_head->end_column;

    emit_function_declaration();
  }

  free_head_token(); /* CLOSE_BRACE */
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 820 "phpbrowser.l"
{
  int line_start, line_end, column_start, column_end;
  char * filename;

#ifdef TOKEN_DEBUG
  fprintf(tokenout, "include statement begins at token %d\n", token_index);
#endif

  free_head_token(); /* INCLUDE_KEYWORD */

  if (tokens_head->type == OPEN_PAREN) {
    free_head_token(); /* OPEN_PAREN */
  }

  assert((tokens_head->type == SINGLE_QUOTED_STRING) ||
           (tokens_head->type == DOUBLE_QUOTED_STRING));

  line_start = tokens_head->start_line;
  column_start = tokens_head->start_column + 1;
  line_end = tokens_head->end_line;
  column_end = tokens_head->end_column - 1;

  filename = tokens_head->strval;

  result = sn_insert_symbol(SN_INCLUDE_DEF,
          /* classname */ NULL,
          filename,
          sn_current_file(),
          line_start, column_start,
          line_end, column_end,
          /* attr */ 0,
          /* ret */ NULL,
          /* arg_types */ NULL,
          /* arg_names */ NULL,
          /* comment */ NULL,
          line_start, column_start,
          line_end, column_end);

  assert(result == 0);

  free_head_token(); /* SINGLE_QUOTED_STRING || DOUBLE_QUOTED_STRING */

  if (tokens_head->type == CLOSE_PAREN) {
    free_head_token(); /* CLOSE_PAREN */
  }

  free_head_token(); /* SEMICOLON */
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 869 "phpbrowser.l"
{
  SearchEntry entry;

#ifdef TOKEN_DEBUG
  fprintf(tokenout, "global statement found at %d\n", token_index);
#endif

  free_head_token(); /* GLOBAL_KEYWORD */

  if (current_function && (global_var_table == NULL)) {
    global_var_table = SearchTableCreate(100, SEARCH_HASH_TABLE, FreeGlobalEntry);
  }

  /* Insert the variable name into the function's global table */

  while (tokens_head->type == VARIABLE) {
    if (current_function) {
        entry.key = tokens_head->strval;
        entry.key_len = -1;

        if (global_var_table->search( &global_var_table, entry ) == NULL)
        {
            entry.data = NULL;
            entry.data_len = 0;
            entry.flag = SEARCH_DUP_KEY; /* add copy of entry.key */
            global_var_table->add( &global_var_table, entry );

#ifdef TOKEN_DEBUG
  fprintf(tokenout, "added global \"%s\"\n", entry.key);
#endif
        }
    }

    free_head_token(); /* VARIABLE */
  }

  free_head_token(); /* SEMICOLON */
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 908 "phpbrowser.l"
{
  char* fname;
  int line;

#ifdef TOKEN_DEBUG
  fprintf(tokenout, "found function call tokens at %d\n", token_index);
  fprintf(tokenout, "match text was \"%s\"\n", yytext);
#endif

  fname = tokens_head->strval;
#ifdef TOKEN_DEBUG
  fprintf(tokenout, "function name is \"%s\"\n", fname);
#endif
  line = tokens_head->start_line;

  result = sn_insert_xref(SN_REF_TO_FUNCTION,
                 SN_FUNC_DEF,
                 SN_REF_SCOPE_GLOBAL,
                 NULL,
                 (current_function == NULL) ? "GLOBAL" : current_function,
                 NULL,
                 NULL,
                 fname,
                 NULL, 
                 sn_current_file(),
                 line,
                 SN_REF_PASS);

  assert(result == 0);

  free_head_token(); /* SOMEWORD */
  free_head_token(); /* OPEN_PAREN */
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 942 "phpbrowser.l"
{
  char* varname = tokens_head->strval;
  SearchEntry entry;
  int ref_to_symbol_type, ref_to_symbol_scope, symbol_def_type;
  int line_start, line_end, column_start, column_end;

  line_start = tokens_head->start_line;
  column_start = tokens_head->start_column;
  line_end = tokens_head->end_line;
  column_end = tokens_head->end_column;

#ifdef TOKEN_DEBUG
  fprintf(tokenout, "variable assignment at token %d\n", token_index);
#endif

  /*
   * If we are not in a function or the variable is in the
   * function's global table then it is a global.
   */

  entry.key = varname;
  entry.key_len = -1;

  if ((current_function == NULL) ||
      (global_var_table &&
        (global_var_table->search( &global_var_table, entry ) != NULL))) {
    ref_to_symbol_type = SN_REF_TO_GLOB_VAR;
    ref_to_symbol_scope = SN_REF_SCOPE_GLOBAL;
    symbol_def_type = SN_GLOB_VAR_DEF;
#ifdef TOKEN_DEBUG
    fprintf(tokenout, "global var \"%s\"\n", varname);
#endif
  } else {
    ref_to_symbol_type = SN_REF_TO_LOCAL_VAR;
    ref_to_symbol_scope = SN_REF_SCOPE_LOCAL;
    symbol_def_type = SN_LOCAL_VAR_DEF;
#ifdef TOKEN_DEBUG
    fprintf(tokenout, "local var \"%s\"\n", varname);
#endif
  }

  /* I think setting a global variable should emit
     a symbol declaration. I am not really
     sure if we should emit just one symbol
     declaration, or multiple ones. Multiple
     ones breaks xref but it does present
     the symbol multiple times in the
     file's symbol list which would be
     nice if it worked correctly */

  result = sn_insert_symbol(symbol_def_type,
                            NULL,
			    varname,
			    sn_current_file(),
			    line_start, column_start,
			    line_end, column_end,
			    0,
			    NULL,
			    NULL,
			    NULL,
			    NULL,
			    line_start, column_start,
			    line_end, column_end
                            );
  assert(result == 0);

  /* FIXME: The second argument to sn_insert_xref must be one of SN_FUNC_DEF,
   * SN_MBR_FUNC_DEF, or SN_SUBR_DEF. This is too restrictive, there
   * needs to be an option to pass when not in a function. Currently,
   * we just pretend to be in a function named "GLOBAL".
   */

  if ((ref_to_symbol_type == SN_REF_TO_GLOB_VAR) ||
      ((ref_to_symbol_type == SN_REF_TO_LOCAL_VAR) &&
          ((int) sn_getopt(SN_OPT_LOCAL_VARS) != 0))) {

    result = sn_insert_xref(ref_to_symbol_type,
                 SN_FUNC_DEF, /* Not really in a function definition */
                 ref_to_symbol_scope,
                 NULL,
                 (current_function == NULL) ? "GLOBAL" : current_function,
                 NULL,
                 NULL,
                 varname,
                 NULL,
                 sn_current_file(),
                 line_start,
                 SN_REF_WRITE);

    assert(result == 0);
  }

  free_head_token(); /* VARIABLE */
  free_head_token(); /* ASSIGNMENT_OPERATOR || ASSIGNMENT_OPERATORS */
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 1038 "phpbrowser.l"
{
  char* varname = tokens_head->strval;
  SearchEntry entry;
  int line_num = tokens_head->start_line;
  int ref_to_symbol_type, ref_to_symbol_scope;

#ifdef TOKEN_DEBUG
  fprintf(tokenout, "variable access at token %d\n", token_index);
#endif

  /*
   * If we are not in a function or the variable is in the
   * function's global table then it is a global.
   */

  entry.key = varname;
  entry.key_len = -1;

  if ((current_function == NULL) ||
      (global_var_table &&
        (global_var_table->search( &global_var_table, entry ) != NULL))) {
    ref_to_symbol_type = SN_REF_TO_GLOB_VAR;
    ref_to_symbol_scope = SN_REF_SCOPE_GLOBAL;
#ifdef TOKEN_DEBUG
    fprintf(tokenout, "global var \"%s\"\n", varname);
#endif
  } else {
    ref_to_symbol_type = SN_REF_TO_LOCAL_VAR;
    ref_to_symbol_scope = SN_REF_SCOPE_LOCAL;
#ifdef TOKEN_DEBUG
    fprintf(tokenout, "local var \"%s\"\n", varname);
#endif
  }

  /* FIXME: The second argument to sn_insert_xref must be one of SN_FUNC_DEF,
   * SN_MBR_FUNC_DEF, or SN_SUBR_DEF. This is too restrictive, there
   * needs to be an option to pass when not in a function. Currently,
   * we just pretend to be in a function named "GLOBAL".
   */

  if ((ref_to_symbol_type == SN_REF_TO_GLOB_VAR) ||
      ((ref_to_symbol_type == SN_REF_TO_LOCAL_VAR) &&
          ((int) sn_getopt(SN_OPT_LOCAL_VARS) != 0))) {

    result = sn_insert_xref(ref_to_symbol_type,
                 SN_FUNC_DEF, /* Not really in a function definition */
                 ref_to_symbol_scope,
                 NULL,
                 (current_function == NULL) ? "GLOBAL" : current_function,
                 NULL,
                 NULL,
                 varname,
                 NULL,
                 sn_current_file(),
                 line_num,
                 SN_REF_READ);

    assert(result == 0);
  }

  free_head_token(); /* VARIABLE */
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 1101 "phpbrowser.l"
{
#ifdef TOKEN_DEBUG
  fprintf(tokenout, "ate token %d %s", token_index,
          TokenTypeToString(tokens_head));
  if (tokens_head->strval) {
      fprintf(tokenout, " \"%s\"", tokens_head->strval);
  }
  fprintf(tokenout, "\n");
#endif

  free_head_token(); /* ... */
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 1114 "phpbrowser.l"

	YY_BREAK
case 56:
YY_RULE_SETUP
#line 1116 "phpbrowser.l"
{
#ifdef TOKEN_DEBUG
    fprintf(tokenout, "matched unknown character \"%s\"\n", yytext);
#endif
}
	YY_BREAK
case YY_STATE_EOF(TOKEN):
#line 1122 "phpbrowser.l"
{
#ifdef TOKEN_DEBUG
    fprintf(tokenout, "reached EOF in TOKEN buffer\n");
#endif

    /* A function closing brace was not found before we hit EOF */
    if (current_function) {
        current_function_line_end = sn_line();
        current_function_column_end = sn_column();

#ifdef TOKEN_DEBUG
        fprintf(tokenout, "found unfinished function at EOF in %s\n", sn_current_file());
#endif

        emit_function_declaration();
    }

    assert(!tokens_head); /* all tokens were processed */

    yy_delete_buffer( YY_CURRENT_BUFFER );
    yy_switch_to_buffer( original_buffer );
    BEGIN(INITIAL);
    yyterminate();
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(PHP):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(DQSTRING):
case YY_STATE_EOF(SQSTRING):
case YY_STATE_EOF(HDSTRING):
#line 1147 "phpbrowser.l"
{
  LongString token_buffer;
  char *base;
  int i;
  Token* tok;
  yy_size_t size;
  YY_BUFFER_STATE yybs;

#ifdef TOKEN_DEBUG
  tokenout = fopen("tokens.out", "a");
  fprintf(tokenout, "reached EOF in lex input buffer in mode %s\n", modestring());
#endif

  /* See if we ran off the end of the lex input buffer in a special mode */
  switch (YY_START) {
    case COMMENT:
      emit_comment();
      break;
    case DQSTRING:
      emit_dqstring();
      break;
    case SQSTRING:
      emit_sqstring();
      break;
    case HDSTRING: 
      emit_hdstring();
      break;
  }

  /* If no tokens were generated, then quit now */
  if (tokens_head == NULL) {
#ifdef TOKEN_DEBUG
    fprintf(tokenout, "no TOKENs generated\n");
#endif
    yyterminate();
  }

  LongStringInit(&token_buffer,0);

  /* Print token info to in memory buffer and then reload
     the input state machine and start out in the TOKEN mode. */

  for (i=0, tok = tokens_head ; tok ; tok = tok->next, i++) {
#ifdef TOKEN_DEBUG
        fprintf(tokenout, "token %d %s", i, TokenTypeToString(tok));
        if (tok->strval) {
            fprintf(tokenout, " \"%s\"", tok->strval);
        }
        fprintf(tokenout, " (%d.%d -> %d.%d)",
            tok->start_line,
            tok->start_column,
            tok->end_line,
            tok->end_column
        );
        fprintf(tokenout, "\n");
#endif
        
        token_buffer.append( &token_buffer, TokenTypeToString(tok), -1);
        token_buffer.append( &token_buffer, " ", -1);
  }

#ifdef TOKEN_DEBUG
  fprintf(tokenout, "token buffer data is \"%s\"\n", token_buffer.buf);
#endif

  original_buffer = YY_CURRENT_BUFFER;
  yy_switch_to_buffer( yy_scan_string(token_buffer.buf) );

  token_buffer.free(&token_buffer);

#ifdef TOKEN_DEBUG
  fprintf(tokenout, "switching to token mode\n");
#endif

  BEGIN(TOKEN);
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 1224 "phpbrowser.l"
ECHO;
	YY_BREAK

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 587 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 587 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 586);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 1224 "phpbrowser.l"


/* Return a string that describes the current mode */

static char* modestring() {
    char* mode = "UNKNOWN";

    switch (YY_START) {
        case INITIAL:
            mode = "INITIAL";
            break;
        case PHP:
            mode = "PHP";
            break;
        case COMMENT:
            mode = "COMMENT";
            break;
        case DQSTRING:
            mode = "DQSTRING";
            break;
        case SQSTRING:
            mode = "SQSTRING";
            break;
        case HDSTRING:
            mode = "HDSTRING";
            break;
        case TOKEN:
            mode = "TOKEN";
            break;
    }
    return mode;
}

/* Helper method that will print matches as they are made */

static void matched_pattern(char * pattern, char * text) {
    char * mode = modestring();

    if (0) {
    fprintf(stderr, "Matched \"%s\", with text \"%s\", in mode \"%s\" (%d.%d)\n",
        pattern, text, mode, sn_line(), sn_column());
    }
}

static void FreeGlobalEntry(SearchEntry *entry) {}


void FreeToken(Token* tok) {
    if (tok->strval != NULL) {
        ckfree(tok->strval);
    }
    ckfree((char *) tok);
}

void append_token(TokenType type,
                  char* strval,
                  long start_line,
                  int start_column,
                  long end_line,
                  int end_column) {
    Token* tok;
    tok = (Token*) ckalloc(sizeof(Token));
    tok->type = type;
    if (strval)
        tok->strval = SN_StrDup(strval);
    else
        tok->strval = NULL;

    tok->start_line = start_line;
    tok->start_column = start_column;

    tok->end_line = end_line;
    tok->end_column = end_column;
    tok->next = NULL;

    /* append to token list */

    if (tokens_tail == NULL) {
        tokens_head = tokens_tail = tok;
    } else {
        tokens_tail->next = tok;
        tokens_tail = tok;
    }
}

void free_head_token() {
    Token* tok;
    assert(tokens_head);
    tok = tokens_head;
    if (tokens_head == tokens_tail) {
        tokens_head = tokens_tail = (Token*) NULL;
    } else {
        tokens_head = tokens_head->next;
    }
    FreeToken(tok);
    token_index++;
}

char * TokenTypeToString(Token *tok) {
    switch(tok->type) {
        case OPEN_PAREN:
            return "OPEN_PAREN";
        case CLOSE_PAREN:
            return "CLOSE_PAREN";
        case OPEN_BRACE:
            return "OPEN_BRACE";
        case CLOSE_BRACE:
            return "CLOSE_BRACE";
        case OPEN_BRACKET:
            return "OPEN_BRACKET";
        case CLOSE_BRACKET:
            return "CLOSE_BRACKET";
        case SEMICOLON:
            return "SEMICOLON";
        case COMMA:
            return "COMMA";
        case VARIABLE:
            return "VARIABLE";
        case ARRAY_VARIABLE:
            return "ARRAY_VARIABLE";
        case ASSIGNMENT_OPERATOR:
            return "ASSIGNMENT_OPERATOR";
        case ASSIGNMENT_OPERATORS:
            return "ASSIGNMENT_OPERATORS";
        case SOMEWORD:
            return "SOMEWORD";
        case KEYWORD:
            return "KEYWORD";
        case FUNCTION_KEYWORD:
            return "FUNCTION_KEYWORD";
        case GLOBAL_KEYWORD:
            return "GLOBAL_KEYWORD";
        case INCLUDE_KEYWORD:
            return "INCLUDE_KEYWORD";
        case DOUBLE_QUOTED_STRING:
            return "DOUBLE_QUOTED_STRING";
        case SINGLE_QUOTED_STRING:
            return "SINGLE_QUOTED_STRING";
        case UNKNOWN:
            return "UNKNOWN";
        default:
            return "TOKEN_NOT_MATCHED";
    }
}

/* Called when the closing brace of a function is found
 * or when we hit EOF without finding the end of the
 * function.
 */

void emit_function_declaration() {
    result = sn_insert_symbol(SN_FUNC_DEF,
            NULL,
            current_function,
            sn_current_file(), 
            current_function_line_start, current_function_column_start,
            current_function_line_end, current_function_column_end,
            0 /* attribute */,
            NULL /* return type */,
            NULL /* argument types */,
            current_function_args /* argument names */,
            NULL /* comment */,
            current_function_highlight_line,
            current_function_highlight_column_start,
            current_function_highlight_line,
            current_function_highlight_column_end );

    assert(result == 0);

    ckfree(current_function);
    current_function = NULL;
    ckfree(current_function_args);
    current_function_args = NULL;

    if (global_var_table) {
      global_var_table->destroy( &global_var_table );
      global_var_table = NULL;
    }
}

void emit_comment() {
    char* comment = mode_buff.buf;

#if COMMENT_DUMP
    fprintf(stderr, "emit comment \"%s\"\n", comment);
#endif

    sn_insert_comment(
        /* classname */ NULL,
        /* funcname */ NULL,
        sn_current_file(),
        comment,
        mode_start_line,
        mode_start_column);

    mode_buff.free(&mode_buff);
}

void emit_dqstring() {
    char* dqstring = mode_buff.buf;

#if DQSTRING_DUMP
    fprintf(stderr, "creating dqstring token \"%s\"\n", dqstring);
#endif

    append_token(DOUBLE_QUOTED_STRING, dqstring,
            mode_start_line,
            mode_start_column,
            sn_line(),
            sn_column());

    mode_buff.free(&mode_buff);
}

void emit_sqstring() {
    char* sqstring = mode_buff.buf;

#if SQSTRING_DUMP
    fprintf(stderr, "creating sqstring token \'%s\'\n", sqstring);
#endif

    append_token(SINGLE_QUOTED_STRING, sqstring,
            mode_start_line,
            mode_start_column,
            sn_line(),
            sn_column());

    mode_buff.free(&mode_buff);
}

void emit_hdstring() {
    char* hdstring = mode_buff.buf;

#if HDSTRING_DUMP
    fprintf(stderr, "creating hdstring token \"%s\"\n", hdstring);
#endif

    /* sn_column() should be at the ; at the end of a heredoc */

    append_token(DOUBLE_QUOTED_STRING, hdstring,
            mode_start_line,
            mode_start_column,
            sn_line(),
            sn_column());

    /* A heredoc string is followed by a SEMICOLON */

    append_token(SEMICOLON, NULL,
            sn_line(),
            sn_column(),
            sn_line(),
            sn_column()+1);

    mode_buff.free(&mode_buff);
}
 
void
reset()
{
  assert(!current_function);
  sn_reset_line();
  sn_reset_column();
}

int
main(int argc, char *argv[])
{
  return sn_main(argc, argv, group, &yyin, yylex, reset);
}
