/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 40
#define YY_END_OF_BUFFER 41
static yyconst short int yy_accept[550] =
    {   0,
        0,    0,    5,    5,    0,    0,    0,    0,   41,   28,
       27,   28,    5,    6,    7,   28,   28,   28,   28,   10,
       11,   28,   28,   24,   16,   17,   28,   12,   28,   13,
       24,   24,   24,   24,   24,   24,   24,   14,   15,   39,
       40,   38,   37,   37,   37,   37,   37,   37,   37,   37,
        1,    5,    6,    7,    8,    7,    9,    0,    0,    0,
       23,   26,    0,   18,    3,    0,   24,    2,   25,   24,
       24,   24,   24,   22,   24,   24,   37,   37,   37,   37,
       37,   37,   37,   37,    0,    4,   24,   24,   24,   24,
       37,   37,   37,   37,   37,   37,   37,   24,   24,   24,

       24,   37,   37,   37,   37,   37,   37,   37,   24,   24,
       24,   24,   37,   37,   37,   37,   37,   37,   37,   24,
       20,   24,   24,   37,   37,   37,   37,   37,   37,   37,
       24,   21,   21,   37,   37,   37,   37,   37,   37,   37,
       19,   24,   24,   37,   37,   37,   37,   37,   37,   36,
       24,   24,   37,   37,   37,   37,   37,    0,    0,   24,
       24,   37,   37,   37,   37,   30,    0,    0,   24,   24,
       31,   37,   37,   37,    0,    0,   21,   37,   37,   37,
        0,    0,   37,   37,   37,    0,    0,   37,   37,   37,
        0,    0,   37,    0,   37,    0,    0,   37,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   34,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   35,    0,    0,    0,    0,    0,    0,    0,   35,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   33,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   32,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   29,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    6,    1,    1,    7,    8,
        9,   10,   11,    1,   12,    1,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,   15,   16,
       17,   18,   19,    1,   20,   21,   22,   23,   24,   25,
       26,   14,   27,   14,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   14,   41,   14,
       42,   43,   44,    1,   45,    1,   46,   47,   48,   49,

       50,   51,   52,   14,   53,   14,   14,   54,   14,   55,
       56,   14,   57,   58,   14,   59,   60,   14,   14,   61,
       14,   14,   62,    1,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[64] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    3,    1,    1,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1
    } ;

static yyconst short int yy_base[562] =
    {   0,
        0,    1,    2,    3,   17,    0,   80,    0,  762,  763,
      763,  742,  757,  763,  141,  143,  754,    0,  751,  763,
      763,  740,  136,    0,  763,  763,  738,  763,  749,  763,
      699,  693,  698,  696,  692,  699,  692,  763,  763,  763,
      763,  763,    0,  718,  708,  716,  713,  710,  710,  721,
      763,  737,  763,  145,  763,  147,  763,  157,  726,  733,
      763,    0,  730,  763,  763,  733,    0,  763,  763,  686,
      679,  677,  684,    0,  674,  672,    0,  697,  697,  695,
      704,  701,  694,  688,  719,  763,  673,  673,  665,  658,
      681,  694,  694,  685,  682,  688,  684,  651,  663,  648,

      654,  682,  668,  684,  665,  657,  661,  680,  646,  644,
      648,  638,  650,  667,  664,  669,  670,  658,  668,  632,
        0,  637,  636,  664,  652,  638,  658,  646,  645,  650,
      623,  632,  631,  640,  643,  645,  627,  651,  647,  645,
        0,  612,  611,  646,  620,  640,  635,  640,  657,  656,
      604,  603,  635,  628,  614,  630,  629,  620,  631,  602,
      601,  624,  623,  606,  604,    0,  611,  607,  592,  591,
        0,  599,  607,  598,  613,  600,    0,  595,  599,  601,
      601,  604,  598,  606,  593,  582,  600,  590,  620,  600,
      589,  590,  597,  580,  614,  597,  586,  611,  594,  139,

      578,  588,  575,  575,  577,  575,  580,  582,  574,  572,
      576,  564,  577,  569,  568,  561,  567,  576,  574,  563,
      567,  763,  547,  567,  569,  560,  543,  558,  554,  545,
      555,  559,  549,  557,  547,  547,  554,  532,  556,  530,
      550,  538,  568,  537,  535,  535,  533,  544,  127,  528,
      541,  526,  543,  558,  537,  540,  527,  527,  525,  519,
      523,  524,  518,  515,  547,  513,  517,  515,  520,  519,
      521,  129,  520,  508,  518,  519,  520,  516,  506,  510,
      513,  499,  503,  501,  511,  486,  492,  498,  483,  763,
      482,  497,  496,  488,  502,  496,  485,  487,  487,  494,

      480,  487,  486,  477,  493,  481,  507,  475,  485,  484,
      472,  471,  763,  128,  478,  459,  458,  475,  477,  469,
      465,  464,  466,  465,  469,  456,  455,  466,  487,  486,
      457,  456,  146,  451,  449,  448,  455,  463,  458,  457,
      456,  447,  443,  447,  453,  452,  438,  446,  445,  426,
      425,  445,  448,  445,  430,  429,  419,  442,  430,  424,
      423,  426,  429,  428,  421,  420,  434,  429,  420,  424,
      423,  414,  444,  416,  415,  414,  420,  152,  763,  417,
      416,  410,  404,  419,  434,  433,  400,  400,  412,  401,
      405,  404,  401,  396,  402,  407,  394,  401,  393,  402,

      386,  390,  390,  390,  394,  372,  392,  391,  369,  392,
      381,  407,  377,  374,  371,  156,  387,  386,  360,  368,
      368,  380,  369,  364,  375,  374,  364,  369,  364,  390,
      369,  366,  387,  763,  355,  358,  352,  367,  356,  361,
      347,  359,  352,  349,  349,  352,  343,  340,  354,  371,
      329,  328,  146,  318,  315,  336,  169,  173,  306,  304,
      157,  176,  177,  311,  303,  182,  179,  298,  180,  183,
      312,  186,  189,  294,  184,  185,  298,  188,  190,  294,
      193,  194,  318,  195,  202,  179,  200,  203,  316,  207,
      214,  212,  219,  199,  213,  215,  221,  222,  229,  216,

      224,  231,  243,  244,  245,  248,  250,  251,  249,  252,
      253,  254,  255,  256,  258,  259,  260,  261,  257,  262,
      263,  266,  264,  273,  275,  276,  267,  274,   11,  279,
      302,  304,  305,  278,  303,  281,  306,  308,  309,  312,
      314,  310,  311,  320,  321,  315,  317,   10,  763,  352,
      355,  358,  361,  364,    8,  367,    7,    6,  370,    5,
        4
    } ;

static yyconst short int yy_def[562] =
    {   0,
      550,  550,  551,  551,  549,    5,  549,    7,  549,  549,
      549,  549,  552,  549,  553,  549,  554,  555,  556,  549,
      549,  549,  549,  557,  549,  549,  549,  549,  549,  549,
      557,  557,  557,  557,  557,  557,  557,  549,  549,  549,
      549,  549,  558,  558,  558,  558,  558,  558,  558,  558,
      549,  552,  549,  553,  549,  553,  549,  549,  549,  554,
      549,  555,  556,  549,  549,  559,  557,  549,  549,  557,
      557,  557,  557,  557,  557,  557,  558,  558,  558,  558,
      558,  558,  558,  558,  559,  549,  557,  557,  557,  557,
      558,  558,  558,  558,  558,  558,  558,  557,  557,  557,

      557,  558,  558,  558,  558,  558,  558,  558,  557,  557,
      557,  557,  558,  558,  558,  558,  558,  558,  558,  557,
      557,  557,  557,  558,  558,  558,  558,  558,  558,  558,
      557,  557,  557,  558,  558,  558,  558,  558,  558,  558,
      557,  557,  557,  558,  558,  558,  558,  558,  558,  558,
      557,  557,  558,  558,  558,  558,  558,  549,  549,  557,
      557,  558,  558,  558,  558,  558,  549,  549,  557,  557,
      558,  558,  558,  558,  549,  549,  557,  558,  558,  558,
      549,  549,  558,  558,  558,  549,  549,  558,  558,  558,
      549,  549,  558,  549,  558,  549,  549,  558,  549,  549,

      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,

      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,

      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  560,  549,  549,  560,  560,  560,  549,  549,
      549,  560,  560,  549,  549,  560,  560,  549,  560,  560,
      549,  560,  560,  549,  560,  560,  549,  560,  560,  549,
      560,  560,  549,  560,  560,  561,  560,  560,  561,  561,
      561,  560,  560,  549,  561,  561,  560,  560,  561,  561,

      560,  560,  561,  561,  560,  560,  561,  561,  560,  560,
      561,  561,  560,  560,  561,  561,  560,  560,  561,  561,
      560,  560,  561,  561,  560,  560,  561,  561,  560,  561,
      561,  561,  561,  561,  561,  561,  561,  561,  561,  561,
      561,  561,  561,  561,  561,  561,  561,  561,    0,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549
    } ;

static yyconst short int yy_nxt[827] =
    {   0,
      549,  549,   11,   11,   14,   14,  489,  456,   77,   67,
       62,   15,   15,  494,  461,   12,   12,   10,   16,   11,
       16,   17,   18,   19,   20,   21,   22,   22,   22,   23,
       24,   25,   10,   26,   10,   27,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   28,   29,
       30,   24,   31,   24,   24,   24,   24,   32,   33,   34,
       24,   24,   35,   24,   36,   24,   24,   37,   38,   39,
       40,   40,   41,   42,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   43,   40,   40,   40,   40,   40,   43,

       43,   44,   43,   43,   45,   46,   47,   43,   43,   43,
       43,   48,   43,   43,   43,   49,   43,   43,   50,   43,
       43,   40,   40,   40,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   40,   40,   55,   58,   65,   58,   55,   66,   55,
       56,  279,   64,   57,  549,   59,   56,  549,   58,   57,
       58,  205,  255,  255,  280,  256,  256,  337,  457,   59,
      206,  383,  461,  337,  207,  420,  461,  337,  337,  461,
      461,  458,  461,  461,  338,  461,  461,  461,  461,  461,
      384,  461,  461,  461,  384,  384,  461,  461,  461,  463,

      462,  490,  469,  461,  470,  461,  461,  467,  472,  475,
      494,  473,  476,  466,  491,  461,  494,  494,  494,  494,
      337,  481,  461,  482,  461,  461,  487,  461,  478,  479,
      484,  485,  494,  488,  461,  497,  492,  384,  495,  493,
      496,  504,  498,  501,  502,  500,  494,  494,  461,  503,
      499,  461,  461,  494,  494,  461,  494,  494,  461,  461,
      494,  494,  494,  461,  461,  494,  461,  494,  505,  461,
      494,  507,  508,  511,  512,  506,  494,  494,  461,  461,
      509,  494,  494,  510,  494,  513,  521,  522,  514,  517,
      518,  519,  520,  525,  523,  527,  526,  515,  516,  524,

      529,  529,  532,  530,  528,  494,  494,  494,  494,  494,
      531,  494,  494,  494,  494,  494,  538,  494,  494,  494,
      494,  486,  536,  494,  494,  533,  534,  535,  483,  480,
      477,  474,  471,  379,  468,  465,  544,  545,  464,  461,
      548,  539,  548,  460,  540,  541,  542,  537,  543,  459,
      546,  547,   10,   10,   10,   13,   13,   13,   52,  455,
       52,   54,   54,   54,   60,   60,   60,   63,   63,   63,
       85,   85,   85,  454,  453,  452,  451,  450,  449,  448,
      447,  446,  445,  444,  443,  442,  441,  440,  439,  438,
      437,  436,  435,  434,  433,  432,  431,  430,  429,  428,

      427,  426,  425,  424,  423,  422,  421,  419,  418,  417,
      416,  415,  414,  413,  412,  411,  410,  409,  408,  407,
      406,  405,  404,  403,  402,  401,  400,  399,  398,  397,
      396,  395,  394,  393,  392,  391,  390,  389,  388,  387,
      386,  385,  385,  382,  381,  380,  379,  378,  377,  376,
      375,  374,  373,  372,  371,  370,  369,  368,  367,  366,
      365,  364,  363,  362,  361,  360,  359,  358,  357,  356,
      355,  354,  353,  352,  351,  350,  349,  348,  347,  346,
      345,  344,  343,  342,  341,  340,  339,  336,  335,  334,
      333,  330,  332,  331,  330,  329,  328,  327,  326,  325,

      324,  323,  322,  321,  320,  319,  318,  317,  316,  315,
      314,  313,  312,  311,  310,  309,  308,  307,  306,  305,
      304,  303,  302,  301,  300,  299,  298,  297,  296,  295,
      294,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  278,  277,  276,  275,  274,  273,
      272,  271,  270,  269,  268,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  254,  253,  252,  251,
      250,  249,  248,  247,  246,  245,  244,  243,  242,  241,
      240,  239,  238,  237,  236,  235,  234,  233,  232,  231,
      230,  229,  228,  227,  226,  225,  224,  223,  222,  221,

      220,  219,  218,  217,  216,  215,  214,  213,  212,  211,
      210,  209,  208,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  189,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  179,  178,
      177,  177,  176,  175,  174,  173,  172,  171,  170,  169,
      168,  167,  166,  165,  164,  163,  162,  161,  160,  159,
      158,  157,  156,  155,  154,  153,  152,  151,  150,  149,
      148,  147,  146,  145,  144,  143,  142,  141,  140,  139,
      138,  137,  136,  135,  134,  133,  132,  131,  130,  129,
      128,  127,  126,  125,  124,  123,  122,  121,  120,  119,

      118,  117,  116,  115,  114,  113,  112,  111,  110,  109,
      108,  107,  106,  105,  104,  103,  102,  101,  100,   99,
       98,   86,   97,   96,   95,   94,   93,   92,   91,   74,
       90,   89,   88,   87,   74,   86,   61,   61,   66,   53,
       84,   83,   82,   81,   80,   79,   78,   76,   75,   74,
       73,   72,   71,   70,   69,   68,   64,   61,   61,   53,
       51,  549,    9,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,

      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549
    } ;

static yyconst short int yy_chk[827] =
    {   0,
        0,    0,    1,    2,    3,    4,  561,  560,  558,  557,
      555,    3,    4,  548,  529,    1,    2,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,   15,   16,   23,   16,   54,   23,   56,
       15,  272,   23,   15,   54,   16,   56,   54,   58,   56,
       58,  200,  249,  314,  272,  249,  314,  333,  453,   58,
      200,  378,  457,  378,  200,  416,  458,  416,  461,  462,
      463,  453,  467,  469,  333,  466,  470,  475,  476,  472,
      378,  478,  473,  479,  416,  461,  481,  482,  484,  458,

      457,  486,  466,  487,  467,  485,  488,  463,  469,  472,
      490,  470,  473,  462,  486,  492,  495,  491,  496,  500,
      494,  478,  493,  479,  497,  498,  484,  501,  475,  476,
      481,  482,  499,  485,  502,  492,  487,  494,  490,  488,
      491,  500,  493,  497,  498,  496,  503,  504,  505,  499,
      495,  506,  509,  507,  508,  510,  511,  512,  513,  514,
      519,  515,  516,  517,  518,  520,  521,  523,  501,  522,
      527,  503,  504,  507,  508,  502,  524,  528,  525,  526,
      505,  534,  530,  506,  536,  509,  517,  518,  510,  513,
      514,  515,  516,  521,  519,  523,  522,  511,  512,  520,

      525,  526,  530,  527,  524,  531,  535,  532,  533,  537,
      528,  538,  539,  542,  543,  540,  536,  541,  546,  489,
      547,  483,  534,  544,  545,  531,  532,  533,  480,  477,
      474,  471,  468,  465,  464,  460,  542,  543,  459,  456,
      546,  537,  547,  455,  538,  539,  540,  535,  541,  454,
      544,  545,  550,  550,  550,  551,  551,  551,  552,  452,
      552,  553,  553,  553,  554,  554,  554,  556,  556,  556,
      559,  559,  559,  451,  450,  449,  448,  447,  446,  445,
      444,  443,  442,  441,  440,  439,  438,  437,  436,  435,
      433,  432,  431,  430,  429,  428,  427,  426,  425,  424,

      423,  422,  421,  420,  419,  418,  417,  415,  414,  413,
      412,  411,  410,  409,  408,  407,  406,  405,  404,  403,
      402,  401,  400,  399,  398,  397,  396,  395,  394,  393,
      392,  391,  390,  389,  388,  387,  386,  385,  384,  383,
      382,  381,  380,  377,  376,  375,  374,  373,  372,  371,
      370,  369,  368,  367,  366,  365,  364,  363,  362,  361,
      360,  359,  358,  357,  356,  355,  354,  353,  352,  351,
      350,  349,  348,  347,  346,  345,  344,  343,  342,  341,
      340,  339,  338,  337,  336,  335,  334,  332,  331,  330,
      329,  328,  327,  326,  325,  324,  323,  322,  321,  320,

      319,  318,  317,  316,  315,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  294,  293,  292,  291,  289,  288,  287,
      286,  285,  284,  283,  282,  281,  280,  279,  278,  277,
      276,  275,  274,  273,  271,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  258,  257,  256,
      255,  254,  253,  252,  251,  250,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  236,  235,
      234,  233,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  223,  221,  220,  219,  218,  217,  216,  215,  214,

      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  201,  199,  198,  197,  196,  195,  194,  193,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  183,
      182,  181,  180,  179,  178,  176,  175,  174,  173,  172,
      170,  169,  168,  167,  165,  164,  163,  162,  161,  160,
      159,  158,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  148,  147,  146,  145,  144,  143,  142,  140,  139,
      138,  137,  136,  135,  134,  133,  132,  131,  130,  129,
      128,  127,  126,  125,  124,  123,  122,  120,  119,  118,
      117,  116,  115,  114,  113,  112,  111,  110,  109,  108,

      107,  106,  105,  104,  103,  102,  101,  100,   99,   98,
       97,   96,   95,   94,   93,   92,   91,   90,   89,   88,
       87,   85,   84,   83,   82,   81,   80,   79,   78,   76,
       75,   73,   72,   71,   70,   66,   63,   60,   59,   52,
       50,   49,   48,   47,   46,   45,   44,   37,   36,   35,
       34,   33,   32,   31,   29,   27,   22,   19,   17,   13,
       12,    9,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,

      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549,  549,  549,  549,  549,
      549,  549,  549,  549,  549,  549
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "phpbrowser.l"
#define INITIAL 0
/*

Copyright (c) 2003, Mo DeJong

This file is part of Source-Navigator.

Source-Navigator is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License as published
by the Free Software Foundation; either version 2, or (at your option)
any later version.

Source-Navigator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License along
with Source-Navigator; see the file COPYING.  If not, write to
the Free Software Foundation, 59 Temple Place - Suite 330, Boston,
MA 02111-1307, USA.



*/
/*
 * phpbrowser.l
 *
 * Copyright (C) 2003 Mo DeJong
 *
 * Description:
 * Lex input file for an php language processor.
 */
#line 36 "phpbrowser.l"

#include <ctype.h>
#include <stdlib.h>
#include <stdio.h>
#include "snptools.h"
#include "lexinput.h"
#include "longstr.h"
#include "srchtbl.h"
#include "tcl.h"

#undef YY_INPUT
#define YY_INPUT(buf,r,ms) (r = sn_encoded_input(buf, ms))

#undef yywrap
#define YY_SKIP_YYWRAP

typedef enum {
    OPEN_PAREN,    /* '(' */
    CLOSE_PAREN,   /* ')' */
    OPEN_BRACE,    /* '{' */
    CLOSE_BRACE,   /* '}' */
    OPEN_BRACKET,  /* '[' */
    CLOSE_BRACKET, /* ']' */
    SEMICOLON,     /* ';' */
    COMMA,         /* ',' */

    VARIABLE,      /* $var */
    ARRAY_VARIABLE, /* $var['one'] */
    ASSIGNMENT_OPERATOR, /* '=' */
    ASSIGNMENT_OPERATORS, /* = -= += and so on */

    SOMEWORD,          /* a sequence of text */
    KEYWORD,       /* a key sequence in this language */
    FUNCTION_KEYWORD, /* The keyword "function" */
    GLOBAL_KEYWORD, /* The keyword "global" */
    INCLUDE_KEYWORD, /* The keyword "include" */

    DOUBLE_QUOTED_STRING, /* "I am a double quoted string" */
    SINGLE_QUOTED_STRING,  /* 'I am a double quoted string' */

    UNKNOWN        /* Some unknown or unimportant text */
} TokenType;

typedef struct Token {
    TokenType type;
    char * strval; /* String value of token, NULL if single character */
    long line; /* line in file where symbol appears */
    int column; /* column where symbol starts */
    struct Token* next;
} Token;

/* Uncomment this to see debug output in token parsing stage */
/* #define TOKEN_DEBUG */

#ifdef TOKEN_DEBUG
FILE* tokenout = NULL;
#endif

Token* tokens_head = NULL;
Token* tokens_tail = NULL;
int token_index = 0; /* current offset from original token_head */

static char group[] = "php";

#define MAX_SIZE 512

/* FIXME: Can't pass NULL or "" as current function (core dump) */
static char* current_function = (char *) NULL;
static char* current_function_args = (char *) NULL;

/* line number where highlight starts and ends */
static int  current_function_highlight_line;

/* in "function fog() {}" column of 'f' in "fog" */
static int  current_function_highlight_column_start;

/* in "function fog() {}" column of 'g' in "fog" */
static int  current_function_highlight_column_end;

/* line where "function" appears */
static int  current_function_line_start;

/* line where closing brace of function appears */
static int  current_function_line_end;

/* in "function fog() {}" column of 'f' in "function" */
static int  current_function_column_start;

/* in "function fog() {}" column of '}' in "{}" */
static int  current_function_column_end;

static int  current_function_brace_count;

static int result;

static SearchTable * global_var_table = (SearchTable *) NULL;

/* Stores a comment buffer that could be built over multiple lines/rules. */
LongString cbuff;
int cbuff_start_line;
int cbuff_start_column;
#define COMMENT_DUMP 0

static YY_BUFFER_STATE original_buffer;

static void matched_pattern(char * pattern, char * text);

static void FreeGlobalEntry(SearchEntry *entry);

Token* AllocToken();
void FreeToken(Token* tok);
void free_head_token();
void add_token(Token* tok);
char * TokenTypeToString(Token *tok);

int yywrap() { return 1; }

#define COMMENT 1

#define PHP 2

#define TOKEN 3


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 194 "phpbrowser.l"



	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 550 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 763 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 196 "phpbrowser.l"
{ /* HTML -> PHP mode */
    matched_pattern("<?", yytext);
    BEGIN(PHP);
    sn_advance_column(2);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 202 "phpbrowser.l"
{ /* PHP -> HTML mode */
    matched_pattern("?>", yytext);
    BEGIN(INITIAL);
    sn_advance_column(2);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 208 "phpbrowser.l"
{ /* A C style multi-line comment, just like this! */
    matched_pattern("/*", yytext);
    BEGIN(COMMENT);
    sn_advance_column(2);
    LongStringInit(&cbuff,0);
    cbuff_start_line = sn_line();
    cbuff_start_column = sn_column();
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 217 "phpbrowser.l"
{ /* A C++ style line comment -> // This function is quite nice. <- */
  char * x = (char *) yytext;
  char * y = x + yyleng - 1;

  matched_pattern("//.*\\n", yytext);

  while (*x != '/') { x++; }
  x++;
  assert(*x == '/');
  x++;
  sn_advance_column(x - yytext);

  assert(*y == '\n');
  *y = '\0';

  sn_insert_comment(
    /* classname */ NULL,
    /* funcname */ NULL,
    sn_current_file(),
    x,
    sn_line(),
    sn_column());

  sn_advance_line();
  sn_reset_column();
}
	YY_BREAK

case 5:
YY_RULE_SETUP
#line 245 "phpbrowser.l"
{
    matched_pattern("[^\\*\\n]*", yytext);

    #if COMMENT_DUMP
    fprintf(stderr, "comment(1) \"%s\", %d\n", yytext, yyleng);
    #endif
    cbuff.append( &cbuff,
        yytext, yyleng );
    sn_advance_column(yyleng);
    }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 255 "phpbrowser.l"
{
    matched_pattern("[^\\*\\n]*\\n", yytext);

    #if COMMENT_DUMP
    fprintf(stderr, "comment(2) \"%s\", %d\n", yytext, yyleng);
    #endif

    cbuff.append( &cbuff,
        yytext, yyleng );
    sn_advance_line();
    sn_reset_column();
    }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 267 "phpbrowser.l"
{
    matched_pattern("\\*+[^\\*/\\n]*", yytext);

    #if COMMENT_DUMP
    fprintf(stderr, "comment(3) \"%s\", %d\n", yytext, yyleng);
    #endif

    cbuff.append( &cbuff,
        yytext, yyleng );
    sn_advance_column(yyleng);
  }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 278 "phpbrowser.l"
{
    matched_pattern("\\*+[^\\*/\\n]*\\n", yytext);

    #if COMMENT_DUMP
    fprintf(stderr, "comment(4) \"%s\", %d\n", yytext, yyleng);
    #endif

    cbuff.append( &cbuff,
        yytext, yyleng );
    sn_advance_line();
    sn_reset_column();
  }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 290 "phpbrowser.l"
{
    char * comment;

    matched_pattern("\\*+/", yytext);

    /* Include multiple '*' characters in the comment */
    if (yyleng > 2) {
        comment = (char *) yytext + yyleng - 1;
        assert(*comment == '/');
        comment--;
        assert(*comment == '*');
        *comment = '0';
        yyleng -= 2;
        cbuff.append( &cbuff,
            yytext, yyleng );
    }

    comment = cbuff.buf;

    #if COMMENT_DUMP
    fprintf(stderr, "eating comment \"%s\"\n", comment);
    #endif

    sn_insert_comment(
        /* classname */ NULL,
        /* funcname */ NULL,
        sn_current_file(),
        comment,
        cbuff_start_line,
        cbuff_start_column);

    cbuff.free(&cbuff);
    sn_advance_column(yyleng);
    BEGIN(PHP);
  }
	YY_BREAK

case 10:
YY_RULE_SETUP
#line 327 "phpbrowser.l"
{
  Token* tok;
  matched_pattern("(", yytext);
  tok = AllocToken();
  tok->type = OPEN_PAREN;
  tok->strval = NULL;
  tok->line = sn_line();
  tok->column = sn_column();
  add_token(tok);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 339 "phpbrowser.l"
{
  Token* tok;
  matched_pattern(")", yytext);
  tok = AllocToken();
  tok->type = CLOSE_PAREN;
  tok->strval = NULL;
  tok->line = sn_line();
  tok->column = sn_column();
  add_token(tok);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 351 "phpbrowser.l"
{
  Token* tok;
  matched_pattern("[", yytext);
  sn_advance_column(yyleng);
  tok = AllocToken();
  tok->type = OPEN_BRACKET;
  tok->strval = NULL;
  tok->line = sn_line();
  tok->column = sn_column();
  add_token(tok);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 364 "phpbrowser.l"
{
  Token* tok;
  matched_pattern("]", yytext);
  tok = AllocToken();
  tok->type = CLOSE_BRACKET;
  tok->strval = NULL;
  tok->line = sn_line();
  tok->column = sn_column();
  add_token(tok);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 376 "phpbrowser.l"
{
  Token* tok;
  matched_pattern("{", yytext);
  tok = AllocToken();
  tok->type = OPEN_BRACE;
  tok->strval = NULL;
  tok->line = sn_line();
  tok->column = sn_column();
  add_token(tok);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 388 "phpbrowser.l"
{
  Token* tok;
  matched_pattern("}", yytext);
  tok = AllocToken();
  tok->type = CLOSE_BRACE;
  tok->strval = NULL;
  tok->line = sn_line();
  tok->column = sn_column();
  add_token(tok);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 400 "phpbrowser.l"
{
  Token* tok;
  matched_pattern("}", yytext);
  tok = AllocToken();
  tok->type = SEMICOLON;
  tok->strval = NULL;
  add_token(tok);
  tok->line = sn_line();
  tok->column = sn_column();
  sn_advance_column(yyleng);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 412 "phpbrowser.l"
{
  Token* tok;
  matched_pattern("=", yytext);
  tok = AllocToken();
  tok->type = ASSIGNMENT_OPERATOR;
  tok->strval = NULL;
  tok->line = sn_line();
  tok->column = sn_column();
  add_token(tok);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 424 "phpbrowser.l"
{
  Token* tok;
  matched_pattern("{assignment-operators}", yytext);
  tok = AllocToken();
  tok->type = ASSIGNMENT_OPERATORS;
  tok->strval = SN_StrDup(yytext);
  tok->line = sn_line();
  tok->column = sn_column();
  add_token(tok);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 436 "phpbrowser.l"
{
  Token* tok;
  matched_pattern("function", yytext);
  tok = AllocToken();
  tok->type = FUNCTION_KEYWORD;
  tok->strval = SN_StrDup(yytext);
  tok->line = sn_line();
  tok->column = sn_column();
  add_token(tok);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 448 "phpbrowser.l"
{
  Token* tok;
  matched_pattern("global", yytext);
  tok = AllocToken();
  tok->type = GLOBAL_KEYWORD;
  tok->strval = SN_StrDup(yytext);
  tok->line = sn_line();
  tok->column = sn_column();
  add_token(tok);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 460 "phpbrowser.l"
{
  Token* tok;
  matched_pattern("{include-keywords}", yytext);
  tok = AllocToken();
  tok->type = INCLUDE_KEYWORD;
  tok->strval = SN_StrDup(yytext);
  tok->line = sn_line();
  tok->column = sn_column();
  add_token(tok);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 472 "phpbrowser.l"
{
  Token* tok;
  matched_pattern("{keywords}", yytext);
  tok = AllocToken();
  tok->type = KEYWORD;
  tok->strval = SN_StrDup(yytext);
  tok->line = sn_line();
  tok->column = sn_column();
  add_token(tok);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 484 "phpbrowser.l"
{
  Token* tok;
  matched_pattern("{q-string}", yytext);
  tok = AllocToken();
  if (*yytext == '\"') {
    tok->type = DOUBLE_QUOTED_STRING;
  } else {
    tok->type = SINGLE_QUOTED_STRING;
  }
  *(yytext + yyleng - 1) = 0;
  tok->strval = SN_StrDup(yytext+1);
  tok->line = sn_line();
  tok->column = sn_column();
  add_token(tok);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 501 "phpbrowser.l"
{
  Token* tok;
  matched_pattern("{someword}", yytext);
  tok = AllocToken();
  tok->type = SOMEWORD;
  tok->strval = SN_StrDup(yytext);
  tok->line = sn_line();
  tok->column = sn_column();
  add_token(tok);
  sn_advance_column(yyleng);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 513 "phpbrowser.l"
{
  matched_pattern("\\$", yytext);
  sn_advance_column(yyleng); /* ignore \$ */
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 518 "phpbrowser.l"
{
  Token* tok;
  matched_pattern("${varname}", yytext);
  sn_advance_column(1);

  tok = AllocToken();
  tok->type = VARIABLE;
  tok->strval = SN_StrDup(yytext+1);
  tok->line = sn_line();
  tok->column = sn_column();
  add_token(tok);

  sn_advance_column(yyleng-1);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 533 "phpbrowser.l"
{
  matched_pattern("\\n", yytext);
  sn_advance_line();
  sn_reset_column();
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 539 "phpbrowser.l"
{
  matched_pattern(".", yytext);
  sn_advance_column(yyleng); /* eat text */
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 546 "phpbrowser.l"
{
  int parens, noargs;
  LongString abuff;

#ifdef TOKEN_DEBUG
  fprintf(tokenout, "function declaration at token %d\n", token_index);
  fprintf(tokenout, "match text was \"%s\"\n", yytext);
#endif
  assert(tokens_head->type == FUNCTION_KEYWORD);

  current_function_line_start = tokens_head->line;
  current_function_column_start = tokens_head->column;

  free_head_token(); /* FUNCTION_KEYWORD */

  /* FIXME: It would be better to create a state stack and push
     the current state onto that (class, function, namespace) */
  assert(current_function == NULL);
  current_function = SN_StrDup(tokens_head->strval);

  current_function_highlight_line = tokens_head->line;
  current_function_highlight_column_start = tokens_head->column;
  current_function_highlight_column_end = tokens_head->column;
  current_function_highlight_column_end += strlen(current_function);

  free_head_token(); /* SOMEWORD */
  free_head_token(); /* OPEN_PAREN */

  /* Save function arguments in current_function_args */  
  parens = 1;
  noargs = 1;
  LongStringInit(&abuff,0);
  while (parens > 0) {
    if (tokens_head->type == OPEN_PAREN) {
      parens++;
    } else if (tokens_head->type == CLOSE_PAREN) {
      parens--;
    } else if (tokens_head->type == VARIABLE) {
        /* We just ignore default values for arguments */
        if (!noargs) {
            abuff.append( &abuff, ",", -1);
        }
        abuff.append( &abuff, tokens_head->strval, -1);
        noargs = 0;
    }

    free_head_token(); /* ... */
  }

  assert(current_function_args == NULL);
  if (!noargs) {
      current_function_args = SN_StrDup(abuff.buf);
  }
  abuff.free(&abuff);

  free_head_token(); /* OPEN_BRACE */

  current_function_brace_count = 1;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 606 "phpbrowser.l"
{
  if (current_function) {
    current_function_brace_count++;
  }
  free_head_token(); /* OPEN_BRACE */
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 613 "phpbrowser.l"
{
  if (current_function && (--current_function_brace_count == 0)) {
#ifdef TOKEN_DEBUG
    fprintf(tokenout, "end of function %s at token %d\n",
        current_function, token_index);
#endif

    current_function_line_end = tokens_head->line;
    current_function_column_end = tokens_head->column + 1;

    result = sn_insert_symbol(SN_FUNC_DEF,
            NULL,
            current_function,
            sn_current_file(), 
            current_function_line_start, current_function_column_start,
            current_function_line_end, current_function_column_end,
            0 /* attribute */,
            NULL /* return type */,
            NULL /* argument types */,
            current_function_args /* argument names */,
            NULL /* comment */,
            current_function_highlight_line,
            current_function_highlight_column_start,
            current_function_highlight_line,
            current_function_highlight_column_end );

    assert(result == 0);

    ckfree(current_function);
    current_function = NULL;
    ckfree(current_function_args);
    current_function_args = NULL;

    if (global_var_table) {
      global_var_table->destroy( &global_var_table );
      global_var_table = NULL;
    }
  }

  free_head_token(); /* CLOSE_BRACE */
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 655 "phpbrowser.l"
{
  int line_start, line_end, column_start, column_end;
  char * filename;

#ifdef TOKEN_DEBUG
  fprintf(tokenout, "include statement begins at token %d\n", token_index);
#endif

  free_head_token(); /* INCLUDE_KEYWORD */

  if (tokens_head->type == OPEN_PAREN) {
    free_head_token(); /* OPEN_PAREN */
  }

  assert((tokens_head->type == SINGLE_QUOTED_STRING) ||
           (tokens_head->type == DOUBLE_QUOTED_STRING));

  /* FIXME: Quoted strings can span lines so line_end needs fixing */
  line_end = line_start = tokens_head->line;
  column_start = tokens_head->column + 1;
  filename = tokens_head->strval;
  column_end = column_start + strlen(filename);

  result = sn_insert_symbol(SN_INCLUDE_DEF,
          /* classname */ NULL,
          filename,
          sn_current_file(),
          line_start, column_start,
          line_end, column_end,
          /* attr */ 0,
          /* ret */ NULL,
          /* arg_types */ NULL,
          /* arg_names */ NULL,
          /* comment */ NULL,
          line_start, column_start,
          line_end, column_end);

  assert(result == 0);

  free_head_token(); /* SINGLE_QUOTED_STRING || DOUBLE_QUOTED_STRING */

  if (tokens_head->type == CLOSE_PAREN) {
    free_head_token(); /* CLOSE_PAREN */
  }

  free_head_token(); /* SEMICOLON */
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 703 "phpbrowser.l"
{
  SearchEntry entry;

#ifdef TOKEN_DEBUG
  fprintf(tokenout, "global statement found at %d\n", token_index);
#endif

  free_head_token(); /* GLOBAL_KEYWORD */

  if (current_function && (global_var_table == NULL)) {
    global_var_table = SearchTableCreate(100, SEARCH_HASH_TABLE, FreeGlobalEntry);
  }

  /* Insert the variable name into the function's global table */

  while (tokens_head->type == VARIABLE) {
    if (current_function) {
        entry.key = tokens_head->strval;
        entry.key_len = -1;

        if (global_var_table->search( &global_var_table, entry ) == NULL)
        {
            entry.data = NULL;
            entry.data_len = 0;
            entry.flag = SEARCH_DUP_KEY; /* add copy of entry.key */
            global_var_table->add( &global_var_table, entry );

#ifdef TOKEN_DEBUG
  fprintf(tokenout, "added global \"%s\"\n", entry.key);
#endif
        }
    }

    free_head_token(); /* VARIABLE */
  }

  free_head_token(); /* SEMICOLON */
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 742 "phpbrowser.l"
{
  char* fname;
  int line;

#ifdef TOKEN_DEBUG
  fprintf(tokenout, "found function call tokens at %d\n", token_index);
  fprintf(tokenout, "match text was \"%s\"\n", yytext);
#endif

  fname = tokens_head->strval;
#ifdef TOKEN_DEBUG
  fprintf(tokenout, "function name is \"%s\"\n", fname);
#endif
  line = tokens_head->line;

  result = sn_insert_xref(SN_REF_TO_FUNCTION,
                 SN_FUNC_DEF,
                 SN_REF_SCOPE_GLOBAL,
                 NULL,
                 (current_function == NULL) ? "GLOBAL" : current_function,
                 NULL,
                 NULL,
                 fname,
                 NULL, 
                 sn_current_file(),
                 line,
                 SN_REF_PASS);

  assert(result == 0);

  free_head_token(); /* SOMEWORD */
  free_head_token(); /* OPEN_PAREN */
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 776 "phpbrowser.l"
{
  char* varname = tokens_head->strval;
  SearchEntry entry;
  int ref_to_symbol_type, ref_to_symbol_scope, symbol_def_type;
  int line_start, line_end, column_start, column_end;

  line_end = line_start = tokens_head->line;
  column_start = tokens_head->column;
  column_end = column_start;
  if (varname == NULL) {
    column_end += 1;
  } else {
    column_end += strlen(varname);
  }

#ifdef TOKEN_DEBUG
  fprintf(tokenout, "variable assignment at token %d\n", token_index);
#endif

  /*
   * If we are not in a function or the variable is in the
   * function's global table then it is a global.
   */

  entry.key = varname;
  entry.key_len = -1;

  if ((current_function == NULL) ||
      (global_var_table &&
        (global_var_table->search( &global_var_table, entry ) != NULL))) {
    ref_to_symbol_type = SN_REF_TO_GLOB_VAR;
    ref_to_symbol_scope = SN_REF_SCOPE_GLOBAL;
    symbol_def_type = SN_GLOB_VAR_DEF;
#ifdef TOKEN_DEBUG
    fprintf(tokenout, "global var \"%s\"\n", varname);
#endif
  } else {
    ref_to_symbol_type = SN_REF_TO_LOCAL_VAR;
    ref_to_symbol_scope = SN_REF_SCOPE_LOCAL;
    symbol_def_type = SN_LOCAL_VAR_DEF;
#ifdef TOKEN_DEBUG
    fprintf(tokenout, "local var \"%s\"\n", varname);
#endif
  }

  /* I think setting a global variable should emit
     a symbol declaration. I am not really
     sure if we should emit just one symbol
     declaration, or multiple ones. Multiple
     ones breaks xref but it does present
     the symbol multiple times in the
     file's symbol list which would be
     nice if it worked correctly */

  result = sn_insert_symbol(symbol_def_type,
                            NULL,
			    varname,
			    sn_current_file(),
			    line_start, column_start,
			    line_end, column_end,
			    0,
			    NULL,
			    NULL,
			    NULL,
			    NULL,
			    line_start, column_start,
			    line_end, column_end
                            );
  assert(result == 0);

  /* FIXME: The second argument to sn_insert_xref must be one of SN_FUNC_DEF,
   * SN_MBR_FUNC_DEF, or SN_SUBR_DEF. This is too restrictive, there
   * needs to be an option to pass when not in a function. Currently,
   * we just pretend to be in a function named "GLOBAL".
   */

  if ((ref_to_symbol_type == SN_REF_TO_GLOB_VAR) ||
      ((ref_to_symbol_type == SN_REF_TO_LOCAL_VAR) &&
          ((int) sn_getopt(SN_OPT_LOCAL_VARS) != 0))) {

    result = sn_insert_xref(ref_to_symbol_type,
                 SN_FUNC_DEF, /* Not really in a function definition */
                 ref_to_symbol_scope,
                 NULL,
                 (current_function == NULL) ? "GLOBAL" : current_function,
                 NULL,
                 NULL,
                 varname,
                 NULL,
                 sn_current_file(),
                 line_start,
                 SN_REF_WRITE);

    assert(result == 0);
  }

  free_head_token(); /* VARIABLE */
  free_head_token(); /* ASSIGNMENT_OPERATOR || ASSIGNMENT_OPERATORS */
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 876 "phpbrowser.l"
{
  char* varname = tokens_head->strval;
  SearchEntry entry;
  int line_num = tokens_head->line;
  int ref_to_symbol_type, ref_to_symbol_scope;

#ifdef TOKEN_DEBUG
  fprintf(tokenout, "variable access at token %d\n", token_index);
#endif

  /*
   * If we are not in a function or the variable is in the
   * function's global table then it is a global.
   */

  entry.key = varname;
  entry.key_len = -1;

  if ((current_function == NULL) ||
      (global_var_table &&
        (global_var_table->search( &global_var_table, entry ) != NULL))) {
    ref_to_symbol_type = SN_REF_TO_GLOB_VAR;
    ref_to_symbol_scope = SN_REF_SCOPE_GLOBAL;
#ifdef TOKEN_DEBUG
    fprintf(tokenout, "global var \"%s\"\n", varname);
#endif
  } else {
    ref_to_symbol_type = SN_REF_TO_LOCAL_VAR;
    ref_to_symbol_scope = SN_REF_SCOPE_LOCAL;
#ifdef TOKEN_DEBUG
    fprintf(tokenout, "local var \"%s\"\n", varname);
#endif
  }

  /* FIXME: The second argument to sn_insert_xref must be one of SN_FUNC_DEF,
   * SN_MBR_FUNC_DEF, or SN_SUBR_DEF. This is too restrictive, there
   * needs to be an option to pass when not in a function. Currently,
   * we just pretend to be in a function named "GLOBAL".
   */

  if ((ref_to_symbol_type == SN_REF_TO_GLOB_VAR) ||
      ((ref_to_symbol_type == SN_REF_TO_LOCAL_VAR) &&
          ((int) sn_getopt(SN_OPT_LOCAL_VARS) != 0))) {

    result = sn_insert_xref(ref_to_symbol_type,
                 SN_FUNC_DEF, /* Not really in a function definition */
                 ref_to_symbol_scope,
                 NULL,
                 (current_function == NULL) ? "GLOBAL" : current_function,
                 NULL,
                 NULL,
                 varname,
                 NULL,
                 sn_current_file(),
                 line_num,
                 SN_REF_READ);

    assert(result == 0);
  }

  free_head_token(); /* VARIABLE */
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 939 "phpbrowser.l"
{
#ifdef TOKEN_DEBUG
  fprintf(tokenout, "ate token %d %s", token_index,
          TokenTypeToString(tokens_head));
  if (tokens_head->strval) {
      fprintf(tokenout, " \"%s\"", tokens_head->strval);
  }
  fprintf(tokenout, "\n");
#endif

  free_head_token(); /* ... */
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 952 "phpbrowser.l"

	YY_BREAK
case 39:
YY_RULE_SETUP
#line 954 "phpbrowser.l"
{
#ifdef TOKEN_DEBUG
    fprintf(tokenout, "matched unknown character \"%s\"\n", yytext);
#endif
}
	YY_BREAK
case YY_STATE_EOF(TOKEN):
#line 960 "phpbrowser.l"
{
#ifdef TOKEN_DEBUG
    fprintf(tokenout, "reached EOF in TOKEN buffer\n");
#endif

    assert(tokens_head == NULL);

    yy_delete_buffer( YY_CURRENT_BUFFER );
    yy_switch_to_buffer( original_buffer );
    BEGIN(INITIAL);
    yyterminate();
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(PHP):
#line 973 "phpbrowser.l"
{
  LongString token_buffer;
  char *base;
  int i;
  Token* tok;
  yy_size_t size;
  YY_BUFFER_STATE yybs;

#ifdef TOKEN_DEBUG
  tokenout = fopen("tokens.out", "a");
  fprintf(tokenout, "reached EOF in lex input buffer\n");
#endif

  /* If no tokens were generated, then quit now */
  if (tokens_head == NULL) {
#ifdef TOKEN_DEBUG
    fprintf(tokenout, "no TOKENs generated\n");
#endif
    yyterminate();
  }

  LongStringInit(&token_buffer,0);

  /* Print token info to in memory buffer and then reload
     the input state machine and start out in the TOKEN mode. */

  for (i=0, tok = tokens_head ; tok ; tok = tok->next, i++) {
        int token_length;
#ifdef TOKEN_DEBUG
        fprintf(tokenout, "token %d %s", i, TokenTypeToString(tok));
        if (tok->strval) {
            fprintf(tokenout, " \"%s\"", tok->strval);
            token_length = strlen(tok->strval);
        } else {
            token_length = 1;
        }
        fprintf(tokenout, " (%d.%d -> %d.%d)",
            tok->line,
            tok->column,
            tok->line,
            tok->column + token_length
        );
        fprintf(tokenout, "\n");
#endif
        
        token_buffer.append( &token_buffer, TokenTypeToString(tok), -1);
        token_buffer.append( &token_buffer, " ", -1);
  }

#ifdef TOKEN_DEBUG
  fprintf(tokenout, "token buffer data is \"%s\"\n", token_buffer.buf);
#endif

  original_buffer = YY_CURRENT_BUFFER;
  yy_switch_to_buffer( yy_scan_string(token_buffer.buf) );

  token_buffer.free(&token_buffer);

#ifdef TOKEN_DEBUG
  fprintf(tokenout, "switching to token mode\n");
#endif

  BEGIN(TOKEN);
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 1038 "phpbrowser.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 550 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 550 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 549);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 1038 "phpbrowser.l"


/* Helper method that will print matches as they are made */

static void matched_pattern(char * pattern, char * text) {
    char * mode = "UNKNOWN";
    int imode = YY_START;

    if (imode == INITIAL) {
        mode = "INITIAL";
    } else if (imode == PHP) {
        mode = "PHP";
    } else if (imode == COMMENT) {
        mode = "COMMENT";
    } else if (imode == TOKEN) {
        mode = "TOKEN";
    }

    if (0) {
    fprintf(stderr, "Matched \"%s\", with text \"%s\", in mode \"%s\" (%d.%d)\n",
        pattern, text, mode, sn_line(), sn_column());
    }
}

static void FreeGlobalEntry(SearchEntry *entry) {}


Token* AllocToken() {
    Token* tok = (Token*) ckalloc(sizeof(Token));
    memset(tok, 0, sizeof(Token));
    return tok;
}
void FreeToken(Token* tok) {
    if (tok->strval != NULL) {
        ckfree(tok->strval);
    }
    ckfree((char *) tok);
}

void add_token(Token* tok) {
    if (tokens_tail == NULL) {
        tokens_head = tokens_tail = tok;
    } else {
        tokens_tail->next = tok;
        tokens_tail = tok;
    }
}

void free_head_token() {
    Token* tok;
    assert(tokens_head);
    tok = tokens_head;
    if (tokens_head == tokens_tail) {
        tokens_head = tokens_tail = (Token*) NULL;
    } else {
        tokens_head = tokens_head->next;
    }
    FreeToken(tok);
    token_index++;
}

char * TokenTypeToString(Token *tok) {
    switch(tok->type) {
        case OPEN_PAREN:
            return "OPEN_PAREN";
        case CLOSE_PAREN:
            return "CLOSE_PAREN";
        case OPEN_BRACE:
            return "OPEN_BRACE";
        case CLOSE_BRACE:
            return "CLOSE_BRACE";
        case OPEN_BRACKET:
            return "OPEN_BRACKET";
        case CLOSE_BRACKET:
            return "CLOSE_BRACKET";
        case SEMICOLON:
            return "SEMICOLON";
        case COMMA:
            return "COMMA";
        case VARIABLE:
            return "VARIABLE";
        case ARRAY_VARIABLE:
            return "ARRAY_VARIABLE";
        case ASSIGNMENT_OPERATOR:
            return "ASSIGNMENT_OPERATOR";
        case ASSIGNMENT_OPERATORS:
            return "ASSIGNMENT_OPERATORS";
        case SOMEWORD:
            return "SOMEWORD";
        case KEYWORD:
            return "KEYWORD";
        case FUNCTION_KEYWORD:
            return "FUNCTION_KEYWORD";
        case GLOBAL_KEYWORD:
            return "GLOBAL_KEYWORD";
        case INCLUDE_KEYWORD:
            return "INCLUDE_KEYWORD";
        case DOUBLE_QUOTED_STRING:
            return "DOUBLE_QUOTED_STRING";
        case SINGLE_QUOTED_STRING:
            return "SINGLE_QUOTED_STRING";
        case UNKNOWN:
            return "UNKNOWN";
        default:
            return "TOKEN_NOT_MATCHED";
    }
}
  
void
reset()
{
  sn_reset_line();
  sn_reset_column();
}

int
main(int argc, char *argv[])
{
  return sn_main(argc, argv, group, &yyin, yylex, reset);
}
